### ISSUE TITLE
add .compareKeys method to make easier comparison between key code representations

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#1005]
`.compareKeys(key1, key2)` can take two key representations and return `true` if they match, accounting for representing as ascii codes vs. characters, etc.

**Comment by chrisbrickhouse** [comment]
>accounting for representing as ascii codes vs. characters, etc.

What do you mean by "etc"? What other representations should we expect beyond numerical ascii codes and plain characters?

**Comment by jodeleeuw** [comment]
I was thinking about [this representation](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values), which I'm hoping to shift to and make the default kind of representation in 7.0.

> Is this supposed to be related at all to jsPsych.pluginAPI.compareKeys()? Could that code be moved to core and the API function made into a wrapper of the new core function?

omg. I completely forgot that I already wrote this.
