### ISSUE TITLE
[BUG] CORS error when loading local audio

### ISSUE THREAD

**Issue by alexrockhill** [jspsych/jsPsych#1046]
In the following minimally reproducible example, when I try to run this script with the latest jsPsych, I get the error below in both FireFox and Chrome when run locally:

```
<!DOCTYPE html>
<html>
    <head>
        <title>My experiment</title>
        <script src="js/jsPsych/jspsych.js"></script>
        <script src="js/jsPsych/plugins/jspsych-audio-keyboard-response.js"></script>
        <link href="js/jsPsych/css/jspsych.css" rel="stylesheet" type="text/css"></link>
    </head>
    <body></body>
    <script>

    var sound_trial = {
        type: 'audio-keyboard-response',
        stimulus: './audio/sound.mp3'
    }

    jsPsych.init({
        timeline: [sound_trial]
    })

    </script>
</html>
```
[sound.mp3.zip](https://github.com/jspsych/jsPsych/files/5213242/sound.mp3.zip)

```
Access to XMLHttpRequest at 'file:///.../audio/sound.mp3' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

**Comment by chrisbrickhouse** [comment]
This is a feature of firefox and chrome, not a bug of jsPsych. See [this Firefox support thread](https://support.mozilla.org/en-US/questions/1264280). On Firefox you can bypass the error by going to about:config and setting **privacy_file_unique_origin** to false; caveat being that this policy is meant to fix a security bug. After development, best practice would be to set the field back to true.

**Comment by alexrockhill** [comment]
Thanks! That's great, I have a task that our group wants to be able to run offline as a backup. It sounded a bit extreme to me at the time but given circumstances where I am in Oregon maybe a good idea.
