### ISSUE TITLE
jspsych-markdown-form

### ISSUE THREAD

**Issue by chrisbrickhouse** [jspsych/jsPsych#1047]
Per @erikasf's [comment](https://github.com/jspsych/jsPsych/issues/135#issuecomment-122635662), create a markdown parser that renders html forms for use in experiments. 

Going off the ideas in [this comment](https://github.com/jspsych/jsPsych/issues/135#issuecomment-686832515), I think we'd want the following `jspsych-html-form-*` plugins: 
 - [ ] `jspsych-html-form-checkboxes` (see [`jspsych-survey-multi-select`](https://www.jspsych.org/plugins/jspsych-survey-multi-select/))
 - [ ] `jspsych-html-form-radiobuttons` (see [`jspsych-survey-multi-choice`](https://www.jspsych.org/plugins/jspsych-survey-multi-choice/))
 - [ ] `jspsych-html-form-textboxes` (see [`jspsych-survey-text`](https://www.jspsych.org/plugins/jspsych-survey-text/))
 - [ ] `jspsych-html-form-dropdown` 

Each of these plugins would take javascript objects as their primary input, but with an option for raw html input as a fallback option. We could wrap a markdown parser around it to implement the markdown interface as `jspsych-markdown-form`.

See #135

**Comment by chrisbrickhouse** [comment]
To implement this, we would need a way to have long strings as inputs for plugins. Giving an entire markdown document as a JS string is a bad idea partly because it clutters the code, and additionally other plugins could benefit from a "long string" data type. I suggest we use the html document to store LongString data. To use this plugin as an example, I suggest an implementation like:

```HTML
<html>
  <head>
    <script src='jspsych.js' />
    <script src='plugins/jspsych-html-markdown-form' />
  </head>
  <body>
    <div id="markdown-form" class="long-string">
      Lorem ipsum dolor sit amet
      [ ] Foo?
      [ ] Bar.
      [ ] Biz!
    </div>
  </body>
  <script>
    var form = {
      type: 'html-markdown-form',
      id: 'markdown-form'
    };

    jsPsych.init(...);
  </script>
</html>
```

And the plugin could then perform an operation like:

```javascript
plugin.trial = function( display_element, trial ) {
  var longstring = document.getElementById(trial.id).innerText;
  var form = MarkdownParser( longstring );
  display_element.innerHTML = form;
}
```

**Comment by becky-gilbert** [comment]
Cool! But would that work if you have a different trial on the timeline before the `form` trial? I'm wondering because most plugins clear the screen with `display_element.innerHTML = ""` at the end of the trial, so that would wipe out the markdown-form div, right? If so, I suppose you could set the markdown-form div's visibility to hidden and create a separate div in the body that serves as the display_element (passed to the jsPsych.init settings), but it'd be nice if there was an easier way...

**Comment by chrisbrickhouse** [comment]
I assumed Core added a child to the body tag which it used as the `display_element`, but [it turns out that's not strictly true](https://github.com/chrisbrickhouse/jsPsych/blob/master/jspsych.js#L111). You can specify an ID for the display element in `jsPsych.init()`, but it defaults to the `<body>` tag if none is provided. This would probably require a change to Core where it creates/uses a sub-element of the body tag by default.

**Comment by chrisbrickhouse** [comment]
Actually, wait, it seems to distinguish `DOM_container` and `DOM_target` where `DOM_container` is the `<body>` tag (or whatever you specify) and `DOM_target` is a `<div>` sub-element that actually gets updated by the plugins. I need to read through core more to figure out how these get passed
