### ISSUE TITLE
Documentation type mismatch for slider response plugins

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1058]
Similar to issue #682, the slider response plugins produce a string as the response (final numeric value of the slider) but the docs say that the value of response is an integer: https://www.jspsych.org/plugins/jspsych-audio-slider-response/#data-generated

Following #682, I assume that the value of response in the data should be an integer rather than string. Also, the slider plugins now save the slider's start value, which is currently an integer, so at the very least these should be consistent.

**Comment by jodeleeuw** [comment]
> Following #682, I assume that the value of response in the data should be an integer rather than string. 

Yeah, I agree. I think the `.value` property of the `<input>` element must default to a string. We can convert this before saving in the data.

**Comment by becky-gilbert** [comment]
Got it, thanks!
