### ISSUE TITLE
Inconsistency in *-slider-response parameter names

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1060]
The video-slider-response plugin has a `start` parameter that controls the start time of the video, as well as a `slider_start` parameter for the starting slider value. The other slider response plugins have a `start` parameter that refers to the slider starting value. I propose keeping the parameter names the same in the video-slider-response plugin, and changing `start` to `slider_start` in the other plugins for consistency.
Relates to issue #713 and pull request #714.

**Comment by jodeleeuw** [comment]
Sounds good to me!
