### ISSUE TITLE
Text will not center

### ISSUE THREAD

**Issue by kevinvschie** [jspsych/jsPsych#1078]
I'm a noob to jspsych, but have managed to get a very small timeline running. However, the text is not presented in the center. I've looked in the .css file and it seems that it should center. Any ideas on why this is? I'm using jspsych 6.1.0 software and running the experiment in brave browser. To add, I've tested it in other browsers and I have the same problem there.

**Comment by jodeleeuw** [comment]
I haven't tested the CSS in brave. Have you looked to see whether it is different in another browser?

**Comment by kevinvschie** [comment]
I have also tried Chrome and it’s the same. I’ve send the html to a colleague of mine and he is experiencing the same problem.

**Comment by kevinvschie** [comment]
Same goes for Safari. It's presented in the upper left corner instead of in the middle.

**Comment by jodeleeuw** [comment]
Are you loading the CSS file? It sounds like the file isn't getting loaded correctly.

**Comment by kevinvschie** [comment]
I think I am. I've copy-pasted the code below. 


<<!DOCTYPE html>
<html>
    <head>
        <title>Pocket TNT Learning Phase</title>
        <script src="jspsych-6.1.0/jspsych.js"></script>
        <script src="jspsych-6.1.0/plugins/jspsych-html-keyboard-response.js"></script>
        <link href="jspsych-6.1.0/css/jspsych.css" rel="stylesheet" type="text/css"></link>
    </head>
    <body></body>

    <script>

        /* create timeline */
        var timeline = [];

        /* define welcome message trial */
        var welcome = {
          type: "html-keyboard-response",
          stimulus: "Welcome to the experiment. Press any key to begin."
        };
        timeline.push(welcome);

        /* create the learning procedure */
        var learning_procedure = {
            timeline: [
                {
                    type: 'html-keyboard-response',
                    stimulus: '<span style="font-size:40px;">+</span>',
                    choices: jsPsych.NO_KEYS,
                    trial_duration: 500
                },
                {
                    type: 'html-keyboard-response',
                    stimulus: jsPsych.timelineVariable('pair'),
                    choices: jsPsych.NO_KEYS,
                    trial_duration: 2500
                },
                {
                    type: 'html-keyboard-response',
                    stimulus: '<span style=font-size:25px;">(not at all related) 1 - 2 - 3 - 4 - 5 (extremely related)</span>',
                    choices: ['1', '2', '3', '4', '5'],
                    stimulus_duration: 10000,
                    trial_duration: 10000
                }
            ],
            timeline_variables: [
                { pair: '<span style="font-size:40px;">PHOTO - NOOVE</span>' },
                { pair: '<span style="font-size:40px;">FOOTPRINT - SAND</span>' },
                { pair: '<span style="font-size:40px;">ORCHARD - APPLE</span>' }
            ]
        }

        timeline.push(learning_procedure)

        jsPsych.init({
          timeline: timeline
        });
      </script>
</html>

**Comment by kevinvschie** [comment]
I think I am by having this in my script:

        <link href="jspsych-6.1.0/css/jspsych.css" rel="stylesheet" type="text/css"></link>

**Comment by jodeleeuw** [comment]
That should do it. Can you share the full script?

**Comment by kevinvschie** [comment]
See below


<<!DOCTYPE html>
<html>
    <head>
        <title>Pocket TNT Learning Phase</title>
        <script src="jspsych-6.1.0/jspsych.js"></script>
        <script src="jspsych-6.1.0/plugins/jspsych-html-keyboard-response.js"></script>
        <link href="jspsych-6.1.0/css/jspsych.css" rel="stylesheet" type="text/css"></link>
    </head>
    <body></body>

    <script>

        /* create timeline */
        var timeline = [];

        /* define welcome message trial */
        var welcome = {
          type: "html-keyboard-response",
          stimulus: "Welcome to the experiment. Press any key to begin."
        };
        timeline.push(welcome);

        /* create the learning procedure */
        var learning_procedure = {
            timeline: [
                {
                    type: 'html-keyboard-response',
                    stimulus: '<span style="font-size:40px;">+</span>',
                    choices: jsPsych.NO_KEYS,
                    trial_duration: 500
                },
                {
                    type: 'html-keyboard-response',
                    stimulus: jsPsych.timelineVariable('pair'),
                    choices: jsPsych.NO_KEYS,
                    trial_duration: 2500
                },
                {
                    type: 'html-keyboard-response',
                    stimulus: '<span style=font-size:25px;">(not at all related) 1 - 2 - 3 - 4 - 5 (extremely related)</span>',
                    choices: ['1', '2', '3', '4', '5'],
                    stimulus_duration: 10000,
                    trial_duration: 10000
                }
            ],
            timeline_variables: [
                { pair: '<span style="font-size:40px;">PHOTO - NOOVE</span>' },
                { pair: '<span style="font-size:40px;">FOOTPRINT - SAND</span>' },
                { pair: '<span style="font-size:40px;">ORCHARD - APPLE</span>' }
            ]
        }

        timeline.push(learning_procedure)

        jsPsych.init({
          timeline: timeline
        });
      </script>
</html>

**Comment by kevinvschie** [comment]
Find attached!

[PocketTNT_Learning+Rating.txt](https://github.com/jspsych/jsPsych/files/5286759/PocketTNT_Learning%2BRating.txt)

**Comment by jodeleeuw** [comment]
You've got an extra `<` at the very start of the file. Maybe that is causing some weird behavior?

**Comment by kevinvschie** [comment]
I hadn't even noticed that. I changed it and indeed that was causing the problems! Thanks for your help Josh!
