### ISSUE TITLE
XAB plugin should be generalized to N-alternative forced choice

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#11]
Pretty self-explanatory. Change the XAB plugin so that any number of alternatives can be passed in. Will rename plugin as jspsych-forced-choice.js.

Possible feature: allow sequential or simultaneous presentation of choices.

**Comment by wolfgangwalther** [comment]
I think this can be easily set up with the new timeline features by presenting the stimulus with e.g. the single-stim plugin and then taking the response with the button-response plugin, using images for each button.
For keyboard responses, the multi-stim-multi-response plugin could also be used to do the whole thing.
Should be able to close this, I guess.

**Comment by jodeleeuw** [comment]
Yes, this could definitely be implemented with existing plugins. But I think there is some benefit to having a plugin that smooths over the complications of implementing it with other less straightforward solutions. It's not a high priority for now, in my view.
