### ISSUE TITLE
Add option to prevent response before media ends in audio-*/video-* plugins

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1137]
In audio/video trials, it'd be useful to have the option to prevent the participant from responding before the media has finished playing, and after that point, still allow the response to end the trial. 

It's currently possible to ensure that the media plays through by setting a fixed trial duration and using `response_ends_trial: false`, but in that case, responses would still be allowed before the media has finished playing. It's also possible to do this by setting up two separate trials - the first one plays the media and the second accepts the response - but this means that the stimuli and response data are stored in separate trials, and any on-screen response options (buttons, slider) only appear after the media has finished.

I think this could be implemented in the audio-\*/video-\* plugins by adding a parameter called e.g. `respond_while_playing` that would default to `true` but could be set to `false`. If false, then while the media is playing, any on-screen response options would still appear but would be disabled, and key presses would be ignored. 

This could be implemented by including an if statement that checks the value of `respond_while_playing`, and if false, it disables the response options and sets up an 'ended' event listener on the media element that would enable the buttons/slider or starts the keyboard listener. 

Thoughts?

**Comment by jodeleeuw** [comment]
Sounds great to me! Might even been a small enough adjustment that we could ship it with 6.2?

**Comment by becky-gilbert** [comment]
Great, thanks for the feedback. Yes I was hoping it'd be straightforward enough to add to 6.2. I'll go for it.
