### ISSUE TITLE
jspsych-rdk fixation_cross_color not functional

### ISSUE THREAD

**Issue by lukasshannon** [jspsych/jsPsych#1217]
In the RDK plugin, setting the fixation_cross_color does not change the color of the fixation cross. To fix this issue, in jspsych-rdk.js on lines 958 & 966, change ctx.fillStyle to ctx.strokeStyle

**Comment by becky-gilbert** [comment]
Hi @lukasshannon, thanks very much for flagging this! We did fix this on the master branch version of the RDK plugin:
https://github.com/jspsych/jsPsych/blob/6673c9e90319c1e539466e70ba2f08d5cbe5c80e/plugins/jspsych-rdk.js#L955-L971
Which means it'll be fixed when we release v6.2, so I'll close this issue now. 
Thanks again!

**Comment by lukasshannon** [comment]
That's great! @becky-gilbert any intention to add radial motion to the RDK plugin? I.e. dots expanding or contracting from the origin?

**Comment by becky-gilbert** [comment]
No, we don't have plans to do that. But if you want to add that option in, then we'd welcome the contribution!
