### ISSUE TITLE
Website: Wrong link to data-collected-by-plugins

### ISSUE THREAD

**Issue by gorkang** [jspsych/jsPsych#1225]
It seems there is a problem with the default paragraph present in **all** the plugins:

> <p>In addition to the <a href="overview#datacollectedbyplugins">default data collected by all plugins</a>, this plugin collects the following data for each trial.</p>

Given it is a relative link (a href="overview#datacollectedbyplugins"), it points to: 
https://www.jspsych.org/plugins/[NAME OF THE PLUGIN]/overview#datacollectedbyplugins

But I believe it should point to:
https://www.jspsych.org/plugins/overview/#data-collected-by-plugins
 
Cheers,

**Comment by becky-gilbert** [comment]
Hi @gorkang - yes you're absolutely right. Sorry about the error, and thanks for pointing this out! We'll fix this when we release jsPsych v6.2, at which point we'll update the website documentation.
