### ISSUE TITLE
Retrieving all timeline variables for a given trial

### ISSUE THREAD

**Issue by jkrumbiegel** [jspsych/jsPsych#1237]
I currently have a design that uses a lot of timeline variables, and one annoying aspect is that I sometimes forget adding one of the timeline variables to the data section (I'm actually not sure why they are not automatically put into the data, as otherwise that information is just lost).

So some data section looks like this:

```js
data: {
    segment: "word-classification",
    audiofile: jsPsych.timelineVariable('audiofile'),
    word: jsPsych.timelineVariable('word'),
    trial: jsPsych.timelineVariable('trial'),
    repetition: jsPsych.timelineVariable('repetition'),
    group: jsPsych.timelineVariable('group'),
    choices: jsPsych.timelineVariable('choices'),
}
```

This is because I couldn't find a way to just retrieve all timeline variables, in which case I could just do something like:

```js
data: jsPsych.allTimelineVariables()
```

Is it only possible to ask for one specific variable name and get back whether it exists or not, or is there not an actual list accessible somewhere?

**Comment by becky-gilbert** [comment]
Hi @jkrumbiegel, I don't think there's currently a way to get the list of timeline variables for each trial, but that's a good idea so I've created an issue to suggest it (#1246). 
In the meantime, to make this a little easier and less error-prone, you could create a function that generates your data object containing each variable name and associated timeline variable. Then you would call that function (with parenthesis) in your trial's data parameter, e.g. 
```javascript
function getAllTimelineVars() {
  all_timeline_vars = {
    audiofile: jsPsych.timelineVariable('audiofile'),
    word: jsPsych.timelineVariable('word'),
    trial: jsPsych.timelineVariable('trial'),
    repetition: jsPsych.timelineVariable('repetition'),
    group: jsPsych.timelineVariable('group'),
    choices: jsPsych.timelineVariable('choices')
  }
  return all_timeline_vars;
}

var trial = {
    type: 'html-keyboard-response',
    stimulus: jsPsych.timelineVariable('word'),
    choices: jsPsych.ALL_KEYS,
    trial_duration: 1000,
    data: getAllTimelineVars()
};
```
And if you wanted to add information that changes across trials, blocks etc., you could add some parameters into your function:
```javascript
function getAllTimelineVars(task_seg) {
  all_timeline_vars = {
    audiofile: jsPsych.timelineVariable('audiofile'),
    word: jsPsych.timelineVariable('word'),
    trial: jsPsych.timelineVariable('trial'),
    repetition: jsPsych.timelineVariable('repetition'),
    group: jsPsych.timelineVariable('group'),
    choices: jsPsych.timelineVariable('choices'),
    segment: task_seg
  }
  return all_timeline_vars;
}
```
and then call it like this:
```javascript
data: getAllTimelineVars('word-classification')
```
I hope that helps!

**Comment by jkrumbiegel** [comment]
Hi Becky, thanks for your response! It is true that I could encapsulate the data segment in a function, but that doesn't solve the underlying issue that I have to remember all the timeline variables. It's just moving them to a different place.

I guess it would be easy enough to write this function myself if I understood how the timeline variables are represented. From looking at some of the source code around timelineVariable() it appeared to me that they are looked up dynamically in a hierarchical fashion (traversing up nested timelines) so I guess that makes it problematic to retrieve all variables?

**Comment by becky-gilbert** [comment]
@jkrumbiegel yes, totally agree that the custom function that I suggested doesn't really solve the problem, it just make your code a little less repetitive/error-prone in the meantime. 

I like the `jsPsych.allTimelineVariables()` idea - glad to see that @jodeleeuw added this to the 7.0 milestone. 

Not sure if there's a simple modification you could make to jspsych.js prior to the 7.0 release to automatically grab all of the timeline variables on each trial, but I couldn't see an easy way to do it myself. Maybe @jodeleeuw has suggestions?

**Comment by jodeleeuw** [comment]
I'm imagining that this kind of functionality can be added along with things like #823 and the option to ignore any parameter from the data on a trial by trial basis. Basically, an overhaul of how we manage the trial-level data to allow a lot more customization without these kinds of hacks. 

The timeline variable part may be the trickiest because they are dynamic. I don't think 7.0 will be when we refactor all the underlying code for timelines... that's probably 8.0... but when we do this would be something to think about. The dynamic search upwards in nested timelines should still allow us to recover all the current timeline variables. We can generate a list of all of them as we navigate up the tree.

**Comment by jodeleeuw** [comment]
I implemented a first pass at this in the `features-all-timeline-vars` branch. I added a single test case to the end of `timeline-variables.test.js`. It needs a lot of expansion to make sure this implementation works.

**Comment by jkrumbiegel** [comment]
Thanks for fixing this!
