### ISSUE TITLE
fix HTML5 preloading error caused by stalled event

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1262]
Currently, with HTML5 audio preloading, if audio loading triggers a 'stalled' event, then jsPsych re-starts the file loading process for that file. However the 'canplaythrough' event listener remains attached to the first attempt, so if the stalled file recovers, then it will produce a console error: "Cannot read property 'style' of null at update_loading_progress_bar".

[See discussion here](https://github.com/jspsych/jsPsych/discussions/1130#discussioncomment-139257), and thanks to @kurokida for reporting the problem and figuring out the cause.

Proposed solution is to remove the stalled event listener from `load_audio_file_html5audio` in jspsych.js. It's possible for audio loading to recover after triggering a stalled event, and if it doesn't recover then file loading will time out, so there's no need to re-start the file loading when this happens.

**Comment by kurokida** [comment]
Thank you for your reply.
I agree with you.
