### ISSUE TITLE
can't use canvas-keyboard-response on cognition.run

### ISSUE THREAD

**Issue by defnebuyuky** [jspsych/jsPsych#1334]
I wrote a simple experiment that shows canvas objects and records keyboard responses but there are 80something errors appearing from the jspsych.js file. I am also quiet new to coding experiments in jspsych. So I guess my question/issue is whether the canvas-keyboard-response is "usable" in cognition.run. The experiment runs perfectly fine locally on chrome. Just for reference, some of the errors are:

Uncaught TypeError: Cannot read property 'info' of undefined
    at evaluateFunctionParameters (VM212 jspsych.js:934)
    at doTrial (VM212 jspsych.js:869)
    at startExperiment (VM212 jspsych.js:819)
    at VM212 jspsych.js:2644
    at Object.jsPsych.pluginAPI.module.preloadVideo (VM212 jspsych.js:2515)
    at VM212 jspsych.js:2643
    at Object.jsPsych.pluginAPI.module.preloadAudioFiles (VM212 jspsych.js:2367)
    at VM212 jspsych.js:2642
    at Object.jsPsych.pluginAPI.module.preloadImages (VM212 jspsych.js:2466)
    at Object.jsPsych.pluginAPI.module.autoPreload (VM212 jspsych.js:2641)
evaluateFunctionParameters @ jspsych.js:934
doTrial @ jspsych.js:869
startExperiment @ jspsych.js:819
(anonymous) @ jspsych.js:2644
jsPsych.pluginAPI.module.preloadVideo @ jspsych.js:2515
(anonymous) @ jspsych.js:2643
jsPsych.pluginAPI.module.preloadAudioFiles @ jspsych.js:2367
(anonymous) @ jspsych.js:2642
jsPsych.pluginAPI.module.preloadImages @ jspsych.js:2466
jsPsych.pluginAPI.module.autoPreload @ jspsych.js:2641
(anonymous) @ jspsych.js:203
checkExclusions @ jspsych.js:1032
init @ jspsych.js:198
load (async)
window.jsPsych.core.init @ jspsych.js:226
jsPsych.init @ previewer.js?id=3217bfb0354b10414238:2
(anonymous) @ code.js:21

  | (anonymous) | @ | jspsych.js:796
-- | -- | -- | --
  | TimelineNode | @ | jspsych.js:802
  | (anonymous) | @ | jspsych.js:786
  | TimelineNode | @ | jspsych.js:802
  | init | @ | jspsych.js:179
  | load (async) |   |  
  | window.jsPsych.core.init | @ | jspsych.js:226
  | jsPsych.init | @ | previewer.js?id=3217bfb…:2
  | (anonymous) | @ | code.js:21

VM221 jspsych.js:899 Uncaught TypeError: Cannot read property 'info' of undefined
    at evaluateFunctionParameters (VM221 jspsych.js:899)
    at doTrial (VM221 jspsych.js:834)
    at startExperiment (VM221 jspsych.js:784)
    at VM221 jspsych.js:2569
    at Object.jsPsych.pluginAPI.module.preloadVideo (VM221 jspsych.js:2449)
    at VM221 jspsych.js:2568
    at Object.jsPsych.pluginAPI.module.preloadAudioFiles (VM221 jspsych.js:2295)
    at VM221 jspsych.js:2567
    at Object.jsPsych.pluginAPI.module.preloadImages (VM221 jspsych.js:2400)
    at Object.jsPsych.pluginAPI.module.autoPreload (VM221 jspsych.js:2566)

**Comment by jodeleeuw** [comment]
Has cognition.run added support for jspsych 6.2 yet?

**Comment by jodeleeuw** [comment]
I confirmed that cognition.run has support for 6.2 as of today. @defnebuyuky can you confirm that you are using version 6.2 in cognition.run? 

![image](https://user-images.githubusercontent.com/595524/103237392-6d30fd00-4915-11eb-952e-73228e00e829.png)

**Comment by defnebuyuky** [comment]
Yes I'm using the version 6.2.0. Just a heads up - the canvases seem to only work when I upload the jspsych-canvas-keyboard-response.js file as an external file though. That's how I resolved the issue. I didn't had to do that with other experiments I ran on cognition. I checked again and the canvas related plugins won't work until the related js files are uploaded manually, but they work

**Comment by jodeleeuw** [comment]
Hey @javidalpe, are the new plugins included in cognition.run's deployment of 6.2?

**Comment by becky-gilbert** [comment]
FYI @javidalpe I can confirm that the new canvas-keyboard-response plugin isn't available on cognition.run when v6.2 is selected. I get the error: No plugin loaded for trials of type "canvas-keyboard-response" (I think the errors in the first post in this thread are secondary)

Demo/code: https://nm7ivtveqa.cognition.run/

Older plugins still seem to work fine with 6.2, so I'm guessing Josh is correct that new plugins weren't included or aren't accessible? In the meantime, for anyone else experiencing similar problems: @defnebuyuky suggests a good workaround which is to just upload the plugin file under "External JS/CSS".

**Comment by javidalpe** [comment]
Thank you @defnebuyuky for reporting the error and thank you @jodeleeuw and @becky-gilbert for debugging the problem. You were right, I'm hardcoding the list of available plugins and I didn't even notice that I needed a new list for jspysch 6.2 🤦 Canvas-* and maxdiff were missing 👎 

I've uploaded a new list, tested the experiment and it works!

**Comment by becky-gilbert** [comment]
No problem @javidalpe and thanks very much for the quick fix!
