### ISSUE TITLE
psychophysics plugin

### ISSUE THREAD

**Issue by mingjia1025** [jspsych/jsPsych#1353]
@kurokida 
I have some issues on using psychophysics objects as timeline variables in my jspsych code. On each trial of a training block, subjects should be first presented a stimulus pattern and prompted to respond. After they make a response, the stimulus pattern should stay unchanged but the prompt changed to a feedback depending on their response. 

Now I'm able to show the stimulus as I wanted during the prompt phase but when I pressed a legal key, I was told "the angle and position of the line can't be specified at the same time." After I clicked off the warnings, I was shown a completely scrambled up stimulus... All the psychophysics objects are defined in "trainVariables" (lines 75-170). I suspect that it may be caused by some internal inconsistency in the psychophysics plugin itself, as I specified the stimuli fields of the code blocks for the two phases in exactly the same way. (lines 191 and 241)

In addition, I also sometimes run into incomplete pattern of stimulus (i.e. only showing some of the psychophysics objects) even during the prompt phase. Often times the defective trial is the very first one in the block, but it can occur randomly in the middle of the block.

[test code.txt](https://github.com/jspsych/jsPsych/files/5783179/test.code.txt)

**Comment by kurokida** [comment]
Thank you for using my plugin!

I run your code, but I couldn't see the error message: "the angle and position of the line can't be specified at the same time." 

It is possible that you're using the old jspsych-psychophysics code which include bugs.
Could you download the latest one from 
https://github.com/kurokida/jspsych-psychophysics/releases
The latest version is v2.0.

After that, please let me know which problems have been resolved and which problems remain.
