### ISSUE TITLE
Docs reorganization, move 'dynamic params' to its own page

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1374]
Opening this issue to track the docs changes suggested in [this comment](https://github.com/jspsych/jsPsych/issues/832#issuecomment-759738847) in the css_classes issue thread. 
- Move 'dynamic parameters' section to its own page in Overview, to make it easier to find
- Rename 'Advanced Options for Trials' page? 
- Will the rest of the content on 'Advanced Options for Trials' stay the same?

Once pages are reorganized, we will also need to update any internal links.

**Comment by becky-gilbert** [comment]
This is on the `docs-reorg` branch. As discussed, I did the following:
- created a new overview/dynamic-parameters page
- renamed 'advanced options for trials' (trials.md) to 'plugins'
- incorporated the content from the plugins/overview and plugins/creating-a-plugin pages into the new overview/plugins page
- removed the plugins/overview and plugins/creating-a-plugin pages

**Comment by jodeleeuw** [comment]
Awesome! I'm going to merge this branch since I'm working on docs edits in the master branch right now and I want to have everything be consistent.
