### ISSUE TITLE
Hide mouse cursor on a trial

### ISSUE THREAD

**Issue by grocio** [jspsych/jsPsych#1404]
I'd like to hide the mouse cursor and allow keyboard input at a trial-level (surprisingly, hiding the cursor disables keyboard input in a certain case). I know a solution but I'd like to know best practices.

In a relevant thread on jsPsych's google group [https://groups.google.com/g/jspsych/c/edptYoa0JBc](https://groups.google.com/g/jspsych/c/edptYoa0JBc), @jodeleeuw recommends using the CSS style. So, I tried 
```javascript
var cursor_off = {
    type: 'call-function',
    func: function() {
        document.body.style.cursor= "none";
    }
}

var cursor_on = {
    type: 'call-function',
    func: function() {
        document.body.style.cursor= "auto";
    }
}

timeline.push(cursor_off, some_trial, cursor_on);
```
It made cursor invisible/visible. **It, however, disabled keyboard input (i.e., html-keyboard-response in my case).** I assume that it is because {cursor: "none";} in body makes the web page inactive (not focused).

Then, I used a new feature (#832; custom CSS class per trial). Specifically, I added
```javascript
<style>
.hide_cursor {
    cursor: none;
}
</style>
```
and I applied this CSS style to a trial

```javascript
var trial = {
    type: 'html-keyboard-response',
    stimulus: '331',
    choices: ['j','k','l', 'J', 'K', 'L'],
    css_classes: ['hide_cursor']
};
```

It hided the mouse cursor only if it is on the stimulus. The region of the stimuli (e.g., '331') was small. So, I increased its region by using padding in the CSS style (`padding: 30%`).

This worked well. I show an example below,
```javascript
... someting ...

<style>
.hide_cursor {
    cursor: none;
}
.stimulus_size {
    padding: 30%;
}
</style>

... something ...

var trial = {
    type: 'html-keyboard-response',
    stimulus: '331',
    choices: ['j','k','l', 'J', 'K', 'L'],
    css_classes: ['hide_cursor', 'stimulus_size']
};
```
It worked well as I intended and this is a tentative solution. I wonder if you could suggest a more elegant solution?

**Comment by jodeleeuw** [comment]
I'm converting this to a discussion post.
