### ISSUE TITLE
Loading .txt file for stimulus presentation

### ISSUE THREAD

**Issue by awb99cu** [jspsych/jsPsych#1412]
I'm new to JSPsych, but I've been trying to construct a free recall experiment in which word lists are loaded into javascript from a text file on the host computer. I've tried a number of solutions such as fileReader and ajax, but I can't get any of them to work in Chrome. 

Is there a way to read text files into jsPsych as one would an image file, and present them serially as a list?

Thank you,
Adam

**Comment by jodeleeuw** [comment]
Converting this to a discussion
