### ISSUE TITLE
new plugin: jspsych-iat

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#146]
Create implicit association test (IAT) plugin.

**Comment by cestq** [comment]
where is the IAT plugin?

**Comment by jodeleeuw** [comment]
The plugin doesn't exist yet, but is on the list of things to develop. It is possible to run an IAT using the single-stim plugin, but it will be easier to do so once an IAT-specific plugin is created.

**Comment by cestq** [comment]
I‘m creating an IAT using the single-stim plugin(I have done IAT using Inquisit and js+html+django  ago),but I have some question.
1,The single-stim example's stimuli is image,how is it using text?
2,Your website http://docs.jspsych.org/features/data/  data storage is using PHP script,how is it using python and django.
3,What environment is jsPsych applicable 
All os？ All browser version？
4,Will Internet speed ,Os or browser impact jsPsych’s rt ？ Because I want to use this date for psychology reserch

**Comment by jodeleeuw** [comment]
It's possible to use text in the single-stim plugin by setting the `is_html` parameter to `true`. See the last example on the documentation page: http://docs.jspsych.org/plugins/jspsych-single-stim/.

I've never used django in combination with jsPsych, but I'm sure it's possible. I've used python indirectly, by combining jsPsych with [psiturk](http://www.psiturk.org).

jsPsych can be used on any OS with almost all browsers. Some very old browsers will not support some of the features.

The RT issue is a bit complicated, but the short answer is that for most RT research, jsPsych will do just fine. For a more thorough discussion and some empirical data, see [our recent Behavior Research Methods paper] in which we compare RT distributions collected with MATLAB and JavaScript.

**Comment by cestq** [comment]
TKS,

I have some question about data storage and python

function save_data(data){
   var data_table = "my_experiment_table"; // change this for different experiments
   $.ajax({
      type:'post',
      cache: false,
      url: '/get_iat', // change this to point to your php file.
      // opt_data is to add additional values to every row, like a subject ID
      // replace 'key' with the column name, and 'value' with the value.
      data: {
          table: data_table,
          json: JSON.stringify(data),
          opt_data: {key: value}
      },
      success: function(output) { console.log(output); } // write the result to javascript console
   });
}

when I use above code,some error like:
Uncaught ReferenceError: value is not defined

Can u give me some python code?

**Comment by jodeleeuw** [comment]
This isn't the appropriate place to discuss this. This thread is for discussion about the IAT plugin issue. Feel free to submit your questions to the support group (https://groups.google.com/forum/#!forum/jspsych).

**Comment by JHonaker** [comment]
@jodeleeuw Just wanted to you to know, I'm about to start working on an IAT plugin.

**Comment by jodeleeuw** [comment]
Great! I have a student working on one right now as well, and she's making good progress. I suspect we'll be able to release it in December. If you need it sooner, then no need to wait for us.

**Comment by JHonaker** [comment]
I just saw that someone else sent a PR with their version as well, but you had some objections to their structure. Could you elaborate a little on what your specific objections were? I'd like to get it finished before December, but I don't want to repeat the same mistakes they did.

**Comment by jodeleeuw** [comment]
The main issue was that the plugin was not self-contained. It expected a particular kind of DOM structure that it did not create (particular div elements for the left and right side of the screen). It's important that the plugin creates all of the DOM elements it needs and cleans them up when it is done.

**Comment by JHonaker** [comment]
I've finished an implementation that works for text, and I'm working on getting images for stimuli next (shouldn't be very hard). I just wanted to ask about the plugin.info versus defining defaults inside of the definition of the plugin variable.

I noticed that the plugin.info stuff is not in the documentation, but it is in the single-stim plugin I'm basing my plugin off of. Should I worry about defining the plugin info? I think I get the basics of it, but I was just wondering if it was still in development.

**Comment by jodeleeuw** [comment]
The `plugin.info` method is for the GUI in development. The spec is still changing, so don't worry about implementing that piece right now. We can always add it in later once the spec is final.

**Comment by JHonaker** [comment]
Alright, I'll write up an example case and send the pull request tomorrow or Tuesday.

**Comment by JHonaker** [comment]
Sorry it took me so long. I had a busy week. I just submitted the PR #307

**Comment by jodeleeuw** [comment]
An IAT plugin has been merged!

@JHonaker thanks for your PR. I had a student working on the IAT and ended up merging her version into the library.
