### ISSUE TITLE
Loops Should be able to be looped.

### ISSUE THREAD

**Issue by dubailey** [jspsych/jsPsych#1468]
Hello, I am trying to loop a loop trial but when I do this it only loops the inner most trial (the trial that is already being looped), this is not conducive to being able to make more complex jsPsych experiments.

**Comment by jodeleeuw** [comment]
Hi @dubailey,

Can you explain a bit more? I'm not sure I understand the problem that you are running into.

**Comment by dubailey** [comment]
Hi, I have a trial that is looped. When I try to loop the loop, what ends
up just happening is the inner most trial is only looped once instead of
being double looped.

**Comment by jodeleeuw** [comment]
Can you post a code snippet to reproduce the problem?

**Comment by jodeleeuw** [comment]
I'm going to close this until we get more information. Happy to reopen if needed.
