### ISSUE TITLE
Provide version number

### ISSUE THREAD

**Issue by amunn** [jspsych/jsPsych#1472]
When updates change core functionality (e.g. 6.1 -> 6.2 changed the name of the slider start parameter) it's helpful to be able to know which version of jpsych an experiment is running. But it seems that there is nowhere in the code (even in the comments) that shows the version number. It would be helpful to add this parameter that could be tested for.

**Comment by jodeleeuw** [comment]
I've been meaning to do this. Thanks for the nudge!
