### ISSUE TITLE
Can't get audio to play

### ISSUE THREAD

**Issue by hwirth** [jspsych/jsPsych#1503]
Some poor non-programmer asked for help on IRC, so I looked at this library.

After fiddling around for about one hour, I noticed the examples folder, but not even the
audio-button/audio-keyboard examples produce any sound for me. So I am suspecting some problem with jsPsych.

The person in question reports hearing one "click" with our basic test program, but no real sound, on Brave and Safari.

I ran a test program, that I made following the tutorials on the web page, as well as the program the person I tried to help made, and the examples

jspsych-audio-button-response.html
jspsych-audio-keyboard-response.html

 from both my local Apache and from my actual web space without success.
I tried it with Firefox 84.0 and Chromium 87.0.4280.88 on Arch Linux.

Edit: The user just reported, that using version 6.2.0 did produce sound for them.

**Comment by jodeleeuw** [comment]
The master branch is currently under development as we merge various branches prior to releasing 6.3. It looks like audio is currently broken on the master branch, but we know why and it'll be fixed prior to release. 

It sounds like using 6.2 worked OK, so I'm closing this issue.
