### ISSUE TITLE
Record key codes and timing

### ISSUE THREAD

**Issue by angoodkind** [jspsych/jsPsych#1515]
This may be too vague, but I am having a difficult time writing an experiment that records all of the key codes and timing for a free text entry experiment. I see some issues have addressed this, but am having trouble putting it all together.

**Comment by jodeleeuw** [comment]
Going to convert this over to a discussion. Not sure if you've spotted the discussions that are separate from issues, but this has been talked about there, too. Some of those threads do have some example code.

 I think as it currently stands it is too open-ended for us to provide solid advice with a reasonable time investment, but if there are specific issues that you run into we can probably help more.
