### ISSUE TITLE
Stop parameter for video plugins doesn't actually stop video

### ISSUE THREAD

**Issue by stvncao5** [jspsych/jsPsych#1533]
If specifying the stop parameter in a video plugin like so:
```javascript
	// Create pre-experiment primer.
	let primer = {
		type: 'video-keyboard-response',
		stimulus: ['videos/primer.mp4'],
		start: 1.0,
		stop: 6.0,
		trial_ends_after_video: true,
	}
```
The trial will not actually end at the 6s mark, when the video is supposed to end (as specified by `trial_ends_after_video`). The video only seems to be paused rather than actually stopped.

I'm also not sure if this is a related or separate issue, but specifying the "start" parameter at 0.0 results in the video not playing at all.

**Comment by becky-gilbert** [comment]
Thanks @stvncao5, we'll take a look at this as soon as possible.
