### ISSUE TITLE
addNodeToEndOfTimeline not working

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1538]
I'm checking all of the master branch example HTML files and noticed that the jsPsych.addNodeToEndOfTimeline example isn't working. The page is blank after the first trial, with no console error. There's nothing in the display element, which suggests the trial isn't being added (as opposed to it being an issue with e.g. image rendering). @jodeleeuw could this be a problem that was introduced during changes to jspsych.js? I'll look into it as soon as I get a chance.

**Comment by jodeleeuw** [comment]
This was just because we dropped support for the preloading-based `callback` and the example was using the callback. I just patched it.

**Comment by jodeleeuw** [comment]
This was just because we dropped support for the preloading-based `callback` and the example was using the callback. I just patched it.

**Comment by becky-gilbert** [comment]
Aha, totally missed that. Thanks!
