### ISSUE TITLE
image-keyboard-response: add the recording of mouse click coordinates x, y

### ISSUE THREAD

**Issue by DominiqueMakowski** [jspsych/jsPsych#1542]
Hi! I'm trying to add to the `image-keyboard-response` plugin the ability to record mouse clicks. 

I've looked at the `serial-reaction-time-mouse` plugin, as it's the only place I found some mouse-tracking, and based on that and some googling, I've added [these lines](https://github.com/RealityBending/JSmisc/blob/29d225d1a2f21ed954343e1c8b510eeba396a43b/jspsych_extensions/image-keyboardmouse-response.js#L172-L180) below what I believe does the drawing of the stimulus:

```js
    img.addEventListener('mousedown', function (event) {
      console.log("X: " + event.clientX + ", Y: " + event.clientY)
      console.log("X: " + event.pageX + ", Y: " + event.pageY)
    })
```

With the goal or - at first - simply printing the position of the mouse when there's a click on the image (I've read that there's pageX and clientX, which can be different). Down the road, I'd like to record the position, as well as the RT of the click, in the data.

Unfortunately, nothing is printed... as if the event listener wasn't active... Would you have any leads on how to make this work? Thanks a lot!

**Comment by GEJ1** [comment]
Hi @DominiqueMakowski , I was working on something similar in order to create a new plugin: https://github.com/jspsych/jsPsych/discussions/1370

Maybe you can use it or take the logic from the code https://github.com/GEJ1/draw-and-mouse-tracking

**Comment by DominiqueMakowski** [comment]
Thanks @GEJ1! 
Turns out we managed to make it work as we wanted (see [here](https://github.com/RealityBending/JSmisc/blob/main/jspsych_extensions/image-keyboardmouse-response.js)) ☺️
