### ISSUE TITLE
'Enter','ArrowRight','ArrowLeft' as Invalid key string

### ISSUE THREAD

**Issue by BastienBlain** [jspsych/jsPsych#1558]
Hi there,

I'm using jspsych-6.2.0 and I specified the following plugin for example as below: 

```
var XX = {
  type: "html-keyboard-response",
  stimulus: "YY",
  choices: 'ArrowRight',
};
```

Nothing happened when I did  then press the right arrow while seeing YY, that is, the next screen is not displayed. There is no error message. I tried chrome and internet explorer and both lead to the same issue. 

If instead I replace 'ArrowRight' by 'f', then pressing 'f' works (in that I move to the next screen). 

Pressing the right arrow e.g. on https://www.freecodecamp.org/news/javascript-keycode-list-keypress-event-key-codes/ does return the relevant code.

Any idea of what could be wrong? 

Thanks for your help!

**Comment by becky-gilbert** [comment]
Converting this to a discussion.
