### ISSUE TITLE
link to eye-tracking overview is broken

### ISSUE THREAD

**Issue by tobiasgerstenberg** [jspsych/jsPsych#1562]
link is on this page: https://www.jspsych.org/extensions/jspsych-ext-webgazer/
and goes here https://www.jspsych.org/overview/eye-tracking.md (but this shows 404 - not found)

**Comment by becky-gilbert** [comment]
Thanks @tobiasgerstenberg! @jodeleeuw ok for me to fix this and redeploy the docs?

**Comment by jodeleeuw** [comment]
Yes, thanks!

**Comment by becky-gilbert** [comment]
Should be fixed now 👍
