### ISSUE TITLE
Automatically save post_trial_gap value?

### ISSUE THREAD

**Issue by ricardoV94** [jspsych/jsPsych#1564]
Is there a way to record the post_trial_gap duration (e.g., when this is randomly generated)? 

I have been using a workaround where I generate all the `itis` in advance and then simply index it based on a trial counter. This way I can save it in advance in the respective trial data. I wonder if there is / could be a better way to save this information.

**Comment by becky-gilbert** [comment]
Hi @ricardoV94, this is now possible with [the `save_trial_parameters` option](https://www.jspsych.org/overview/plugins/#the-save_trial_parameters-parameter) in jsPsych v6.3.0. You can do this:
```js
var trial = {
  // ... other parameters ...
  post_trial_gap: function() {
    return jsPsych.randomization.sampleWithoutReplacement([500,600,700],1)[0];
  },
  save_trial_parameters: {
    post_trial_gap: true
  }
};
```
If you're using an earlier version of jsPsych, then I think what you're doing now make sense. Another option is to use a global (top-level) variable to store the current ITI value, and use [dynamic parameters](https://www.jspsych.org/overview/dynamic-parameters/) to update the value of this variable during each trial and save the current value to the data:
```js
var current_iti;
var trial = {
  // ... other parameters ...
  post_trial_gap: function() {
    current_iti = jsPsych.randomization.sampleWithoutReplacement([500,600,700],1)[0];
    return current_iti;
  },
  data: function() {
    return {iti: current_iti};
  }
}
```

**Comment by ricardoV94** [comment]
That is great. I am actually already using v6.3, so there is no need for anything else. Thanks for the prompt reply!
