### ISSUE TITLE
issues with 'Spacebar' as key press option: instruction trial type throws error

### ISSUE THREAD

**Issue by apileggi** [jspsych/jsPsych#1603]
Hi there, anything using ['Spacebar'] as a key press was working until I switched from an earlier version to jsPsych-6.3.0. 
No other code changes and it seems ['Spacebar'] is no longer a valid option. 

In html-keyboard-response, everything just hangs, no errors are shown in the console.

For instructions, console says:

jspsych.js:2308 Uncaught TypeError: v.toLowerCase is not a function
    at jspsych.js:2308
    at Array.map (<anonymous>)
    at Object.listener_function [as fn] (jspsych.js:2308)
    at HTMLBodyElement.root_keydown_listener (jspsych.js:2236)

Note: If I use key_press: 'P' or some other character, it works. But 'Spacebar' does not.

**Comment by jodeleeuw** [comment]
Hi @apileggi,

We changed how keys are represented in 6.3 to conform with modern web browser standards.

Try using `[' ']` instead with 6.3.

We're using the `event.key` property and you can see those values on sites like [this one](https://keycode.info/).

**Comment by apileggi** [comment]
[' '] was the fix indeed!

Thank you!
