### ISSUE TITLE
addNodeToEndOfTimeline do not execute preload_callback

### ISSUE THREAD

**Issue by mupsycho** [jspsych/jsPsych#1616]
i notise that there was a problem in `core.addNodeToEndOfTimeline`
```js
  core.addNodeToEndOfTimeline = function(new_timeline, preload_callback){
    timeline.insert(new_timeline);
  }
```
Maybe you can use this to fix it
```js
  core.addNodeToEndOfTimeline = function(new_timeline, preload_callback){
    timeline.insert(new_timeline);
    if(typeof preload_callback !== 'undefinded'){
      preload_callback();
    }
  }
```

**Comment by jodeleeuw** [comment]
Thanks, @mupsycho ! We intentionally removed support for the `preload_callback` with version 6.3.0 because we shifted preloading to the `preload` plugin. Now one could stick a preloading trial on the new timeline to accomplish the same thing.

**Comment by mupsycho** [comment]
all right。Thanks for answer。
however，if it is right, i think the following code can not work
```js
jsPsych.addNodeToEndOfTimeline({
                    timeline: []
  }, function(a){
  // with other code
});
```
or maybe this style is my personal habit
in fact, I haven't tested the following code
```js
jsPsych.addNodeToEndOfTimeline({
                    timeline: []
  });
// with other code
```
however, i find that `addNodeToEndOfTimeline` can work without `resumeExperiment`, it is amazing

**Comment by jodeleeuw** [comment]
Right, we've deprecated the first case. If you want to run code at the start of the new timeline you could put a `call-function` plugin on the timeline.
