### ISSUE TITLE
I found an error on the website

### ISSUE THREAD

**Issue by nrschoen** [jspsych/jsPsych#1642]
Check out the picture of this page: https://www.jspsych.org/core_library/jspsych-randomization/

![Screen Shot 2021-03-17 at 10 40 15](https://user-images.githubusercontent.com/65179042/111455387-a35c6c80-870d-11eb-90a6-c465812edf9f.png)

**Comment by becky-gilbert** [comment]
Thanks for reporting this @nrschoen! Feel free to submit a pull request to fix this if you'd like to. Otherwise we'll fix it ASAP 👍

**Comment by becky-gilbert** [comment]
Fixed via 163f3479b0655b8e3f5fc55f0d80d0c4e14ce1ed. I think the problem was that code blocks must have a line break after the ending backticks (\```).
