### ISSUE TITLE
Generalize the on_load event handler to ensure that trial has completed loading

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#1666]
Currently the `on_load` event for a trial fires when the `plugin.trial` method completes. In most cases this works fine because the `plugin.trial` code is synchronous. But, if there is async code of any kind that delays the loading of the screen, then the `on_load` event could fire before the trial is really loaded.

We need some way of giving plugins control over when the load event is triggered. It would be nice if the default mode required no additional implementation, and this control was optional.

**Comment by bjoluc** [comment]
Maybe allowing `plugin.trial` to return a promise? Would be backwards-compatible and pretty intuitive. Although users that need to support very old browsers ([< 2014](https://caniuse.com/?search=promise)) might need to polyfill.
