### ISSUE TITLE
RT unit inconsistency and minimum_valid_rt

### ISSUE THREAD

**Issue by kinleyid** [jspsych/jsPsych#1675]
Hello! I've run into an issue specifying the minimum_valid_rt for experiments with some trials that record RTs using the "performance" method and some that use the "audio" method. The "performance" method records RTs in milliseconds while the "audio" method records RTs in seconds, at least within jsPsych.pluginAPI.getKeyboardResponse(). This means that if minimum_valid_rt is specified in seconds, it won't work for trials that use the "performance" RT method, whereas if it is specified in milliseconds it won't work for the "audio" method. I think the easiest way to fix this would be to create a variable called something like "rt_ms" within the function that tests for RTs less than minimum_valid_rt:
```
var rt_ms = rt;
if (parameters.rt_method == 'audio') {
  rt_ms = rt_ms * 1000;
}
if(rt_ms < minimum_valid_rt) {
  return;
}
```

**Comment by becky-gilbert** [comment]
Thanks very much for flagging this issue and suggesting a solution! We'll have a look at this ASAP.

**Comment by becky-gilbert** [comment]
Fixed this for the next release. Thanks again @kinleyid!
