### ISSUE TITLE
Can jsPsych be used mobile phone

### ISSUE THREAD

**Issue by cestq** [jspsych/jsPsych#168]
same title

**Comment by jodeleeuw** [comment]
The short answer is yes.

The longer answer is that jsPsych's core features will all work on a mobile phone, but many of the plugins are designed for desktop use and won't work on mobile devices. You may need to modify plugins to get them to work on a mobile phone. For example, many plugins rely on keyboard presses but on many mobile devices the keyboard only appears when the focus is on a text input element.
