### ISSUE TITLE
Problem with unfinished status in cognition. run

### ISSUE THREAD

**Issue by python2020-maker** [jspsych/jsPsych#1767]
Hi,

I have a problem with unfinished status and the problem is not solved by refreshing. Also worth mentioning that the Timeline is not in green color as what is shown in the Tutorial by Josh, showing unfinished in view.

Is there anybody to help?

**Comment by jodeleeuw** [comment]
Hi @python2020-maker,

We'll need more information here. Can you share some of your code? What do you mean by unfinished status?

(Please use the [discussions board](https://github.com/jspsych/jsPsych/discussions) for Q&A support)
