### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by python2020-maker** [jspsych/jsPsych#1768]
Hi, 

I can run the experiment but the data is not saved and this error in console: Failed to load resource: the server responded with a status of 404 ()

How can this issue be solved? Is there anybody to help?

**Comment by jodeleeuw** [comment]
Hi @python2020-maker,

We'll need more information to be able to help. Where are you running your experiment? How is the data being saved? What file is the 404 error referencing?
