### ISSUE TITLE
Wrong title in documentation for jspsych-webgazer-validate

### ISSUE THREAD

**Issue by moltaire** [jspsych/jsPsych#1782]
The documentation page is titled "calibrate". I've made a pull request for a fix ( #1781).
This was my first pull request in a long time, so I hope I got it all right, even if it's such a minor issue.

**Comment by becky-gilbert** [comment]
Oops, don't know how we missed that 🤦 Thanks very much for flagging it, and for submitting the fix! 
The pull request looks good to me. If @jodeleeuw is happy with it then I'll merge it and re-deploy the docs.

**Comment by becky-gilbert** [comment]
FYI, docs have been re-deployed so this change is live now 👍
