### ISSUE TITLE
require_movement in slider plugins don't allow for using only the keyboard 

### ISSUE THREAD

**Issue by gorkang** [jspsych/jsPsych#1783]
In #696 the `require_movement` conditional was changed from `'change'` to `'click'`. This solves an important issue, but creates a new one. Now, if someone is using the keyboard to answer the slider questions (TAB + arrows + TAB + space), the button won't activate. This is very common between computer savvy participants (e.g. Mechanical Turkers)

Not sure if there is an easier solution but adding a second conditional allows for both behaviours (only mouse or only keyboard). 

So, changing:

```
    if(trial.require_movement){
      display_element.querySelector('#jspsych-html-slider-response-response').addEventListener('click', function(){
        display_element.querySelector('#jspsych-html-slider-response-next').disabled = false;
      });
    }
```

For this:
```
    if(trial.require_movement){
      display_element.querySelector('#jspsych-html-slider-response-response').addEventListener('click', function(){
        display_element.querySelector('#jspsych-html-slider-response-next').disabled = false;
      });
      display_element.querySelector('#jspsych-html-slider-response-response').addEventListener('change', function(){
        display_element.querySelector('#jspsych-html-slider-response-next').disabled = false;
      });
    }
```
Seems to solve the issue.

**Comment by becky-gilbert** [comment]
Thanks for flagging this @gorkang! This solution seems very sensible to me.
