### ISSUE TITLE
Does not stay in the loop

### ISSUE THREAD

**Issue by steffejr** [jspsych/jsPsych#1799]
Hello, 
I am trying to use a loop and this example does not stay in the loop. No matter which key is pressed the example goes to the conditional function.

https://github.com/jspsych/jsPsych/blob/ab7ea845df8d12badc74cc338ebb1599e77efd41/examples/conditional-and-loop-functions.html#L17

Jason

**Comment by becky-gilbert** [comment]
HI @steffejr, that's odd - I just tried this example file in jsPsych v6.3.0 and 6.3.1 and they're both working for me. When I press "r", the trial repeats. Which jsPsych version are you using?

**Comment by steffejr** [comment]
That was it, thank you. I was using version 6.2.0. Once I changed to 6.3.1 the problem was solved. Thank you very much,
Jason
