### ISSUE TITLE
Audio buffer error

### ISSUE THREAD

**Issue by moramaldonado** [jspsych/jsPsych#1823]
Hi, 

I am getting the following error with the audio-keyboard-response plugin: 

 103 Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Failed to convert value to 'AudioBuffer' 

I don't get the error when I try the experiment locally. 

Do you know what can be causing it?

Thanks!

**Comment by jodeleeuw** [comment]
I would start with checking the path to make sure the audio file is where you expect it is on the server.

**Comment by moramaldonado** [comment]
The path is correct, as far as I can tell (in both cases: http://www.syncog.ppls.ed.ac.uk/stim/audio_neg/Who%20is%20running%3f.wav).  

When I run the experiment locally, I get:

AudioBuffer {length: 71883, duration: 1.63, sampleRate: 44100, numberOfChannels: 1}
duration: 1.63
length: 71883
numberOfChannels: 1
sampleRate: 44100
__proto__: AudioBuffer

When I run it on the server:

Promise {<pending>}
__proto__: Promise
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: AudioBuffer

**Comment by becky-gilbert** [comment]
Hi @moramaldonado, sorry about the delay with this issue. I'm not sure that I'll be able to replicate this, but I can try. It would help if you could share a minimal reproducible example, or a link to your experiment on the server, so that I can take a look at the problem. Thanks!

**Comment by jodeleeuw** [comment]
I'm going to close this, but happy to re-open if we get a reproducible example.
