### ISSUE TITLE
No plugin loaded for trials of type "visual-search-circle"

### ISSUE THREAD

**Issue by RachelCarmenMoreau** [jspsych/jsPsych#1826]
I have been trying to load in the plugin for visual-search-circle but it keeps throwing the same errors:

>no plugin loaded for trials of type "visual-search-circle"
>Uncaught TypeError: Cannot read property 'info' of undefined

I originally assumed I was calling the plugin incorrectly but I have checked over and over and still can't see anything wrong.

```
<head>
    <title>Experiment</title>
    <script src="jspsych/jspsych.js"></script>
    <script src="jspsych/plugins/jspsych-html-keyboard-response.js"></script>
    <script src="jspsych/plugins/jspsych-image-keyboard-response.js"></script>
    <script src="jspsych/plugins/jspsych-external-html.js"></script>
    <script src="jspsych/plugins/jspsych-survey-html-form.js"></script>
    <script scr="jspsych/plugins/jspsych-visual-search-circle.js"></script>
  </head>
```

Calling it at the very beginning. Then I just copied and pasted in the example from 
https://www.jspsych.org/plugins/jspsych-visual-search-circle/
To test it and it doesn't wanna work.

Any ideas?

**Comment by becky-gilbert** [comment]
Hi @RachelCarmenMoreau, it looks like there's a type in the `script` line for the visual search circle plugin - it should be `src` rather than `scr`. Could you try fixing that and see if it works? Another thing to check is that the plugin file is in your jspsych folder and that the file name is spelt the same way as in your `script` tag that loads the file.

**Comment by RachelCarmenMoreau** [comment]
> Hi @RachelCarmenMoreau, it looks like there's a type in the `script` line for the visual search circle plugin - it should be `src` rather than `scr`. Could you try fixing that and see if it works? Another thing to check is that the plugin file is in your jspsych folder and that the file name is spelt the same way as in your `script` tag that loads the file.

Hey! The first solution worked. Thanks :)

**Comment by becky-gilbert** [comment]
Great! 👍
