### ISSUE TITLE
7.0 Release Notes

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#1827]
# New Features

# Changes
- Added links to the [jsPsych-builder](https://github.com/bjoluc/jspsych-builder) CLI tool on the [Running Experiments](https://www.jspsych.org/overview/running-experiments/) and [Hello World](https://www.jspsych.org/tutorials/hello-world/) documentation pages. jsPsych Builder uses modern web development tools such as Node, webpack, and Babel to make it easier to develop and package jsPsych experiments. Thanks @bjoluc! (#1855, #1912)
- Added live demos to the Example code snippets on the plugin documentation pages, to make it easier to see what the plugins and their parameters do. Thanks @kurokida and @SHogenboom!

# Bug Fixes
- Fixed documentation errors (#1820, #1781, #1782, #1840, #1981). Thanks @AndrianV, @moltaire, @LMD-nat, and @nikbpetrov!
- The same-different-html and same-different-image plugins incorrectly used `null` as the default values for the `first_stim_duration` and `second_stim_duration` parameters. The defaults for these parameters have been changed to 1000 ms, which is consistent with the plugin documentation. Thanks @nikbpetrov! (#1879, #1880)
- In the video-* plugins, fixed bug that meant the trial did not end when the `trial_ends_after_video` parameter was set to `true` and the video ended at a specific time via the `stop` parameter. (#1533)

**Comment by jodeleeuw** [comment]
This was made obsolete by the introduction of changesets.
