### ISSUE TITLE
Add reference to jspsych-builder?

### ISSUE THREAD

**Issue by bjoluc** [jspsych/jsPsych#1855]
Hi everyone, I've been maintaining a tool called [jspsych-builder](https://github.com/bjoluc/jspsych-builder) for a while that takes over the manual jsPsych setup tasks, offers a development server with hot reload, and a build toolchain including webpack and babel. It also supports JATOS out of the box.
By now, we've been using it successfully in several courses at Paderborn and Marburg University and so far have had a good experience with it (the courses were attended by both JavaScript newbies and advanced users).
If this is welcome, I'm happy to add a reference to the documentation so others can find it more easily. What do you think?

**Comment by jodeleeuw** [comment]
hey @bjoluc 

This looks really useful. I'd be happy to include a reference to it in the docs. I'm not sure what the best spot is for it, but I'm open to suggestions.

I think your input would also be useful as we think about migrating to support ES6 modules in version 7.0. It looks like you are already dealing with some of the issues we're going to encounter. Any interest in helping out with that phase of things?

**Comment by becky-gilbert** [comment]
Thanks for pointing us to this @bjoluc! I wonder if we could add a section about jspsych-builder to the [overview/running-experiments](https://www.jspsych.org/overview/running-experiments/) page? Perhaps inside the Online section, or in its own section? Let me know if I can help by writing a first draft of the docs section or giving feedback.

And just to echo what Josh said - it'd be great to have your help with the switch to ES6 module support. Personally I think it'd be great to continue to offer jsPsych in its current form (as a simple set of scripts, alongside a module version), and I'm wondering if that might be possible with webpack?

**Comment by bjoluc** [comment]
Hi @jodeleeuw and @becky-gilbert,
I'm glad you welcome this! The running section would certainly be a good spot. An own section there would probably make sense since jspsych-builder in general is deployment-agnostic. Nevertheless, I think, an additional hello-world-like tutorial for jspsych-builder could also be helpful, maybe with a link to it in the plain hello world tutorial. I'm thinking of a note there to catch advanced JS and NPM users right at the beginning so they do not spend time on a manual setup just to switch later.
Then again, I'd recommend it to anyone, especially beginners, but I'm clearly biased :see_no_evil: :smile: 
Thanks @becky-gilbert! I can write a draft (once we have decided where to put it) and I'd be happy about your review then!

> Any interest in helping out with that phase of things?

I'd love to! In this regard, there are also a lot of other benefits (especially ES6 classes!) that come with modern JS that jsPsych could take great advantage of – and I'd surely like to help out introducing some of them!

> Personally I think it'd be great to continue to offer jsPsych in its current form (as a simple set of scripts, alongside a module version), and I'm wondering if that might be possible with webpack?

That is a perfectly feasible and common approach. [Rollup](https://rollupjs.org/guide/en/) would be the tool of choice here (with the iife format). Again, I'm keen to set this up for jsPsych – it opens the door to the lovely world of modern JS, a world of endless joy and harmony :smile: Kidding aside, I'm pretty sure we could even do the transition without a major release (whether that's desirable is one whole other question).

Do you have a preferred communication channel I should join? I'm also happy to attend some meetings and discuss a roadmap face-to-face :slightly_smiling_face:

**Comment by becky-gilbert** [comment]
Hi @bjoluc, great! Can you draft the addition of jspsych-builder to the running-experiments docs page? I think putting it in its own section for now sounds good. I like the idea of linking to your hello world demo on the basic hello world tutorial page. 

As far as helping out with the migration to ES6 modules support - I think you should get in touch with Josh, as he's handling the plan for that (we tend to just email and have the occasional zoom meeting). Another thing you could do is look at the open issues that relate to modules to read about Josh's ideas on this and comment there: #625, #529

Thanks very much for pointing me to rollup! I've already seen from the quick start section on the first page that this looks like just what we need 😃
