### ISSUE TITLE
Audio-button-response distorted audio

### ISSUE THREAD

**Issue by crystalylee** [jspsych/jsPsych#1869]
I created an experiment on jspsych where you see a video on the first trial, and then it asks you to make a choice. However, the audio on the final trial is very distorted and I'm not sure why. The distortion also only comes up on iPads, and not smart phones or computers. I've tried various ways to fix this: reducing the file size, using different files (wav, mp3, m4a), varying the file size of the preceding video file, and none have fixed the audio distortion. 

Any help would be greatly appreciated!

active link: run.pavlovia.org/sp-compressed/sp
code: https://gitlab.pavlovia.org/sp-compressed/sp

**Comment by jodeleeuw** [comment]
Hi @crystalylee 

Weird! I doubt that this issue is due to something in jspsych, though I'm open to the possibility. Have you verified that the audio file is undistorted if you load it directly? Try navigating to the URL of the sound file and playing it through the browser.

**Comment by jodeleeuw** [comment]
I'm going to close this, but happy to reopen if there is further input.
