### ISSUE TITLE
Incorrect default value documentation for jspsych-same-different plugin

### ISSUE THREAD

**Issue by nikbpetrov** [jspsych/jsPsych#1879]
The default value in the [documentation of the jspsych-same-different-html](https://www.jspsych.org/plugins/jspsych-same-different-html/) for the `first_stim_duration` and `second_stim_duration` says 1000, while [within the plugin file](https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-same-different-html.js) it is set to `null`, meaning the stimuli display until a key press (while this is not indicated to the user by default).

I imagine the default values in the plugin file need to be updated to 1000 instead of `null`.

Edit: ditto for the `jspsych-same-different-image` [documentation](https://www.jspsych.org/plugins/jspsych-same-different-image/) and [plugin file](https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-same-different-image.js).

**Comment by becky-gilbert** [comment]
Thanks very much for flagging this error @nikbpetrov! We'll fix it ASAP.

**Comment by becky-gilbert** [comment]
Ah, just saw your pull request that fixes this. Thanks!

**Comment by becky-gilbert** [comment]
Closed via PR #1880 (1436132)

**Comment by becky-gilbert** [comment]
@nikbpetrov FYI, I just added your name to the [contributors.md file](https://github.com/jspsych/jsPsych/blob/master/contributors.md). Please submit a pull request with changes to this file if you want to be listed differently or if I made any errors. 

Thanks again! 😃

**Comment by nikbpetrov** [comment]
> @nikbpetrov FYI, I just added your name to the [contributors.md file](https://github.com/jspsych/jsPsych/blob/master/contributors.md). Please submit a pull request with changes to this file if you want to be listed differently or if I made any errors.
> 
> Thanks again! 😃

Thanks @becky-gilbert ! All looks good. Glad I could help. I hope I can contribute more substantially soon (working on #647 )
