### ISSUE TITLE
"Storing data permanently as a file" example does no sanitisation of incoming data.

### ISSUE THREAD

**Issue by mike-somethingnooneelsehasusedyet** [jspsych/jsPsych#1908]
The "Storing data permanently as a file" example on https://www.jspsych.org/overview/data/ suggests this code:
```
<?php
$post_data = json_decode(file_get_contents('php://input'), true);
// the directory "data" must be writable by the server
$name = "data/".$post_data['filename'].".csv";
$data = $post_data['filedata'];
// write the file to disk
file_put_contents($name, $data);
?>
```
That code potentially allows a malicious actor to host their own content on your web server. 

There is no sanitisation of the `$post_data['filename']` value. If the PHP script is running as user `bob` a malicious actor can create a file anywhere the user `bob` has write access to, regardless of the directory specified in the code, by supplying a value such as `../../foo/bar` to do directory traversal. For example this could potentially allow creation of new files in the web server document root, even if has been specified that files be saved outside of it.

There is no sanitisation of `$post_data['filedata']` or check to ensure it's anything like what is expected, e.g. that it is a CSV string, so a malicious actor can put arbitrary content in a file.

```
$ curl -X POST https://yourserver/write_data.php -d "{ \"filename\" : \"../../var/www/html/blah\", \"filedata\": \"$(base64 -w 0 photo.jpg)\" }"
$ curl https://yourserver/blah.csv | base64 -d > /tmp/photo.jpg
```

The example code should by updated to include sanitisation/checks of `$post_data['filename']` and `$post_data['filedata']` values.

**Comment by pjotrsavitski** [comment]
@mike-somethingnooneelsehasusedyet The example from the documentation is probably not the best one and should not be used in production, though it does seem quite strange to start parsing the contents of the file. It might be better to just improve the documentation and clearly mention that this is an example starter solution that just gives the general idea about the possible approach. It might be more useful to mention that **data** directory should be located outside of the so-called **www root** of the web server. Sanitising file name is a decent suggestion, but it seems to be a bit out of scope for the documentation and a better approach should be to just create a temporary name for the uploaded content. A simple example would be `$filename = strftime('%F') . '-' . bin2hex(random_bytes(32));`. It could clearly be anything that is random enough and would probably work just fine. Having unique file name would both prevent possible manipulation and rewriting of an existing data.

File content and fine name (extension really) are a totally different things and having files stored outside of **www root** where server can't serve them would be quite beneficial. Another approach would be to force the web server to serve all of the files within the data directory as text files, which would prevent the file contents attach vector. [Here](https://serverfault.com/questions/82505/how-can-i-set-apache-to-serve-files-as-text) is an example for Apache web server. Still, not allowing the directory contents to be served is a safer and better solution, as one would mostly prefer not to expose the data to the world.

**Comment by mike-somethingnooneelsehasusedyet** [comment]
I assure you people have used this example code in production. Devising behavioural experiments and creating secure, very possibly Internet exposed, web applications which accept and store user input are entirely different skill sets. Some people will not have any coding experience, awareness of security issues around accepting user input and storing it, or local support to help them and will cobble something together by copy/pasting code. People will assume that an example provided in documentation is OK to use if there is no indication that it shouldn't be, as is the case with the code I highlighted. (Inevitably some will use it in production even if the documentation says not to!)
