### ISSUE TITLE
Support for require

### ISSUE THREAD

**Issue by crfroehlich** [jspsych/jsPsych#194]
I'm using JsPsych in a project that is entirely modular. jQuery doesn't exist on the global object, so I can't simply include the JsPsych files via script nodes--I need to bundle it with my app as it's compiled (in my case via browserify). It's a simple enough fix for me to make the necessary changes, [see this gist](https://gist.github.com/somecallmechief/84fc3982b3c0f974d87d), but it means I'll have to continue to manually tweak the files every time there's a new release.

It would be great if JsPsych supported CommonJs style `require` out of the box.

**Comment by RobAWilkinson** [comment]
In case anyone stumbles upon this, we have figured a way around this issue by using webpacks `script-loader` for the time being

**Comment by jodeleeuw** [comment]
Tracking this in #529 now.
