### ISSUE TITLE
Data can't be saved in a MySQL database at least with iPhone and iPad.

### ISSUE THREAD

**Issue by kurokida** [jspsych/jsPsych#1999]
I have been using [this method](https://www.jspsych.org/overview/data/#storing-data-permanently-in-a-mysql-database) to store data in a MySQL database.

I noticed that the data with Windows PC can be saved, but the data with iPhone and iPad data is not saved.

This issue may be related to https://github.com/jspsych/jsPsych/discussions/1830

I modified the recommended code slightly to create the following code.

```javascript
    function saveData() {
        alert('save_data')
        var xhr = new XMLHttpRequest();
        xhr.open('POST', 'write_data.php'); // change 'write_data.php' to point to php script.
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onload = function() {
            alert('xhr_onload')
            if(xhr.status == 200){
                var response = JSON.parse(xhr.responseText);
                console.log(response.success);
            
                savedata_result = response.success
                jsPsych.data.addProperties({res: savedata_result})
            
            }
        };
        xhr.onerror = function(){
            alert('Err')
            alert(`Error ${xhr.status}: ${xhr.statusText}`); 
        }
        xhr.send(jsPsych.data.get().json());
    }

```

# Results
- The message "save_data" appeared in all devices, that is, Windows PC, iPhone, and iPad.
- On Windows PC, the message "xhr_onload" appeared and the data can be saved successfully.
- On iPhone and iPad (both Safari and Chrome), the message "xhr_onload" didn't appear, the message "Err" and "Error 0:" appeared instead. The xhr.statusText was empty.

Does anyone have any ideas?

**Comment by kurokida** [comment]
Hi @javidalpe, I'm sorry to bother you.

As I mentioned above, I'm having trouble with data saving with iPhone and iPad.
This problem is occurring on my server, but I found that there was no problem in the case using Cognition.run you developed.

Do you have any idea?
Or could you show me the source code regarding the data saving to the server?

**Comment by kurokida** [comment]
I have found a solution, but I am not sure if this is the right one.

If I write as follows, the problem was solved.

```javascript

xhr.open('POST', 'write_data.php', false);
```

That is, I changed the operation from async to sync. 
See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open

@jodeleeuw , @becky-gilbert , if my method is correct, I think we need to rewrite [this page](https://www.jspsych.org/overview/data/#storing-data-permanently-in-a-mysql-database).

**Comment by becky-gilbert** [comment]
Thanks for flagging this @kurokida, and glad to hear that you found a solution. I've assigned this to Josh and he's out of the office right now, but I'm sure he'll get to it when he gets back.

Note: see also #1908 for other changes we might want to make to this data saving section in the docs.

**Comment by jodeleeuw** [comment]
I think the ideal solution here involves waiting for the `xhr` request to process before continuing. 

This could be done by using the `async` option in the `call-function` plugin and activating it in the `xhr.onload` and `xhr.onerror` functions.

Another option would be to switch to using the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) which is a more streamlined way of making these requests. The same idea would apply there: we'd want to wait for the request to complete before the experiment continues.
