### ISSUE TITLE
Deploy versioned documentation

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2047]
Given the major changes to the documentation that will happen with v7.0, we should figure out how to deploy versioned documentation for previous releases. It looks like [this is supported by the documentation theme provider](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/), so we should be able to retroactively deploy docs for every version that was built to use the mkdocs material theme.

Assigning me and @becky-gilbert so one of us can get to it eventually 😁

**Comment by jodeleeuw** [comment]
I've started to work on this. I've figured out how to deploy docs for 6.3 and how it will work for 7.0. I could deploy the change to the live site, but I think it will be weird to have a dropdown selector for the version that doesn't do anything. So I propose that I deploy the versioned docs for 6.3 at the same time that we do 7.0 docs.

**Comment by becky-gilbert** [comment]
@jodeleeuw thanks for letting me know, and sorry I hadn't gotten to this yet! 

RE waiting for v7 before adding a version selector - sounds good. How difficult would it be to add docs for all v6 releases? Maybe I can add those around the same time as 6.3.1?

BTW is it ok if I update the live site with the recent docs edits that apply to the current release? These have all been merged into `master`. I assume that all of the v7 docs changes will go on a branch We also have the separate `docs-demos` branch - I can either merge that into `master` before updating the live site, or wait until all of the plugin demos have been created.

**Comment by jodeleeuw** [comment]
@becky-gilbert I think we should aim to have a final version of the 6.3 docs done with the release of 7.0. If we have the live demos functional for 6.3 docs then we could merge those changes in and publish an updated version of the 6.3 docs prior to publishing the 7.0 docs. But once we publish the 7.0 docs I want to avoid having to make changes to the 6.3 docs.

In theory adding docs for <6.3 is very doable, but the problem is that I think some of those docs were built with earlier versions of `mkdocs` and `material-mkdocs`. So if the latest version of those can't build those docs then we'd have to do things like install specific old versions, generate the docs, and then publish them. I think this might be more of a headache than it is worth. We could add a note to the docs, maybe even on the main page, about versions and why there is no option for earlier versions of the docs.

**Comment by jodeleeuw** [comment]
This was completed with #2154
