### ISSUE TITLE
Experiment doesn't work on psiTurk/mTurk (but works fine as .html)

### ISSUE THREAD

**Issue by fspinar** [jspsych/jsPsych#2073]
Hi all,

I am trying to run my experiment by using jsPsych. The code works fine when I run it as an HTML code separate from psiTurk, but when I try to run it on mTurk sandbox or in the debug mode of psiTurk, I only get a blank screen.

Could you help me through this ? I really don't see what is wrong.

Thanks a lot.

**Comment by becky-gilbert** [comment]
Hi @fspinar, it'll be hard to figure out what the problem is here without more information. Do you get any errors in the browser's JavaScript console when you see the blank screen? Also, have you tried reaching out to psiTurk support?

**Comment by deargle** [comment]
:wave: from psiturk support. https://github.com/NYUCCL/psiTurk/issues/525

**Comment by jodeleeuw** [comment]
I'm going to shift this to [discussions](https://github.com/jspsych/jsPsych/discussions) since it is a support request.
