### ISSUE TITLE
Modularization: `trial_type` property in `DataCollection` is stored as an object, creating circular dependencies

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2076]
`jsPsych.data.get().json()` causes an error because `trial_type` is an Object with circular references.

Suggested fix is to store the static `info.name` as the `trial_type`.

**Comment by bjoluc** [comment]
Thanks @jodeleeuw! That's the one part I discovered I was missing when I went through the proposed changes in #661. Fixed by 
017b45d.
