### ISSUE TITLE
Change global parameter inside a function

### ISSUE THREAD

**Issue by fspinar** [jspsych/jsPsych#2085]
Hi all,

I have a function that determines the stimulus of a trial. That is:

var trial = {
...
stimulus: function(){

}
}

Inside this function I need to be able to update a global parameter and use that parameter in other trials. That is :
var parameter = 0;
var trial = {
...
stimulus: function(){
parameter = parameter + 1;
}
}

var newTrial = {
// access to this parameter
}

Could you help me with this ? Should I add this parameter to the data structure of the experiment ? (data.parameter = ...) 
I suppose this is the easiest way ? 

Thank you and best regards

**Comment by becky-gilbert** [comment]
Hi @fspinar, I'm moving this to the Discussions section because it's a question, rather than a bug or feature request.
