### ISSUE TITLE
repetitions_per_point in webgazer-validate plugin?

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#2131]
@jodeleeuw the [webgazer-validate plugin docs page](https://www.jspsych.org/plugins/jspsych-webgazer-validate/) lists a `repetitions_per_point` parameter, which is "The number of times to repeat the sequence of calibration points". There's no such parameter in the actual plugin. Should I implement the repetitions parameter in the plugin and change "calibration" -> "validation" in the docs parameter description? Or remove this parameter from the docs?

**Comment by jodeleeuw** [comment]
Oops. Totally sloppy on my part!

Let's remove the parameter from the docs. And let's do that on `main` so that it deploys as part of the v6.3 docs. Thanks!
