### ISSUE TITLE
change plugin parameters: option of different types to a single type

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#2132]
With the switch to TypeScript in v7.0, plugin parameters that allow different types are trickier to deal with (see discussion [here](https://github.com/jspsych/jsPsych/pull/2078#discussion_r692059043)). One solution is to enforce a single type* for these parameters. This will be a breaking change for the affected plugins, and will require changes to the documentation, as well as any demo code and example files that use the parameter type that is no longer allowed. 

Affected plugins and parameters:
* RDK `correct_choice`: currently can be a string or array. Change to array.
* visual-search-circle `foil`: currently can be a string or array. Change to array.

I scanned the plugin docs and didn't catch any others.

\* Another solution is to create a new 'any' type for these parameters, but the downside is that we will lose the benefit of type-safety in these cases.

**Comment by becky-gilbert** [comment]
@vrsivananda quick question for you about the RDK plugin: while looking into the `correct_choice` parameter, I noticed that when this parameter is an array, the response is only considered correct if the participant responds with _all_ of the keys listed in the array:
```js
var key_in_choices = trial.correct_choice.every(function(x) {
  return jsPsych.pluginAPI.compareKeys(x,response.key); 
});
return key_in_choices; //If the response is included in the correct_choice array, return true. Else, return false.
```
But your comment above says that if the response is included in the array then the `correctOrNot` function should return `true`. So I'm wondering if this is an error, and `trial.correct_choice.every` should use the [`some` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) instead of `every`. This change would mean that if someone responds with "a" when `correct_choice` is `["a","l"]`, their response would be considered correct (whereas right now the participant needs to press both "a" and "l" to get a correct response). 

Thanks!

**Comment by jodeleeuw** [comment]
For the `visual-search-circle` plugin I think changing `foil` to be just an array would create an annoying problem where if you want all of the foils to be the same, you would need to repeat that item `n` times in the array. Currently the plugin will do this for you if the `foil` parameter is not an array.

We could implement something so that the array is duplicated the number of times necessary to reach `set_size` I guess?

**Comment by becky-gilbert** [comment]
@jodeleeuw 
> We could implement something so that the array is duplicated the number of times necessary to reach set_size I guess?

Yes this was my plan. As part of this switch to only allowing the `foil` parameter to be an array, I would remove the string check from the trial method, and instead check whether the `foil` array contained only one element and the `set_size` is greater than 1. Other than that, the implementation would be the same as it is currently (i.e. repeat the single element in the `foil` array up to `set_size`, otherwise use the `foil` array as it is).
