### ISSUE TITLE
The EyeTracking plugin can not get the position of video's target. 

### ISSUE THREAD

**Issue by ljhtx** [jspsych/jsPsych#2152]
I just get an initial position of video's target. Is there any other way to solve this problem？
![image](https://user-images.githubusercontent.com/47860962/133388326-7f1a70a8-6e2d-41df-8a97-9791fc4ee7af.png)
![image](https://user-images.githubusercontent.com/47860962/133388510-ecfeb5e5-3bbc-4f81-8a30-8ba2734ee208.png)

**Comment by myrtevos** [comment]
Hey, not sure if I've understood your problem based on the information given, but it's possible that the eye tracking extension tries to 'fetch' the location of the stimulus before that stimulus has been fully rendered on the screen. I ended up just adapting the trial plugin itself to record the bounding rectangle of the stimulus.

**Comment by ljhtx** [comment]
Thank you for your response！As you have said，although the plugin can not get the position, I tried to get the position before the end of the video stimuli. It worked.
