### ISSUE TITLE
combining 2 plugins...!

### ISSUE THREAD

**Issue by mary-9555** [jspsych/jsPsych#2155]
Hi guys.
I'm working on a task using multimedia such as images and audios.
After every trial there should be a Likert scale, for example in first page there's an image with "image_button_response" plugin used,
the following page there is a likert scale with "survey_likert" plugin, asking questions about the image.
So my question is, Should I define every single image variable then likert then image again then likert again and so on? or theres an easier way to code? Can I write a timeline_variables for my 72 trials! using two plugins?

I' m also wondering how can i present a trial including both image and audio at the same time in the same page ?

**Comment by jodeleeuw** [comment]
I'm moving this over to [discussions](https://github.com/jspsych/jsPsych/discussions).
