### ISSUE TITLE
Support for Safari fullscreen?

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#217]
[This experiment](http://php-coglab.rhcloud.com/experiments/wordlist-matrix.html) works in fullscreen mode with Safari, so it's possible.

**Comment by jodeleeuw** [comment]
@adrianoesch I think this was your experiment but its not online anymore. I still can't figure out how you got it working. Any pointers?

**Comment by adrianoesch** [comment]
so what i've found out in the meantime is that dom events events are triggered, but the input forms like textareas are disabled in safari's fullscreen. here's another working example: [link](https://lab-timgroup.rhcloud.com/anna.html?c=0123456&a=0101011&m=1&s=1&f=dev&r=dev&i=dev&ch=dev). so what i usually do now, is that i run the "experiment" in fullscreen and leave fullscreen for a post-survey where i need input forms like in [this experiment](https://online-coglab.rhcloud.com/experiment.html?is_dev=true&allowSkip=true) (skip trial with "Ctrl-C").

**Comment by jodeleeuw** [comment]
In your fullscreen plugin you have this:

```javascript
if(elem.webkitRequestFullscreen) {
  elem.webkitRequestFullscreen(elem.ALLOW_KEYBOARD_INPUT);
  elem.webkitRequestFullscreen(elem.ALLOW_KEYBOARD_INPUT);
  if (!(navigator.userAgent.indexOf("Safari") > -1 && navigator.userAgent.indexOf("Chrome") > -1)){
    document.onkeydown = function(e){e.preventDefault()}
  }
}
```

What's the check and subsequent disabling of the default behavior for?

**Comment by adrianoesch** [comment]
it prevents safari from playing a sound on every key press.
