### ISSUE TITLE
Create canvas drawing plugin

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2196]
Add a plugin for simple canvas-based doodles, per our promise for MOSS award.

@kushinm do you have something that would be a reasonable starting point? Or alternatively, as someone who might conceivably use such a plugin, what would you need in it?

**Comment by becky-gilbert** [comment]
FYI I have a version of this but I made it with jsPsych v5 (!), so it would need quite a bit of adaptation. If anyone else has done this and wants to share their code, that would be great because it would allow us to pick out or combine the best features and implementation.

**Comment by kushinm** [comment]
The plugin I used was also for a much older version of jsPsych! I do plan on building a newer one later down this semester/early next year. If it can wait till then I'm happy to contribute or if @becky-gilbert feels like it's easier for her to integrate her existing plugin that's fine too! I should note that the plugin I'd created extensively used paperJS and some JQuery that's native to JavaScript now. Are you trying to keep the number of dependencies in plugins to a minimum?

**Comment by jodeleeuw** [comment]
I think our deadline is roughly 4 weeks for this one.
