### ISSUE TITLE
*-keyboard-response plugins do not recognize NO_KEYS

### ISSUE THREAD

**Issue by chrisbrickhouse** [jspsych/jsPsych#2222]
The [documentation for audio-keyboard-response](https://www.jspsych.org/7.0/plugins/audio-keyboard-response/) (@1.0.0) says that specifying `choices: jsPsych.NO_KEYS` will prevent the trial from accepting any keyboard input. This is not the behavior, and the experiment will in fact accept *any* key as a response.

The second code example provides a minimal working example for this incorrect behavior:
```
var trial = {
    type: jsPsychAudioKeyboardResponse,
    stimulus: 'sound/tone.mp3',
    choices: jsPsych.NO_KEYS,
    trial_ends_after_audio: true
};
```
**Expected behavior**:
* accepts no keys as input
* ends when the audio file is finished *only*

**What occurs**:
* Pressing any key ends the trial
* If no key is pressed, the trial ends when the audio file is finished

**Workaround**:
* The user can add `response_ends_trial: false` to the example code. The experiment will still recognize the input, but it will not end the trial. Instead, the trial will continue until the audio finishes and then end as expected.

**Comment by chrisbrickhouse** [comment]
I ran into this while coding a new experiment, so I can confirm this extends beyond the code examples in documentation. I tested the other `*-keyboard-response` code examples and they show the same bug. It seems that `NO_KEYS` is not being respected or has some kind of bug.

**Comment by jodeleeuw** [comment]
We had to change this to a string because of some of the other things that changed in 7.0. It looks like we missed the update to the docs. Thanks for flagging this. I believe the new version is simply:

```js
choices: "NO_KEYS"
```

**Comment by jodeleeuw** [comment]
This might be worth a mention in the migration guide as well. I forgot about this change when I wrote it.
