### ISSUE TITLE
Register package with Bower

### ISSUE THREAD

**Issue by kevinmickey** [jspsych/jsPsych#229]
In the same spirit as #194 and #195 (although hopefully easier), register jspsych with Bower.  Instructions here:

http://bower.io/docs/creating-packages/#register

**Comment by 1kastner** [comment]
That looks like a nice idea!

**Comment by bjoluc** [comment]
> As Bower is deprecated, registering new Bower packages is not supported anymore.

I think this should be dropped in favor of NPM now @jodeleeuw.
