### ISSUE TITLE
Typo and broken link in docs

### ISSUE THREAD

**Issue by cabejackson** [jspsych/jsPsych#2318]
There's currently a typo in the docs on this page: https://www.jspsych.org/7.0/overview/timeline/
See screenshot:
<img width="714" alt="Screen Shot 2021-11-09 at 10 20 29 AM" src="https://user-images.githubusercontent.com/66799077/140952018-3984412a-529c-437f-a9e4-a520dc2b85cf.png">

Also, the link to the dynamic parameters page is sending me to a 404 page. 
<img width="936" alt="Screen Shot 2021-11-09 at 10 25 07 AM" src="https://user-images.githubusercontent.com/66799077/140952813-d54027b1-d15b-4bed-b98e-489d003aae76.png">

Link should be updated to: https://www.jspsych.org/7.0/overview/dynamic-parameters/

**Comment by hawkrobe** [comment]
the Media Preloading link also broke in 7.0: should be updated to `https://www.jspsych.org/7.0/overview/media-preloading/` !

<img width="718" alt="CleanShot 2021-11-13 at 22 58 43@2x" src="https://user-images.githubusercontent.com/5262024/141670899-ce77df82-d742-491c-baa3-93650e763354.png">
