### ISSUE TITLE
Add direct link to latest `dist` in docs

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2324]
I think one consequence of the new release structure is that it is a bit harder to know how to get the most up-to-date dist if people are using "option 2" in the tutorials. For example, downloading the dist for the 7.0.0 release will not have the updated file for v1.0.1 of the fullscreen plugin. But it's not obvious at all that the 1.0.1 release of the fullscreen plugin contains the full dist archive.

I think we should add a more direct link to the latest dist archive. I'm hoping there's some way to figure out which release that is automatically through GH's API.

**Comment by becky-gilbert** [comment]
Totally agree! Maybe a really clear "download the latest distribution" link on the docs landing page and GH readme, plus a link in the Hello World option 2 section? No idea how to automate this so that the link is correct with every update, but we could add the links manually for now.
