### ISSUE TITLE
Make the release workflow update all unpkg links in docs

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2348]
Before 7.1 docs are published need to update unpkg links.

Also would be nice to figure out an automated system for this in the future 😅 !

**Comment by bjoluc** [comment]
I'd like to modify the release workflow such that the unpkg links are automatically updated in the release PR (commit messages in docs files' commit histories may become very confusing otherwise); yet need to do some research on how to achieve that.
