### ISSUE TITLE
Backward masking in jsPsych?

### ISSUE THREAD

**Issue by spiropan** [jspsych/jsPsych#238]
Hello,
I would like to be able to backward mask an image in jsPsych (i.e. display a positive valence image for 33 ms immediately followed by a neutral mask for 167 ms). The easiest plugin to do this appears to be jspsych-animation.js. However, the frame_time parameter only accepts a single scalar value so the image and the mask would have to have the same frame rate. Would you say the best remedy would be to allow frame_time to be an array so that different timings can be applied to each image in the sequence? Or is there another way to do this that could be more straightforward? 
many thanks in advance,
Spiro

**Comment by jodeleeuw** [comment]
The easiest way to set this up is to just have two consecutive trials from the single-stim plugin. The first trial would having a timing_response parameter of 33 and timing_post_trial of 0.

However, 33ms is in the territory where standard JavaScript techniques will become unreliable. Monitor refresh rates need to be considered at such small intervals. JavaScript can sort of do this, with `requestAnimationFrame`, but this isn't supported in jsPsych yet.

**Comment by spiropan** [comment]
Thanks Josh, JSpsych looks like a very useful toolbox, thank you for
developing it! Any idea when that feature would be supported in JSPSych?
Thanks, Spiro

**Comment by jodeleeuw** [comment]
It's on the list of issues: #75 

But it's a complicated change and is not the highest priority at the moment, so I don't have an estimated date.
