### ISSUE TITLE
Can not run any examples

### ISSUE THREAD

**Issue by Hannah2201** [jspsych/jsPsych#2447]
Cloned repository and tried to run example experiments in Chrome. All example experiments throw errors: 

"Uncaught ReferenceError: initJsPsych is not defined
    at conditional-and-loop-functions.html:11:19"

"Failed to load resource: net::ERR_FILE_NOT_FOUND"

Would be thankful for help!

**Comment by bjoluc** [comment]
The example files in the repository depend on the [development setup](https://www.jspsych.org/7.1/developers/configuration/). If you'd simply like to have executable script files instead (including the examples), you can [download the latest release archive](https://www.jspsych.org/7.1/tutorials/hello-world/#option-2-download-and-host-jspsych). Cheers!
