### ISSUE TITLE
Unexpected simulation behaviour of instructions plugin

### ISSUE THREAD

**Issue by nikbpetrov** [jspsych/jsPsych#2462]
In the [instructions plugin](https://github.com/jspsych/jsPsych/blob/main/packages/plugin-instructions/src/index.ts) I expect that when I specify RT of 200 that the time spent on each page would be 200ms. Instead, currently the plugin spends 3000ms (on average) on each page.

The obvious issue is that the view time is currently hardcoded at M=3000 and SD=300 on line 264 of the code. This needs adjusting.

However, there is another big issue to consider: RT for this trial is supposed to be the sum of the view time of each page. Hence, the problem is when the user specifies RT of 200, does that mean view time per page or does that mean overall RT for the whole trial (i.e. sum of all view times) - there is definitely wiggle room here!

Considering that most users will not care about analysing the RT of an instructions trial, I would argue that it is worth setting the default option as RT meaning view time but allowing users to change that (by letting them know that they can 'tag' instruction trials and change the simulation options as they see fit).

P.S. Just realized there is a similar hardcoded line for the [fullscreen plugin](https://github.com/jspsych/jsPsych/blob/main/packages/plugin-fullscreen/src/index.ts) (line 167) - button click is set to M=1000, even if I have provided a different RT in the simulation options.

**Comment by jodeleeuw** [comment]
Hey @nikbpetrov,

I decided to fix this in the following way:

1. If `rt` is set but not `viewing_history`, then the `rt` is the total length of time spent across all pages and the plugin will generate simulated view times for each page that are consistent with the overall `rt`.
2. If `viewing_history` is set but not `rt`, then the `rt` will be set to the sum of all the `viewing_history` times.
3. If both are set, then we assume they are consistent and don't enforce a check.
