### ISSUE TITLE
survey-html-form not running

### ISSUE THREAD

**Issue by Alexpathy** [jspsych/jsPsych#2486]
Hi!
I am new to jsPysch and have a problem with one of the plugins. I can't get the plugin survey-html-form to run correctly. When I try to debug I get this error message: "hej.html:32 Uncaught ReferenceError: jsPsychSurveyHtmlForm is not defined". Supposedly I haven't defined the plugin correctly, but I can't seem to figure out the problem, as most of my code is just copy paste. Line 32 is my type parameter for the survey-html-form. 
Would really appreciate some help. Thanks! 

```
<!DOCTYPE html>
<html>
  <head>
    <title>My experiment</title>
    <script src="https://unpkg.com/jspsych@7.1.2"></script>
    <script src="https://unpkg.com/@jspsych/plugin-html-keyboard-response@1.1.0"></script>
    <script src="https://unpkg.com/@jspsych/plugin-survey-html-form@1.1.0"></script>   
    <link href="https://unpkg.com/jspsych@7.1.2/css/jspsych.css" rel="stylesheet" type="text/css" />
  </head>
  <body></body>
  <script>

    /* initialize jsPsych */
    var jsPsych = initJsPsych({
  on_finish: function() {
    jsPsych.data.displayData();
  }
});

/* create timeline */
var timeline = [];

/* define welcome message trial */
var welcome = {
  type: jsPsychHtmlKeyboardResponse,
  stimulus: "Welcome to the experiment. Press any key to begin."
};

timeline.push(welcome);

var trial = {
    type: jsPsychSurveyHtmlForm,
  html: '<div><img src="img/stimuli_img/DESCRIBE.jpg"></div><p><input name="first" type="text" /></p>'
};

    timeline.push(trial);

    /* start the experiment */
    jsPsych.run(timeline);

  </script>
</html>
```

**Comment by becky-gilbert** [comment]
Hi @Alexpathy, the error suggests that the plugin file hasn't loaded, and when I click on your link for the `survey-html-form` plugin I get an error message about the file not being found.
It turns out that the latest version of the `survey-html-form` plugin is 1.0.0, which I found by searching on NPM: https://www.npmjs.com/package/@jspsych/plugin-survey-html-form

So you can try changing your unpkg link to:
```html
<script src="https://unpkg.com/@jspsych/plugin-survey-html-form@1.1.0"></script>
```
Does that fix the problem?

**Comment by Alexpathy** [comment]
Yes, that works great. Thank you! I'll be more wary about plugin versions in the future.
