### ISSUE TITLE
Demo Experiment: simple reaction time task

### ISSUE THREAD

**Issue by hamster789** [jspsych/jsPsych#2526]
Hi, I am very new to javascript and coding. I am currently trying out the demo experiment on JsPsych- simple reaction time task. When I try to run the experiment with Visual Studio Code and open it with a live sever, it shows that "The experiment failed to load." I am not sure why the experiment is not working as I directly copied the coding in the webpage on JsPsych. :(

**Comment by becky-gilbert** [comment]
Hi @hamster789, this question seems better suited for the Discussion board so I'm closing this issue and will respond on your other post. We can re-open this issue if we find that there's a problem with our demo.
