### ISSUE TITLE
virtual-chinrest issues on npm

### ISSUE THREAD

**Issue by cjungerius** [jspsych/jsPsych#2575]
Hi jsPsych team! 
      
I noticed when trying to implement the virtual-chinrest plugin in my experiment (using jspsych builder and npm) that the plugin fails because the svg.js library isn't imported by the plugin, and unlike when one writes an experiment with the html/js method, this cannot be fixed with an import of svg.js into the experiment file (at least as far as I can tell - I must admit I'm a bit of a novice here). In addition, the latest version of svg.js on npm (and perhaps elsewhere) has slightly different behaviour from what the plugin expects, leading to a bug when stopping the ball animation function even once the library is correctly imported.

I used [patch-package](https://github.com/ds300/patch-package) to patch `@jspsych/plugin-virtual-chinrest@1.0.0` for the project I'm working on. I don't know how relevant this is to general use of the plugin (and perhaps having the svgdotjs import here is a big no-no), but I figured I'd share it in the hope it's useful somehow.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@jspsych/plugin-virtual-chinrest/src/index.ts b/node_modules/@jspsych/plugin-virtual-chinrest/src/index.ts
index 673e5ca..4769c2a 100644
--- a/node_modules/@jspsych/plugin-virtual-chinrest/src/index.ts
+++ b/node_modules/@jspsych/plugin-virtual-chinrest/src/index.ts
@@ -1,4 +1,5 @@
 import { JsPsych, JsPsychPlugin, ParameterType, TrialType } from "jspsych";
+import { SVG } from '@svgdotjs/svg.js'
 
 const info = <const>{
   name: "virtual-chinrest",
@@ -147,7 +148,9 @@ declare global {
 class VirtualChinrestPlugin implements JsPsychPlugin<Info> {
   static info = info;
 
-  constructor(private jsPsych: JsPsych) {}
+  constructor(private jsPsych: JsPsych){
+    this.jsPsych = jsPsych;
+  }
 
   trial(display_element: HTMLElement, trial: TrialType<Info>) {
     /** check parameter compatibility */
@@ -315,7 +318,7 @@ class VirtualChinrestPlugin implements JsPsychPlugin<Info> {
     };
 
     const finishBlindSpotPhase = () => {
-      window.ball.stop();
+      window.ball.timeline().stop();
 
       this.jsPsych.pluginAPI.cancelAllKeyboardResponses();
 
@@ -406,8 +409,7 @@ class VirtualChinrestPlugin implements JsPsychPlugin<Info> {
 
     function drawBall(pos = 180) {
       // pos: define where the fixation square should be.
-      // @ts-expect-error
-      var mySVG = SVG("svgDiv");
+      var mySVG = SVG().size(1000,200).addTo('#svgDiv')
       const rectX = trial_data["px2mm"] * pos;
       const ballX = rectX * 0.6; // define where the ball is
       var ball = mySVG.circle(30).move(ballX, 50).fill("#f00");
@@ -458,7 +460,7 @@ class VirtualChinrestPlugin implements JsPsychPlugin<Info> {
         finishBlindSpotPhase();
         return;
       } else {
-        window.ball.stop();
+        window.ball.timeline().stop();
         animateBall();
       }
     }
```
<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jodeleeuw** [comment]
Thanks @cjungerius for bringing this up. I've been meaning to refactor that plugin for a while and remove the dependency. This got me to do it. See #2577 for a proposed change to the plugin. Would love your feedback on it if you have a chance.
