### ISSUE TITLE
Fix GitHub Pages Link to edit Docs

### ISSUE THREAD

**Issue by kalaschnik** [jspsych/jsPsych#2588]
When I try to click the pen within the docs, for example:
https://www.jspsych.org/7.2/overview/timeline/

The site directs to: https://github.com/jspsych/jsPsych/edit/master/docs/overview/timeline.md

having still `master` in the URL. I think this is something you can fix easily by selecting `main` in your repo settings:

https://github.com/jspsych/jsPsych/settings/pages

**Comment by jodeleeuw** [comment]
Thanks @kalaschnik for pointing this out. The fix required updating a config file in our docs builder. It should be fixed now.
