### ISSUE TITLE
Add plugin support for number-only responses

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2597]
Could accomplish this by:

1. Adding a parameter to `survey-text` that changed the `<input>` to type `number` on a per question basis.
2. Creating a new plugin based on `survey-text` that is `<input type="number">` for all questions.
3. Relying on `survey` plugin. Does this support something like this already?

**Comment by becky-gilbert** [comment]
> 3. Relying on survey plugin. Does this support something like this already?

Yes it does - see the [SurveyJS text question demo page here](https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Reactjs&theme=defaultV2). Each question has an optional "inputType" parameter which is "text" by default but can be set to any of these:

> color
> date
> datetime
> datetime-local
> email
> month
> number
> password
> range
> tel
> text
> time
> url
> week

**Comment by jsato8094** [comment]
I also wanted to be able to set the "inputType" parameter, so I created a PR to make that possible. Can you please review it?
https://github.com/jspsych/jsPsych/pull/2622
