### ISSUE TITLE
localSave() doesn't behave as desired in Safari

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#261]
Safari displays the text file instead of creating a file. There may be ways around this:
- [FileSaver.js](https://github.com/eligrey/FileSaver.js/#supported-browsers)
- [Relevant StackOverflow thread](http://stackoverflow.com/questions/12802109/download-blobs-locally-using-safari)

**Comment by spencerking** [comment]
@jodeleeuw 
I just tested this in Safari 10.1.2 with the following code and it works as intended.

`jsPsych.data.get().localSave('csv','mydata.csv');`

If you'd like, I can update jspsych-data.md to reflect that this functionality now works in Safari.

**Comment by jodeleeuw** [comment]
That's great! Yes, please do update the documentation.
