### ISSUE TITLE
jsPsych: audio + image not loading 

### ISSUE THREAD

**Issue by Deewa-A** [jspsych/jsPsych#2616]
Hi,
I am relatively new to jspysch and coding in general, so I kindly ask for your patience on this question.

I create a script to run a study that requires image and audio media. I have run the script before (months ago using jspyshc version 6). I saw that there have been recent changes to the code (ex. 'external-html' -> jsPsychExternalHtml; including initJsPsych({}) in the begining and  jsPsych.run() at the end of the script). 

I implemented these changes yesterday and ran the script. It ran smoothly and I launched it online. Today, as I was launching the study to an online sample, I found that that media was not loading (although it was perfect yesterday).

I did some trouble shooting with preloading (var preload = {};  override_safe_mode: true etc.; max_load...) but unfortunately the issue remains. Does anyone have any insights as to why this has occurred, and how I can fix it? 

Additional info: 
- Error message: "The experiment failed to load.
Error details: 'Error loading file: tone.mp3
File did not begin loading. Check that file path is correct and reachable by the browser, and that loading is not blocked by cross-origin resource sharing (CORS) error' 
- Image simply does not appear 
- Files: [Ready to upload.zip](https://github.com/jspsych/jsPsych/files/8645635/Ready.to.upload.zip)

Thank you in advance.

**Comment by Deewa-A** [comment]
Thank you kindly for the response. This is the link: https://fxsel7hk18.cognition.run/
I reached out to cognition.run as well, and they noted the link should be working now (which it does).  I think the issue might have been on their part.

**Comment by bjoluc** [comment]
Thanks for the link!

> I think the issue might have been on their part.

Looks so, hence closing this. Feel free to re-open if it occurs again.
