### ISSUE TITLE
Potential inefficient behavior

### ISSUE THREAD

**Issue by vijaymarupudi** [jspsych/jsPsych#2626]
Hello!

This issue is not too important, just wanted to bring it to your attention.

I think this might take long for experiments with lots of trials. After each trial, `jsPsych.finishTrial()` iterates through every trial that has completed to get a reference to the data that was added. So if there were 1000 trials, `jsPsych.finishTrial()` would loop 1000 times to find the data it had just saved.

I might be wrong, so please check me on this.

https://github.com/jspsych/jsPsych/blob/518c76fe50222e213965a605e0f4e943f26edc96/packages/jspsych/src/JsPsych.ts#L245

**Comment by jodeleeuw** [comment]
Thanks @vijaymarupudi. I think you are correct here.

**Comment by jodeleeuw** [comment]
Brainstorming possible fixes:

- use `.getLastTrialData()` or `.last()` instead of `.filter()`
- make [`.write()`](https://github.com/jspsych/jsPsych/blob/518c76fe50222e213965a605e0f4e943f26edc96/packages/jspsych/src/modules/data/index.ts#L35-L53) return the updated `DataCollection`
