### ISSUE TITLE
canvas-slider-response appearance 

### ISSUE THREAD

**Issue by giuconte** [jspsych/jsPsych#2636]
Dear all,
in the canvas-slider-response the slider looks different than in the image-slider-response or html-slider-response which are consistent with each other. How can I change the appearance of the canvas-slider-response to make it consistent with the others? I looked in the css file, but couldn't find the solution. I would like to take this opportunity to thank the contributors for their great work.

**Comment by jodeleeuw** [comment]
This was a simple fix. The `<input type="range">` element is missing the `jspsych-slider` class. I've added it in PR #2637. While you are waiting for a release you can fix this by adding the class yourself in the plugin file.

**Comment by jodeleeuw** [comment]
The new package is now released. You should be able to update to the latest version and get the correct slider appearance.

**Comment by giuconte** [comment]
Thank you very much for the fix!
