### ISSUE TITLE
add plugin.info method

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#270]
This is partially in prep for the GUI.

`plugin.info` returns an object with a description of the plugin and all its parameters.

**Comment by wolfgangwalther** [comment]
I like the idea of `plugin.info`.
The default values given here could also be used in the `pluginAPI` module to set the trial's default parameters at the start of each trial. Currently this is done by various lines of code in each plugin. There could be a common method to set default values and evaluate function parameters, that the plugin could call. This would simplify plugin code more and also remove redundancy between the default values set in code and in the plugin.info.
I implemented a draft of this locally and could polish this up a little bit to open a PR.

**Comment by jodeleeuw** [comment]
Yes, this is absolutely the direction I wanted to go in with this method. The spec for plugin.info is in flux as we build out the GUI, butI hope that the method can eventually be used for defaults and validation.

**Comment by wolfgangwalther** [comment]
Ok, cool! Some suggestions for the spec on this:

In the current spec, what would the `no_function` parameter be used for? It seems like it is set to `false` for every parameter in every plugin right now. I initially thought this could be used to decide whether to run `evaluateFunctionParameters` for this parameter (not doing so for parameters taking callback functions), but the better way to do this would probably be based on `type: [jsPsych.plugins.parameterType.FUNCTION]`.

I suggest two additional settings for the trial parameters, both concerning parameters, that have `array: true` set:
* `length`: Length of the array. Can be either an integer number, so the array set for this parameter will be made of this length, or be set to a string, containing the name of another trial parameter. The length of the array would then be set to the length of the array of the referenced parameter. This comes in handy in a lot of cases, where two parameters have to have the same length for a given trial (e.g. `rows` and `columns` must be the same length as `questions` in plugin `survey-text`)
* `default_item`: Every `undefined` item in the array would be replaced with this. If you were to provide an empty array for `columns` in the example above, `length: 'questions'` would set the length of this array to the same length as the `questions` parameter and each item in this array would then be set to `default_item`, which would be 40, for the survey-text plugin right now.

I use both in a plugin which is currently in development, where I drafted the implementation of this method.

Going through all the plugins, I think the only parameters, that could not be set / validated with this spec so far, would be those were either an array or a string/number/... would be allowed:
* `button_html` in the `button-response` plugin
* all those `choices` and related parameters, that specify allowed keys in different plugins

One solution for this could be to actually make the `plugin.info.parameters[...].array` / `.length` / `.default_item` settings arrays of the same length as `plugin.info.parameters[...].type`. We could then set those values for each `type` independently. The `button_html` info in `button-response` could look like this:
```javascript
button_html: {
  type: [jsPsych.plugins.parameterType.STRING, jsPsych.plugins.parameterType.STRING],
  array: [false, true],
  length: [/* first item is undefined, because array is false here */, 'choices'],
  default_item: [/* first item is undefined, because array is false here */, '<button class="jspsych-btn">%choice%</button>'],
  default: '<button class="jspsych-btn">%choice%</button>',
  no_function: false,
  description: ''
},
```

This would allow us to set `button_html` to either:
* a string containing the html for every button
* an array of the same length as `choices`, setting the html for every button explicitely
* an array with undefined values, just overriding the default value for some of the buttons:
`button_html: [ , '<button class="jspsych-btn blue">%choice%</button>']` would override the 2nd button with this html (note the `,` in the array, leaving the first item undefined). The 1st button would still use the default value (through `plugin.info.parameters[...].default_item`).

**Comment by jodeleeuw** [comment]
@kristiyip There are some plugins that don't have this implemented yet. With the changes for #426, plugins will now need to implement this to work. Can you work on the missing plugins at some point this week? The only crucial bit right now is the parameter types. Everything else can be omitted since we are still fleshing out the spec.
