### ISSUE TITLE
Fullscreen for mobile devices

### ISSUE THREAD

**Issue by klanderson** [jspsych/jsPsych#2813]
Has anyone has success using the fullscreen plugin with mobile devices? I’ve tried it with Safari and Chrome on iOS and have not gotten it to work. It does work with an iPad however. 

The next best solution might be hiding the address bar but this also doesn’t seem straightforward.

An online search for fullscreen (or even hiding the address bar) on mobile devices gives a lot of outdated and conflicting answers so I’m not sure what it possible.

Refs:
[caniuse.com/fullscreen](https://caniuse.com/fullscreen)
[Hiding address bar 1](https://ishwar-rimal.medium.com/fixing-that-address-bar-issue-in-mobile-browsers-once-and-for-all-8c283fc88e56)
[Hiding address bar 2](http://menacingcloud.com/?c=iPhoneAddressBar)

**Comment by bjoluc** [comment]
Hi @klanderson,

I've used the fullscreen plugin in multiple experiments and it almost certainly wouldn't work on iPhones, but typically worked on Android (pretty much replicating the statistics at caniuse.com). Sadly, there's not much we can do here on devices that do not support the fullscreen API :confused: If you manage to reliably hide the address bar, please let us know so we can think about extending the fullscreen plugin.

Thanks!
