### ISSUE TITLE
 can't load webgazer.js file 

### ISSUE THREAD

**Issue by kmamine** [jspsych/jsPsych#2851]
Hi, 
I'm  running the JsPsych Eye-tracking example and I was confronted with the following error : 

on Firefox  : 
`The resource from “https://cdn.jsdelivr.net/gh/jspsych/jsPsych@7.0.0/examples/js/webgazer/webgazer.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).` 
 
On google chrome 
`GET https://cdn.jsdelivr.net/gh/jspsych/jsPsych@7.0.0/examples/js/webgazer/webgazer.js net::ERR_ABORTED 404` 

Apparently, I can't load the webgazer.js file
This work well yesterday, but I  was confronted with this issue today.  

Thanks for helping me out with this situation.

**Comment by bjoluc** [comment]
It's odd that this used to work – the correct tag for 7.0.0 is `jspsych@7.0.0`, so the URL should be `https://cdn.jsdelivr.net/gh/jspsych/jsPsych@jspsych@7.0.0/examples/js/webgazer/webgazer.js`. Fixed now, thanks for flagging @kmamine!
