### ISSUE TITLE
Log keypress without progressing sequence?

### ISSUE THREAD

**Issue by addingasun** [jspsych/jsPsych#2860]
Hi, I'm trying to develop a project that shows a sequence of images that participants must respond with a keypress to. I want the images to be presented for a set amount of time, but I also need the keypresses to be logged so I can ensure they are responding correctly to the sequence. I have the trials set to a certain duration so they progress over time, but the keypress still moves to the next trial and I don't want that, I just want it to log the press.

**Comment by addingasun** [comment]
I have a post-trial gap already implemented, I don't think it's an issue of holding down the key I just mean I want the key press to be logged without progressing the sequence, but I think with `jsPsychImageKeyboardResponse` it defaults to this, so I'm looking for a way for it to keep track of whether or not the key was pressed without moving the sequence to the next trial. I have a trial duration also set that I want it to stick to, but I need it to be logged whether or not the key was pressed because I also have a conditional timeout message set to run if the key isn't pressed.

**Comment by nikbpetrov** [comment]
Not sure what you mean with "sequence". If it means that you have 5 trials of `jsPsychImageKeyboardResponse` that you want each displayed for X seconds, regardless of whether the participant provides a response or not (but you still want to record if they do provide a response), then you might want to look at the `response_ends_trial` options of the [plugin](https://www.jspsych.org/7.3/plugins/image-keyboard-response/) - just set it to false and the image will be displayed until `trial_duration` ends AND their first response will be recorded.

**Comment by addingasun** [comment]
That's exactly what I was looking for, thank you
