### ISSUE TITLE
Allow trial's `on_finish` method to be async.

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#2902]
We added functionality of extensions to have async `on_finish` events. It would be helpful in some rare circumstances for the trial's `on_finish` to be async as well. (The specific case that I'm running into is pushing data from the trial to a server, and wanting to wait for the response before proceeding.)

@bjoluc is this already implemented in the v8 code?

**Comment by bjoluc** [comment]
@jodeleeuw Not implemented yet, but fairly easy to do :+1:
