### ISSUE TITLE
JsPsych study, local JATOS saving CSV, public server saving JSON

### ISSUE THREAD

**Issue by Kedersha** [jspsych/jsPsych#2977]
Hi, hope you're well!

([cross-posting to the JATOS forum](https://forum.cogsci.nl/discussion/8462/jspsych-study-local-jatos-saving-csv-public-server-saving-json/p1) as well)

I'm setting up a study using JATOS 3.7.4 and plugins from jsPsych 7.3. I'd like to save the data as a CSV using jsPsych's old data.csv function to do the conversion (as below)

```
        var resultData =  jsPsych.data.get().ignore('accuracy').ignore('internal_node_id').ignore('question_order').ignore('stimulus').filter([{trial_type:'survey'}, {trial_type:'survey-likert'}]);
        jatos.submitResultData(resultData.csv(),jatos.endStudy);
```

I've also attached an abbreviated version of this annotation script [here](https://github.com/jspsych/jsPsych/files/10912862/samplecode.txt) (the extension was originally .html, just changed it for uploading here).

It's working fine on my local server and saving a CSV as intended, but the exact same study is saving all results as JSON on the production server. Do you have any ideas about what might be going on?

Thanks!

**Comment by Kedersha** [comment]
Okay, I did a little more testing. It looks like what's happening is that if you interrupt the study and close it early, it saves as JSON not as CSV (it also doesn't add JATOS worker IDs, which was something I'd just added in the on_close function). However if you go all the way through the study, it saves the CSV and adds the worker IDs. Do the new versions of jsPsych not have the same on_close options, or is this a glitch?

**Comment by becky-gilbert** [comment]
Hi @Kedersha, sorry for the very slow reply, and I'm not sure if this is still helpful, but this might have something to do with the order of function calls. What happens if you move the `csv` command so that it's called on the `resultData` before the call to `jatos.submitResultData`, i.e.
```js
var resultData =  jsPsych.data.get().ignore('accuracy').ignore('internal_node_id').ignore('question_order').ignore('stimulus').filter([{trial_type:'survey'}, {trial_type:'survey-likert'}]).csv();
jatos.submitResultData(resultData,jatos.endStudy);
```

**Comment by Kedersha** [comment]
Hi! I tried this out on my local server, interrupting the study partway through, and it seems to work. The study's already complete now, without any problems arising from this little issue, so I won't put the time into testing it on the production server, but thanks for looking into it. :) Take care!
