### ISSUE TITLE
Dynamic Parameters - error in documentation

### ISSUE THREAD

**Issue by norabradford** [jspsych/jsPsych#3032]
The code for feedback in the Dynamic Parameters page seems to be broken - it always returns "wrong". Could just be something strange with my code, but I copy pasted directly from the page.

**Comment by jodeleeuw** [comment]
Hi @norabradford,

I just tried to reproduce this problem and it worked OK for me. Can you share the entire example where it doesn't work?

**Comment by norabradford** [comment]
Ah, ok it may be something wrong with my code then. The file is here-> https://github.com/norabradford/NumerosityExperiment/blob/main/numerosity_test1.html and the issue is in lines 287-322. It always registers as an "incorrect" trial, even when I press 'f'

**Comment by norabradford** [comment]
Oop! just kidding, I got it. For some reason 'f' couldn't be used as the correct answer... it had to be the key code ('70')

**Comment by jodeleeuw** [comment]
Ah, yeah, that's because you are using version 6.2. I think we changed to characters as responses at 6.3.

Glad it is resolved!
