### ISSUE TITLE
Source maps not found when loading scripts from short CDN URLs

### ISSUE THREAD

**Issue by tmalsburg** [jspsych/jsPsych#3043]
I'm following the documentation [here](https://www.jspsych.org/7.3/tutorials/hello-world/#option-1-using-cdn-hosted-scripts), but get the this error message when loading the page:

```
Source map error: Error: request failed with status 404
Resource URL: https://unpkg.com/jspsych@7.3.3
Source Map URL: index.browser.min.js.map
```

Tried Firefox and Chromium, same result.

Relevant line:

``` html
    <script src="https://unpkg.com/jspsych@7.3.3"></script>
```

**Comment by bjoluc** [comment]
Hi @tmalsburg,

this is your browser trying to load the source map file that belongs to https://unpkg.com/jspsych@7.3.3/dist/index.browser.min.js (which is https://unpkg.com/jspsych@7.3.3/dist/index.browser.min.js.map), failing to find it at https://unpkg.com/index.browser.min.js.map. The source maps are not required to run jsPsych, but they can help you debugging it. You can work around the error by using the canonical script URL:
js```
<script src="https://unpkg.com/jspsych@7.3.3/dist/index.browser.min.js"></script>
```

I found a workaround for this issue in the build chain of my v8 draft, but didn't bother to look for a way to backport it yet. I'm planning to do so, so let's keep this issue open until I get to it.

Cheers!
