### ISSUE TITLE
Option to randomize question order in survey plugins

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#305]

**Comment by fredcallaway** [comment]
This, and many other fine-control features could be easily achieved if the trial was parameterized by a list of objects describing each question, e.g. (in coffee script)

```coffee
bridge_quiz =
  kind: 'survey-multi-choice'
  items: jsPsych.randomization.shuffle [
    question: 'What is your name?'
    options: ['Sir Arthur', 'That guy who gets eaten by the rabbit']
    required: true
  ,
    question: 'What is your quest?'
    options: ['To seek the holy grail', 'Ummm...']
    required: true
  ,
    question: 'What is your favorite color?'
    options: ['Blue', 'No, yellow!']
    required: false
  ]
```

Something else that would be easier with this style would be assigning different questions to different conditions. On the other hand, it would be inconsistent with much of the library and it is a bit more verbose (although imho, grouping attributes by item is more readable).

**Comment by jodeleeuw** [comment]
I agree. @GavinQ1 has done amazing work on a new form plugin (#310) that will likely replace these simple survey plugins. It is organized in this item-focused way. We are just working on finalizing the parameter set before merging it into the library.

**Comment by fredcallaway** [comment]
Wow, that looks great! I will make one suggestion to include an optional "correct" field. This streamlines a common use case for forms: quizzes to test participant comprehension of instructions.

**Comment by jodeleeuw** [comment]
Great idea. @GavinQ1, is that something you can do now, or should we wait?

**Comment by GavinQ1** [comment]
@jodeleeuw Sure but probably next week? I need to prepare for finals this week.

**Comment by jodeleeuw** [comment]
No rush, just wanted to get it on the list! Thanks!
