### ISSUE TITLE
jsPsychVideoButtonResponse & jsPsychVideoKeyboardResponse

### ISSUE THREAD

**Issue by ncuneo711** [jspsych/jsPsych#3102]
I tried using jsPsychVideoButtonResponse and jsPsychVideoKeyboardResponse (either one works for my study since this is just a filler task). I am using the exact documentation from the plugin docs (https://www.jspsych.org/7.0/plugins/video-keyboard-response/ & https://www.jspsych.org/7.0/plugins/video-button-response/). I am consistantly getting the error that my stimulus must be in an array. I tried changing the video I was using to the sample one in the js folder and still received this error.

Code below:

var trial = {
        type: jsPsychVideoButtonResponse,
        stimulus: [
            'video/load.mp4'
        ],
        choices: ['0-5', '6-10','11-15','16-20','21-25','25+'],
        prompt: "<p>How many different fish are shown in the video?</p>",
        response_allowed_while_playing: false
};

var filler = {
            type: jsPsychVideoKeyboardResponse,
            stimulus: [
                 'video/load.mp4'
           ],
            choices: "NO_KEYS",
            trial_ends_after_video: true
            };

**Comment by alessandraluz** [comment]
Hi, did you manage to figure out a fix for this?

**Comment by ncuneo711** [comment]
yes (kind of) but i ended up clearing my cache/history and re-running the code and it worked totally fine/haven't had an issue again!
