### ISSUE TITLE
button_label_next not working

### ISSUE THREAD

**Issue by ahmedtarek-** [jspsych/jsPsych#3120]
I am having a problem to override the text for the next button for the instruction block. I followed this guide 
https://www.jspsych.org/7.3/plugins/instructions/

and did this

```javascript
var close_friend_block = {
  type: 'poldrack-instructions',
  data: {trial_id: 'user-info'},
  pages: [],
  allow_keys: false,
  button_label_next: "Weiter",
  button_label_previous: "Zurück",
  show_clickable_nav: true,
}
```

Yet the button still appears with the default "next". Not sure how to fix this

**Comment by bjoluc** [comment]
Hi @ahmedtarek-,

your template is using an old jsPsych version (<7, which one precisely I cannot tell), and you are not using the official instructions plugin, but a [modified version of it](https://github.com/ahmedtarek-/ravens/blob/master/js/jspsych/poldrack_plugins/jspsych-poldrack-instructions.js). The description in the plugin file reads

> Modification by Ian Eisenberg - changed navigation buttons such that the "Next" button reads "End Instructions" on the last page

I'm pretty sure that's what broke it. You can either [set up the latest jsPsych version](https://www.jspsych.org/7.3/tutorials/hello-world/) for your experiment, use the original instructions plugin for your jsPsych version (might be as simple as just replacing `'poldrack-instructions'` with `'instructions'` in your snippet), or fix your modified plugin version.

Cheers!
