### ISSUE TITLE
survey.css not shipped in latest release

### ISSUE THREAD

**Issue by niket-agrawal** [jspsych/jsPsych#3131]
Although, I can use the following to survey stylesheet
`<link rel="stylesheet" href="https://unpkg.com/@jspsych/plugin-survey@0.2.1/css/survey.css">`

It would be much better if you can bundle it in `dist` directory along with other plugin files. It would help us run the experiments in offline environments.

**Comment by becky-gilbert** [comment]
Hi @niket-agrawal, thanks for pointing this out! I'm working on a major update to the survey plugin (PR #3204), and I will see if we can include the CSS file in `dist`.
