### ISSUE TITLE
Links to the 'Media Preloading' page are broken in the 'preload' plugin page

### ISSUE THREAD

**Issue by ubdbra001** [jspsych/jsPsych#3165]
As per title, the links on the [preload plugin page](https://www.jspsych.org/7.3/plugins/preload/) direct to: `https://www.jspsych.org/7.3/plugins/overview/media-preloading/` instead of `https://www.jspsych.org/7.3/overview/media-preloading/`

**Comment by jadeddelta** [comment]
closing this as it looks like it was fixed with [this pr](https://github.com/jspsych/jsPsych/pull/3275), appreciate the report though!
