### ISSUE TITLE
Update plugin development documentation for v8

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#3180]
Things to change:

- [x] Mention that trial can be `async` and return the data rather than calling `jsPsych.finishTrial()`
- [x] Changes to `info` to support metadata
- [x] No need for clearing display, timeouts.

**Comment by jodeleeuw** [comment]
@bjoluc are there any other major changes here to update in the plugin documentation that I'm missing?

**Comment by bjoluc** [comment]
@jodeleeuw If we decide to drop `pretty_name`, that would be one thing. If we decide to accept undefined parameters without a default value and introduce `required: true` instead, that would be the other thing. And #3241 of course, if we go that route.
