### ISSUE TITLE
Free-sort plugin not working on Safari

### ISSUE THREAD

**Issue by irenegreenbean** [jspsych/jsPsych#3183]
The free-sort plugin does not seem to be allowing the drag and drop option for stimuli when used in safari. You can click the stimuli but you will not be able to drag or move them anywhere. (also some people who have been testing the link have said that the stimuli, which are clickable buttons that play audio clips, also aren't playing the sounds correctly and people cannot hear any of the stimuli)

https://github.com/irenegreenbean/map-drawing-no-alipay 
This is my repo using the jspsych free-sort plugin, and this: https://proliferate.alps.science/experiment/590bd685-e41a-4ddc-baa4-003aae867002/debug is the experiment page (on the pages where the instructions are in Chinese, just click the button to continue. The main page with the issues is the free-sort page, which is a bunch of small square stimuli and one large rectangle area to drag the stimuli into. The stimuli can be played by clicking, and then if you click and hold, you'll be able to drag them.)

I'm not sure what is the issue, because the drag and drop function works fine on Chrome.

**Comment by irenegreenbean** [comment]
It seems that even with the demo on the jspsych documentation, the example demo won't allow dragging of the visual stimuli in Safari either. Is this just an issue with the free-sort plugin? If so, is there any way this could be fixed to work on Safari? I'm running this experiment in a country that does not allow the use of Google Chrome, so very few people have access to Chrome as a browser.

**Comment by Shaobin-Jiang** [comment]
Strange. Though I do not have mac, I have tested the jsPsych demo via lambdatest on safari and everything works fine.

And btw, that country you are referring to does not ban Google Chrome. It bans most services provided by Google, but its people have no trouble getting access to [google chrome](https://www.google.cn/chrome/).

**Comment by bjoluc** [comment]
Thanks for checking @Shaobin-Jiang. @irenegreenbean I guess this was fixed by #2893, i.e. in @jspsych/plugin-free-sort version 1.0.3? If not, feel free to re-open this issue :slightly_smiling_face:
