### ISSUE TITLE
response_ends_trial: false functionality for visual-search-circle

### ISSUE THREAD

**Issue by derekalbert** [jspsych/jsPsych#3210]
Hi, I'm using the visual-search-circle plugin and want to have the trial last its full duration (as per trial_duration) despite participants entering a response. That is to say, it would be great to have response_ends_trial: false functionality in this plugin. I am trying to modify the plugin myself using logic from html-keyboard-response, but struggling. Id really appreciate some help!

**Comment by jodeleeuw** [comment]
Caught me at a good time for this 😁 - I just added this feature in #3211. It'll be live on npm in a bit.

**Comment by jodeleeuw** [comment]
Updating to version `1.2.0` should add the feature.

**Comment by derekalbert** [comment]
Thank you!

**Comment by derekalbert** [comment]
Hi Jo, I'm trying to plugin but there seems to be an issue. Now, the arrays pile up. Maybe they aren't properly getting cleared from the screen?

**Comment by derekalbert** [comment]
I re-added the clear_display function from the previous version to this new one and called it prior to all instances of end_trial. This seems to have fixed the problem. Will let you know if I come across others.

function clear_display() {
     display_element.innerHTML = "";
}

**Comment by jodeleeuw** [comment]
Oops. I'll publish a fix for this. Thanks for flagging it.
