### ISSUE TITLE
MathJax for html in jsPsych (v7.1)?

### ISSUE THREAD

**Issue by collinskatie** [jspsych/jsPsych#3237]
Thanks jsPsych team for such an awesome framework! 

I was wondering what the best way to get something like MathJax https://docs.mathjax.org/en/latest/index.html would be within a  jsPsych trial? In particular, we have LaTex in (e.g., "$C_1$, "$B^{2x}$") in the prompt / stimulus html for some of our trials that we'd like to render nicely. 

We currently have a single task.js file, which we run in our index.html via 

```
<body>

	<script src="task.js"></script>

</body>  
```

We've tried adding 

`<script type="text/javascript" id="MathJax-script" async
	src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>`

to the imports alongside the other plug-ins, but we haven't seemed to be able to get it to work... so thought I'd see if there was an easy way? We're also using version 7.1 (as we're working with Pavlovia, which I believe only supports up to that version at the moment). 

Reading online, it seemed like it could be useful to add the following in the on_load for a trial, but that also doesn't seem to help (and stretches my current javascript understanding...)

```
on_load: function () {
    MathJax.typesetPromise();
   ....
}
```

Thanks for any tips on getting MathJax to work!

**Comment by Shaobin-Jiang** [comment]
That is because MathJax does not use `$` for inline math by default. You might want to do something like this:

```javascript
let trial = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: '\\(\\frac{1}{2}\\)',
    on_load: function () {
        MathJax.typesetPromise();
        // Or if you want more precise control over which element to render (the code below works with this plugin only):
        // MathJax.typeset([document.querySelector('#jspsych-html-keyboard-response-stimulus')]);
    }
};
```

Or, if you really want to do it the LaTex way, you can add this piece of code at the front:

```javascript
window.MathJax = {
    tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]}
};
```

**Comment by collinskatie** [comment]
Thank you very much! That worked! I parsed all of our $$ to the "\(...\)". In case anyone needs help doing that parse, here's a replacement that helped (modified from GPT :) ) 

`problem_statement.replace(/\$(.*?)\$/g, '\\($1\\)');`
