### ISSUE TITLE
Unable to run jsPsych in node.js

### ISSUE THREAD

**Issue by eeviriyi** [jspsych/jsPsych#3249]
It seem that when I run the demo code in the [tutorials](https://www.jspsych.org/7.3/tutorials/hello-world/#option-3-using-npm):

```
import 'jspsych';
import htmlKeyboardResponse from '@jspsych/plugin-html-keyboard-response';
import 'jspsych/css/jspsych.css'
import {initJsPsych} from "jspsych";
const jsPsych = initJsPsych();
const trial = {
    type: htmlKeyboardResponse,
    stimulus: 'Hello world!',
};
jsPsych.run([trial])
```

the terminal occurred an error just like this:

```
87 |         super(`${message} Please follow the migration guide at https://www.jspsych.org/7.0/support/migration-v7/ to update your experiment.`);
88 |         this.name = "MigrationError";
89 |     }
90 | }
91 | // Define a global jsPsych object to handle invocations on it with migration errors
92 | window.jsPsych = {
     ^
ReferenceError: Can't find variable: window
```

I have successfully run the demo in HTML, but unable to run it in node.js. Where is wrong?

**Comment by Shaobin-Jiang** [comment]
Are you running your javascript code directly with `node`? Check out the doc [here](https://www.jspsych.org/7.3/tutorials/hello-world/#option-3-using-npm):

> If you are electing to use npm to install jsPsych we will assume that you already are familiar with Node.js and generally know what you are doing with web development. **We will also assume that you are using a [webpack](https://webpack.js.org/) or a similar bundler.**

The `window` object is usually only available in a browser environment and cannot be accessed in node without additional packages. A bundler would do that for you.
