### ISSUE TITLE
Edit button colour after selection

### ISSUE THREAD

**Issue by Dazzid** [jspsych/jsPsych#3259]
I'm using this code to customize the buttons. However, the command to change the background color is not working. 
It seems the command _.jspsych-survey-multi-choice-option input[type="radio"]:checked + label_ 
It is not correct.
What I'm missing? Should I use plugins instead?

```
const radialButtonStyles = `
/* Target the containers for each option to apply a horizontal layout */
.jspsych-survey-multi-choice-option {
  display: inline-block; /* Align options horizontally */
  margin-right: 5px; /* Space between options */
}

/* Hide the actual input (radio button) visually but keep it accessible */
.jspsych-survey-multi-choice-option input[type="radio"] {
  position: relative;
  opacity: 100;
  width: 2;
  height: 2;
}

.jspsych-survey-multi-choice-option label {
  background-color: #f0f0f0; /* Light background for the label */
  padding: 3px 20px; /* Padding around the text */
  border-radius: 20px; /* Rounded corners for the labels */
  font-size: 16px; /* Adjust font size as needed */
  cursor: pointer; /* Pointer cursor on hover */
  display: inline-block; /* Ensure label is inline-block for proper spacing */
  transition: background-color 0.3s, color 0.3s; /* Smooth transition for color changes */
}

/* Change label background and text color when radio button is selected */
.jspsych-survey-multi-choice-option input[type="radio"]:checked + label {
  background-color: #ff9900; /* Orange background for selected option */
  color: white; /* White text for selected option */
  opacity: 100;
  width: 1;
  height: 1;
}
```

**Comment by Shaobin-Jiang** [comment]
What is this you are doing here? This is apparently not inline CSS and yet you are prefixing it with a `const`, thereby declaring it as a constant. Are you trying to dynamically insert CSS? If so, why not just import it in a CSS file?

And what do you mean by

> Should I use plugins instead?

How do you expect the survey-multi-choice plugin to function without using it?

**Comment by Dazzid** [comment]
The point is that I'm using cognition.run, perhaps this is not the place for such a question

**Comment by jodeleeuw** [comment]
Hi @Dazzid 

Happy to help figure this out. I think in cognition.run you can insert custom CSS files. Is that correct?

**Comment by Shaobin-Jiang** [comment]
Use this piece of code instead:

```css
.jspsych-survey-multi-choice-option label:has(> input[type="radio"]:checked) {
  background-color: #ff9900; /* Orange background for selected option */
  color: white; /* White text for selected option */
}
```

See here on [stackoverflow](https://stackoverflow.com/questions/1014861/is-there-a-css-parent-selector).
