### ISSUE TITLE
String concatenation in multi-select leading to empty values

### ISSUE THREAD

**Issue by RobAWilkinson** [jspsych/jsPsych#327]
When using survey-multi-choice if one of the possible choices contains a double string, the value on the input will be messed up.

Steps to reproduce:

```html
<script src="jsPsych/jspsych.js" ></script>
<script src="jsPsych/plugins/jspsych-survey-multi-choice.js" ></script>
<script>
var answer1 = 'She said, "answer1"';
  var multi_choice_block = {
    type: 'survey-multi-choice',
    questions: ['question'],
    options: [[answer1, 'answer2', 'answer3']],
  };
  jsPsych.init({
    display_element: document.body,
    timeline: [multi_choice_block],
    on_finish: function(data) {
      console.log(data)
    },
  });
</script>
```
Result:
<img width="783" alt="screen shot 2017-01-25 at 6 06 03 pm" src="https://cloud.githubusercontent.com/assets/1959628/22317584/8971434a-e329-11e6-9141-ed3b5ff575ef.png">

**Comment by lbai001** [comment]
up

**Comment by jodeleeuw** [comment]
This is probably also a bug in other plugins that allow user input to set html attributes. Need to check.
