### ISSUE TITLE
jsPsych.ParameterType undefined in plugin

### ISSUE THREAD

**Issue by noa-no-h** [jspsych/jsPsych#3315]
Hi! In the minimal plugin I've written, jspsych is returning "undefined" for `console.log(jsPsych.ParameterType); `

This is the line I added to the code after I got the error: 
minimal_plugin.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'STRING')
    at minimal_plugin.js:9:39
    at minimal_plugin.js:26:5
(anonymous) @ minimal_plugin.js:9
(anonymous) @ minimal_plugin.js:26

Here is my minimal plugin code. Any help would be appreciated! 

```
var intro_and_attention_checks = (function(jsPsych) {
    console.log(jsPsych.ParameterType);
  
    const info = {
      name: "intro_and_attention_checks",
      description:"",
      parameters: {
        version: {
          type: jsPsych.ParameterType.STRING,
          pretty_name: "Version",
          default: "v4_sona",
        }
      },
    };
    
    jsPsych.plugins["intro_and_attention_checks"] = (function () {
      const plugin = {};
    
      plugin.info = info;
    
      plugin.trial = function (display_element, trial) {};
    
  
    return plugin;
    })(); 
 })(jsPsych);
```

I think this is similar to #3046  (https://github.com/jspsych/jsPsych/discussions/3046) but I'm not using nmp/parcel

**Comment by jodeleeuw** [comment]
Hi @noa-no-h,

This looks like it might be mixing version 6 and version 7 syntax together. Are you trying to develop for v6 or v7?

**Comment by noa-no-h** [comment]
Thank you! Yes I am not at all surprised that's the problem. I'm developing for v7 and I was hoping to find a template I could work with to better understand plugin development but the link for JavaScript template files in the documentation ("Templates" here: https://www.jspsych.org/7.1/developers/plugin-development/) goes to a missing github folder and the documentation on that page has been difficult for me as a beginner. Could you help me see what I need to change to make this code work for v7? Thanks!

**Comment by jodeleeuw** [comment]
Ah, sorry for the broken link. We moved the templates into a different folder when we added a tool for generating new plugins. Here's the correct link: https://github.com/jspsych/jspsych-contrib/blob/main/templates/plugin-template-js/index.js

You may want to follow [the instructions in the readme](https://github.com/jspsych/jspsych-contrib/tree/main?tab=readme-ov-file#creating-a-new-plugin-or-extension) for creating a new plugin using our CLI tool. It automates the tedious parts of renaming files, copy/pasting, etc.

**Comment by noa-no-h** [comment]
thank you so much! (Hope I didn't sound too complain-y — tone is hard to get right by just text and I'm so grateful for everything you've done to build and support JsPsych!)

**Comment by noa-no-h** [comment]
that part is working now after I copied from the template. Thank you! Now I'm going to try out the CLI tool.
