### ISSUE TITLE
enable_button_after on cognition.run 

### ISSUE THREAD

**Issue by anasophiarc** [jspsych/jsPsych#3317]
Hello, 
I am using the enable_button_after feature for video button and html button responses in an experiment. On cognition.run the most recent jsPsych library is 7.3 which does not seem to include the enable_button_after feature? Locally I have the 1.2.0 version of the plugins included at the top of the file in HTML but I can't keep that in cognition.run. How can I include the most recent version of the plugin on cognition.run? There is an option to upload external JS/CSS files. 

Here is an example of how I am currently intending to use the enable_button_after feature: 
`var instructions = { 
    type: jsPsychVideoButtonResponse, 
    stimulus: ['videos/Instructions.mp4'], 
    choices: ['Continue', 'Review'], 
    height: 450, 
    width: 800, 
    response_allowed_while_playing: true, 
    enable_button_after: 70000, //Delay ability to respond until after 1:10 of the instructions clip has passed 
    response_ends_trial: true, 
    on_finish: function(data) {
        jsPsych.data.addDataToLastTrial({
            review: data.response == 1
        }); 
    }
}; `

Thanks!

**Comment by jodeleeuw** [comment]
I think uploading the JS file https://unpkg.com/@jspsych/plugin-video-button-response@1.2.0/dist/index.browser.min.js to cognition.run would overwrite the server copy of the plugin, but I'm not sure exactly how their system works.

**Comment by anasophiarc** [comment]
@javidalpe would you know anything about this? 

Thanks,
Ana

**Comment by javidalpe** [comment]
Hello @anasophiarc!

Cognition.run was running JsPsych 7.3.3.

I have added JsPsych release 7.3.4, which includes the new video-button-response plugin. 

Give it a try!

Thanks
Javi
