### ISSUE TITLE
jsPsychCanvasButtonResponse: How to center canvas object?

### ISSUE THREAD

**Issue by DominiqueMakowski** [jspsych/jsPsych#3319]
I am using the `jsPsychCanvasButtonResponse`, but the figure is left aligned. 

![image](https://github.com/jspsych/jsPsych/assets/8875533/a11916e8-4a66-47d4-ad66-34f0ae8b9027)

Is there a convenient way to center it or should one add a custom CSS class? 
I would suggest that, given the nature of most JsPsych plugins (which produce centered content), it would be potentially make sense to consider centering as a default

**Comment by Shaobin-Jiang** [comment]
The canvas is centered by default. Could be some additional CSS you have added that caused the problem?

**Comment by DominiqueMakowski** [comment]
Mmh not that I can't think of. I am displaying a chat from `chat.js`, you can see the minimal example [here](https://realitybending.github.io/JSmisc/examples/hexaco18.html) and the [code](https://github.com/RealityBending/JSmisc/blob/536aa6353503177ccb5ccc558370ef9eacb53ff5/examples/hexaco18.html#L58-L77) (as well as that of the [plot](https://github.com/RealityBending/JSmisc/blob/main/misc/plots.js)), but we don't modify any CSS anywhere as far as I can tell. Any pointers?

**Comment by Shaobin-Jiang** [comment]
It seems that `chart.js` is setting an inline `display: block` for the canvas. Removing the style should do the trick.

**Comment by DominiqueMakowski** [comment]
Thanks a lot for your help, much appreciated!
Unfortunately, I'm not that good with javascript & CSS yet so I was wondering how do you remove the style? through an option in the JsPsych object or by an option in the chart?

**Comment by DominiqueMakowski** [comment]
It works thanks a lot :)
