### ISSUE TITLE
Save data in an offline experiment

### ISSUE THREAD

**Issue by kittymimo** [jspsych/jsPsych#3437]
Hi!

I am conducting an offline experiment and saving data locally. I am able to save the data at the end of the experiment, using the `on_finish` function. I am wondering if there is a way to save the data before the end, for instance if the participant does not finish the experiment. I tried using the `on_close` function, but that does not work.

Thank you!

Catherine

**Comment by mrzdcmps** [comment]
Hi Catherine,

you could use the `on_trial_finish` to continously save and override a result file:
```
    const jsPsych = initJsPsych({
        on_trial_finish: function() {
                saveData(jsPsych.data.get().csv())
        }
    });
    ```

**Comment by kittymimo** [comment]
Hi,

Thanks so much for your answer! I tried what you suggested, and it kind of worked, but there are two problems: 1) After every trial, there’s a download icon that jumps down to my Downloads folder, which is very distracting; 2) A new file is created after each trial (adding -2, -3, etc. to the file name). I’m on Mac, and I tried running the experiment with Safari and Chrome.

Do you know how I could resolve these issues, or do you have other ideas to save the data before the end of the experiment?

Thank you!

**Comment by jodeleeuw** [comment]
Hi Catherine,

If you are running in the lab and you know that a participant is done but hasn't finished you can open up the Developer Console in the browser and type `jsPsych.data.get().localSave(...)` filling in the parameters you want for the localSave. But this does require some supervision and making sure that the browser window isn't closed.  Is that feasible?

**Comment by kittymimo** [comment]
Thank you both very much for your help! 

@jodeleeuw , the option you proposed was not really feasible for me, but I found an alternative. I used `jsPsych.endCurrentTimeline`, and so now I can press ‘Escape’ during the experiment and move to the last page of the experiment, which allows me to save the data with the `on_finish` function.

**Comment by kittymimo** [comment]
Thank you both very much for your help!

@jodeleeuw , the option you proposed was not really feasible for me, but I found an alternative. I used `jsPsych.endCurrentTimeline`, and so now I can press ‘Escape’ during the experiment and move to the last page of the experiment, which allows me to save the data with the `on_finish` function.
