### ISSUE TITLE
improve readme with code / demo examples

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#354]
Readme file could have sample code snippets and animated GIFs of what the experiment renders to.

**Comment by jodeleeuw** [comment]
@kristiyip Do you think you could work on this early next week? 

I'm imagining some kind of short gallery of code excerpts and GIFs of the experiments that they render to. It would be good to have:
 - a simple example with the single-stim plugin
 - another simple example of the instructions plugin
 - a slightly longer example that shows a "real" experiment in < 50 lines. Maybe something like the lexical decision task in the examples folder.

**Comment by kristiyip** [comment]
Do you want me to video building the experiment and then opening it on the browser?

**Comment by jodeleeuw** [comment]
I think just a clip of the experiment running, and we'll put that side-by-side with the code. Let's at least try it that way first, and then go from there.
