### ISSUE TITLE
Button label not configurable in some plugins

### ISSUE THREAD

**Issue by hugueslacroix** [jspsych/jsPsych#360]
Button labels are not configurable in some plugins (e.g., survey-text, survey-likert, etc.). I suggest adding a new optional parameter that could be called "button". Implementing this parameter would require the following code at the beginning of the trial function : 
`trial.button = typeof trial.button === 'undefined' ? 'Submit Answers' : trial.button;` 

And replacing the HTML : 
`display_element.innerHTML += '<button id="jspsych-survey-text-next" class="jspsych-btn jspsych-survey-text">Submit Answers</button>';`

With : 
`display_element.innerHTML += '<button id="jspsych-survey-text-next" class="jspsych-btn jspsych-survey-text">'+ trial.button +'</button>';`

**Comment by jodeleeuw** [comment]
I would welcome this pull request. Perhaps with `trial.button_label` instead of `trial.button` for a more descriptive parameter name?
