### ISSUE TITLE
Default value in survey-text plugin

### ISSUE THREAD

**Issue by hugueslacroix** [jspsych/jsPsych#361]
It could be nice to have a the possibility to push some default value in the survey-text plugin (some default text in the textarea field. I suggest inserting this at the beginning : 

```
    if (typeof trial.values == 'undefined') {
      trial.values = [];
      for (var i = 0; i < trial.questions.length; i++) {
        trial.values.push("");
      }
    }
```

And replacing this line : 
```'<textarea name="#jspsych-survey-text-response-' + i + '" cols="' + trial.columns[i] + '" rows="' + trial.rows[i] + '"></textarea>'+```

With this one: 
```'<textarea name="#jspsych-survey-text-response-' + i + '" cols="' + trial.columns[i] + '" rows="' + trial.rows[i] + '">'+trial.values[i]+'</textarea>'+```

(I'll start contributing code soon, once I figure the best way to do that on GitHub).

**Comment by jodeleeuw** [comment]
I think this is a good idea. Perhaps using the [placeholder attribute ](https://www.w3schools.com/tags/att_textarea_placeholder.asp) instead of actual text? It depends what use cases you have in mind.

**Comment by hugueslacroix** [comment]
Placeholders could be a good idea for other situations, but I need the subject to correct the sentence in the textarea, so I need to put the sentence as the "value" or content of the textarea.
