### ISSUE TITLE
CSS for jspsych-display-element not rendering properly

### ISSUE THREAD

**Issue by roten7** [jspsych/jsPsych#370]
The latest version of the jsPsych CSS file seems to have an issue. The section that is commented out fixed an earlier issue with longer surveys not being rendered correctly in Firefox and possibly Safari.
![firefox](https://cloud.githubusercontent.com/assets/22083175/24674873/19508e7e-194b-11e7-809c-0e89495d884d.png)

Although this fixes the survey rendering issue, none of the text or images rendered using the single-stim or basic text plugins are horizontally centered. Uncommenting this centers images and text but brings back the survey issue.

Commented:
![firefox3](https://cloud.githubusercontent.com/assets/22083175/24675044/b43f7440-194b-11e7-916e-4db293ea7641.png)
![firefox4](https://cloud.githubusercontent.com/assets/22083175/24675015/994c3a1a-194b-11e7-9c64-7e9a435c8357.png)

Uncommented:
![firefox6](https://cloud.githubusercontent.com/assets/22083175/24675032/ab3dd436-194b-11e7-8557-09c8202d26f3.png)
![firefox5](https://cloud.githubusercontent.com/assets/22083175/24675028/a8460f50-194b-11e7-86ae-dc43bcee7cc0.png)
Note how you cannot scroll up.

With the uncommented CSS in chrome, both the images are centered and the surveys are not cut off, this issue is exclusive to firefox. Any suggestions on a fix?

**Comment by jodeleeuw** [comment]
I am trying to find a cross-browser solution that allows for centering by default. Clearly it's not quite there yet. Thanks for bringing this up.

**Comment by jodeleeuw** [comment]
I think this is now fixed.
