### ISSUE TITLE
jspsych-form styles and jquery dependencies

### ISSUE THREAD

**Issue by hugueslacroix** [jspsych/jsPsych#374]
I started using jspsych-form plugin and I find it very useful, however, it looks like there hasn’t been a lot of testing on it since the merge. 
So far, I noticed a few issues: 
- It doesn’t show properly if you load both the MDL CSS and jsPsych/css/jspsych.css. It seems the issue comes from  .jspsych-display-element,  .jspsych-content-wrapper and  .jspsych-content styles. 
- There are still a few lines with jQuery dependency: 
- There’s an issue when you preload something since there’s nothing in the plugin to update the MDL element when they are appended dynamically after the initial loading of the page. We could add this in the Form.prototype.render to solve the problem : 
```
// instead of setTimeout I should probably use a listener that I don’t know yet, any recommendation?  
    setTimeout(function(){
       componentHandler.upgradeDom();
     }, 1);
```

Should I try and fix it? What should I know about the future CSS development in jsPsych? 

#310

**Comment by jodeleeuw** [comment]
You are absolutely right that there has not been a lot of testing on it yet. If you are interested in fixing it, that'd be great. The goal is to make it compatible with the base jspsych.css file, remove jQuery dependencies, and fix any other outstanding issues. 

My goal for future CSS development is to get the flexbox stuff working consistently across browsers, and have all the basic elements minimally styled to a consistent simple look.

**Comment by hugueslacroix** [comment]
Ok, I'll try to fix and update the plugin. Removing jQuery dependencies should not be a big issue, it looks like most of the work have already been done. 

About the CSS, I'll try to understand how flexbox works and make the plugin work with the base jspsych.css, but it might take me a little while since I'm not that familiar with the flexbox.

**Comment by jodeleeuw** [comment]
@GavinQ1 can you take a look at this when you have some free time? I'd love to get this and #135 resolved.

**Comment by hugueslacroix** [comment]
I have been working quite a lot on jspsych-form plugin in my own branch, I changed and improved many things, but I'm not ready yet to send you a pull request (I have a short deadline to analyze my data now). If this can wait a little more, I'll offer a solution, however, if @GavinQ1 can have a look at the bug it might be solved more quickly.

**Comment by GavinQ1** [comment]
got it!
