### ISSUE TITLE
support required for Safari

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#376]
Safari doesn't apply `checkValidity` automatically like other browsers, and gives no notification if it fails. 

This code generates an alert in browsers that fail to give notifications. It can be adapted into the survey plugins.

```js
if(!trial_form.checkValidity() && (!trial_form.validationMessage || trial_form.validationMessage === null || trial_form.validationMessage === '')){ alert('Please answer all of the questions before submitting.'); return; }
```

**Comment by spencerking** [comment]
According to [https://caniuse.com/#search=required](https://caniuse.com/#search=required) this functionality is now supported in Safari. It is working as expected for me on 10.1.2.
