### ISSUE TITLE
jspsych-survey-multi-choice missing example

### ISSUE THREAD

**Issue by earcanal** [jspsych/jsPsych#381]
[jspsych-survey-multi-choice](http://docs.jspsych.org/plugins/jspsych-survey-multi-choice/) has a heading **Basic example with multiple questions on a page** but no example :(

Here's one:

```
var questions = {
  type: 'survey-multi-choice',
  data: {
    trial_id: 'questions'
  },
  questions: ['Do you want more life, Tucker?'],
  options: [ ['yes','no'] ],
  required: [true]
}
```
...
```
var experiment = [];
experiment.push(questions);
```

**Comment by jodeleeuw** [comment]
This will be fixed when the docs for version 6.0 are published. The updated docs file in the meantime is at:

https://github.com/jspsych/jsPsych/blob/master/docs/markdown_docs/plugins/jspsych-survey-multi-choice.md
