### ISSUE TITLE
jspsych-visual-search-circle.js TypeError: display_element.width is not a function

### ISSUE THREAD

**Issue by jtg567** [jspsych/jsPsych#393]
Line 120 of `jspsych-visual-search-circle.js` is throwing an error for me:
`TypeError: display_element.width is not a function`

Typing `display_element` at the console returns `<div id="jspsych-content" class="jspsych-content">` but only if I set a breakpoint to keep 120 from running - it is undefined if I check after the error is thrown.

Please advise - I've noted searching here and on the google group that the way display_element works has changed since the last release. [Here's my study in context, if it helps.](https://github.com/jtg567/braingames/blob/icon_vs_1/games/icon_vs_1/game.js)

**Comment by jodeleeuw** [comment]
This plugin needs a bit of an overhaul to work with the new version. I'm going to take a look at it now and see if I can get it fixed.

**Comment by jodeleeuw** [comment]
That was easier than expected. I just pushed a new version of the plugin that works, and removes the Snap library dependency.

**Comment by jtg567** [comment]
This is outstanding, Josh; thanks a lot!
