### ISSUE TITLE
callback function from screen presentations

### ISSUE THREAD

**Issue by teonbrooks** [jspsych/jsPsych#402]
Hey, we're looking to streamline the hardware integration now with LSL that allows for timesync on a local subnet. It is also a general way to deal with hardware. Is it possible to send a callback function from the builtin plug-in stimulus presentation (e.g. `jspsych-single-stim`) or would this require making a call via `jspsych-call-function` first?

cf. https://github.com/NeuroJS/eeg-stream-data-model/issues/1#issuecomment-310536236

**Comment by jodeleeuw** [comment]
There is currently an `on_trial_start` handler that can be set through `jsPsych.init`. This handler gets a copy of the trial object. So one approach could be to use the `data` parameter to define some kind of flag, check for the flag in `on_trial_start` and then send the trigger from there. It's not quite as precise, timing-wise, as modifying the plugins to only send the trigger when the stimulus write command happens, but the whole cycle might be fast enough that it doesn't matter.

Here's some untested code:

```javascript
var flag_trial = {
  type: 'single-stim',
  stimulus: 'img1.png',
  data: {flag: 'typeA'}
}

var noflag_trial = {
  type: 'single-stim',
  stimulus: 'img2.png'
}

jsPsych.init({
  timeline: [flag_trial, noflag_trial],
  on_trial_start: function(trial){
    if(typeof trial.data.flag != 'undefined'){
      // send message to hardware
    }
  }
});
```

**Comment by jodeleeuw** [comment]
I'm just learning more about LSL, and it looks really interesting. We could talk about a more direct integration with jsPsych, if you are interested.

**Comment by teonbrooks** [comment]
yeah, that would be great. cc: @marionleborgne. I will close the issue for now and follow up via email.
