### ISSUE TITLE
support video preloading using same methods as audio/images

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#408]
mainly so that it can smoothly integrate with the new preload progress bar (#384)

**Comment by jtg567** [comment]
idk if this would be helpful, but it seemed to work for me - this js runs just prior to my game.js that launches the experiment: https://github.com/mozilla/braingames/blob/master/games/shrub/static/js/preloadVideo.js

**Comment by jodeleeuw** [comment]
@jtg567 is that repo private now?

**Comment by jtg567** [comment]
Ah, shoot, I forgot about that. Apologies.

Seems like I took it all from http://dinbror.dk/blog/how-to-preload-entire-html5-video-before-play-solved/

**Comment by andytwoods** [comment]
I use https://createjs.com/preloadjs. Although kind of wishing I'd done it by hand as it's been a pain when upgrading.

**Comment by breslavya** [comment]
@jodeleeuw, do you maybe have any temporary code (even if not yet debugged) for integrating video upload with the progress bar? I thought to try and implement it myself, since I need to preload videos and it would be nice to have a progress bar, but if you have any partial implementation I could build on, that would be great

**Comment by jodeleeuw** [comment]
Not yet, sadly. If you make progress on this I would welcome a pull request to add it to the library.

**Comment by breslavya** [comment]
Thanks. so far I haven't gotten very far with the preloading, I just posted on the google group, maybe someone there has implemented something. I'll let you know if I make progress

**Comment by andytwoods** [comment]
I use https://createjs.com/preloadjs.

**Comment by andytwoods** [comment]
Option 4 here looks pretty doable (and minimal :) ) http://dinbror.dk/blog/how-to-preload-entire-html5-video-before-play-solved/

**Comment by jodeleeuw** [comment]
@andytwoods I like that option!

**Comment by andytwoods** [comment]
Let me know if I can help.

**Comment by jodeleeuw** [comment]
I think the preloading audio works well right now. I like the blob URL approach for video because it could be seamless from the user perspective and it can integrate with the approach for images and audio. 

Happy to accept a PR if you want to implement the video bit in `jspsych.js` 😄

**Comment by andytwoods** [comment]
It ok that  option 4 needs IE10+ ?

**Comment by jodeleeuw** [comment]
Yes. IE9 usage is down to less than half a percent. There may be other features that are not IE9 compatible already.

(It would be good to work on something like #19 to indicate when browsers can't run experiments, too.)

**Comment by andytwoods** [comment]
Entirely untested but something like this https://github.com/andytwoods/jsPsych/blob/master/jspsych.js
Will add some tests tomorrow.
PS I use this to block old browsers https://github.com/lancedikson/bowser

**Comment by breslavya** [comment]
Sorry for answering so late, different time zone. Thanks for the help! I initially looked at option 4 in the link above, and it seems to work partially (it preloads the first part of each video), but I couldn't manage to get it to work with the video plugin.  I'll try the code you added Andy - thanks! I currently block IE 8 and lower, but I'll change it to IE10 so the blob will work.

**Comment by andytwoods** [comment]
working https://github.com/andytwoods/jsPsych.
If you try out jspsyc-video.html in the examples, all looks good. 
Hesitant to pull-request as I've added no tests. Just exploring how hard it is to get Jest up and working.

**Comment by andytwoods** [comment]
npm test
that was easy! (using webstorm and it installed dependencies automagically it seems). All tests passing so I've not killed anything, surprisingly :)
Will pull-request.

**Comment by breslavya** [comment]
Works like a charm, thank you so much!
I wasn't able to get it to not preload videos (or choose which to preload), but for my purposes it's fine, since I always want to preload all videos.
I haven't tested what happens when there's more than one source, but it seems from the code it only preloads the first, right?
Josh, I'm not sure anything can be done about this, but as the progress bar shows the percent of items loaded, it's less indicative for movies. I don't know if it's possible to update it during loading, but if there is, it may be worth trying to change it in the future so it shows some progress during the loading of each movie.
Thanks again Andy, it's amazing that you whipped this so quickly! It's a great help

**Comment by andytwoods** [comment]
gosh, hard to know best way of excluding things from preloading. Needs to fit with jsPsych ethos. Perhaps an explicit 'exclude from preloading' array in init? @jodeleeuw ?

**Comment by jodeleeuw** [comment]
> Perhaps an explicit 'exclude from preloading' array in init?

I could see this working. Right now you could also disable automatic preloading and then manually provide the list of files to preload with `preload_audio` and `preload_images`. So I would want to be convinced that excluding is a needed shortcut. 

Did you add `preload_video` as an option in `jsPsych.init`? Haven't had time to look at the PR yet, but it is much appreciated!

**Comment by breslavya** [comment]
Sorry, I should clarify - I didn't mean a list to exclude. It seems that currently it preloads everything by default, even if I set preload_videos = [] or to include only a specific film, whereas for images and audio it doesn't seem to preload by default (only if requested).
