### ISSUE TITLE
Code Changes Not Loading

### ISSUE THREAD

**Issue by AlexAlb2** [jspsych/jsPsych#424]
Hi All

I created the code for my experiment. When I read the code, all changes are there but they don't upload onto my online experiment/changes don't show - I still see the old version. Can anyone help?

Thank you
Alex

**Comment by jodeleeuw** [comment]
This sounds like a cache issue. Try requesting a total refresh of the page. In Chrome the shortcut is Ctrl+shift+r. Other browsers have analogous commands but I don't know the shortcuts off the top of my head.
