### ISSUE TITLE
Last release on the release page from Jan 2016

### ISSUE THREAD

**Issue by mariansauter** [jspsych/jsPsych#445]
Hi, I just wanted to ask whether the master branch is stable enough to use or do I have to wait for a release? I just came back to jsPsych after 2 years. Looks very impressive :)

**Comment by jodeleeuw** [comment]
We're getting close on releasing a stable version 6.0 [(milestone progress here)](https://github.com/jspsych/jsPsych/milestone/9). The master branch is relatively stable, although I said that a few weeks ago and then we decided to overhaul almost all of the plugins. The code right now is passing all of the tests and should be good to use, but you may want to do an extra round of testing of the experiment just to be safe.
