### ISSUE TITLE
Left and right category fields seem to be displaying wrong text for iat-html plugin

### ISSUE THREAD

**Issue by jpellman** [jspsych/jsPsych#456]
When I replace the default category labels of "left" and "right" in the iat-html plugins, the screen displays the first and second characters in the string separated by newline + "or" + newline instead of the expected new labels of "Good" and "Satanic".

![satanicpizzas](https://user-images.githubusercontent.com/5000591/28757912-25c88ec4-755b-11e7-99b9-65ca4d21f971.png)

**Comment by jodeleeuw** [comment]
I think that we are treating those fields as arrays, but don't have a good way to input them yet. @GavinQ1

**Comment by jodeleeuw** [comment]
Moving to GUI issues [175](https://github.com/jspsych/jsPsych-Redux-GUI/issues/175)
