### ISSUE TITLE
Validation for category key in iat-html

### ISSUE THREAD

**Issue by jpellman** [jspsych/jsPsych#457]
Presently, you can set both of the category keys to be the same key in the iat-html plugin.  There should be some sort of warning to prevent users from doing this.

![doublea](https://user-images.githubusercontent.com/5000591/28757949-df217d2c-755b-11e7-9efc-54cde77ff05d.png)

**Comment by jodeleeuw** [comment]
Moving to GUI repository issues. [174](https://github.com/jspsych/jsPsych-Redux-GUI/issues/174)
