### ISSUE TITLE
required parameter for survey-text plugin (feature request)

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#460]
It would be great to have the option to make some survey-text responses required via an array of booleans, as in the survey-multi-choice plugin. I think this would mean adding the survey-text questions to a form with a submit button, where the input text/textarea elements for any required questions are assigned the 'required' attribute.

I'd be happy to contribute this when I switch to using the upcoming release (at the moment I'm working off an older jspsych version).

**Comment by becky-gilbert** [comment]
In case anyone is interested, I've created a 'survey-text-req' plugin that works with a slightly older version of the jsPsych master branch (from late June 2017).
https://github.com/becky-gilbert/jspsych-survey-text-req 
It allows you to specify required questions and give placeholder/default text. It also autofocuses the first text input area.
This would probably need further editing to work with the current branch, but I thought it might still be useful. (And as I said, I'm happy to make it work with the upcoming release once I switch to that version)

**Comment by amandasongmm** [comment]
Thank you so much for your contribution. I can make it work after commenting out the 
"trial = jsPsych.pluginAPI.evaluateFunctionParameters(trial);" line. It seems that evaluateFunctionParameters is not under pluginAPI in the latest version (6.0.5). And the codes can function without this line.

**Comment by jdzenk** [comment]
Hello, I'm new to jspsych and am struggling to make this work with version 6.0.5. @amandasongmm, I tried implementing the change you made, but think I must be missing something as the plugin still hasn't been able to work for me. I also added the .js file to my plugins folder. Is there anything else that needs to be done?
