### ISSUE TITLE
'undefined' next buttom of html-slider-response

### ISSUE THREAD

**Issue by uludewig** [jspsych/jsPsych#471]
Hi, 

I am using the html-slider-response. The default value of the next bottum seems to be 'undefined'. How can I manipulate the label of the next bottum? 

My set up is like this:
```
var nline = {
 type: 'html-slider-response',
prompt: '<p>...</p>',
stimulus: '<p>...</p>' , 
labels: ['0', '100']
```

**Comment by jodeleeuw** [comment]
You can change the label by adding a `button_label` parameter, e.g:

```js
var trial = {
  button_label; 'Next trial'
}
```

I also just made a change to the library to implement a proper default value for the buttons, so that you don't need to provide a label.
