### ISSUE TITLE
No stimulus saved in data for single-audio plugin

### ISSUE THREAD

**Issue by annguyen0212** [jspsych/jsPsych#473]
I've run through a couple of experiments using both single-stim and single-audio. For the experiments that use single-audio, the data file doesn't have a "stimulus" column.

**Comment by annguyen0212** [comment]
Figured out that just need to change "stimulus: trial.audio_path" to "stimulus: trial.stimulus" in the plugin source code would solve the problem

**Comment by jodeleeuw** [comment]
This is fixed in version 6.0 now, though the single-audio plugin has been replaced by a set of audio plugins.
