### ISSUE TITLE
Expfactory Version 2.0

### ISSUE THREAD

**Issue by vsoch** [jspsych/jsPsych#480]
hey @jodeleeuw ! I'm finishing up Expfactory version 2.0, which will deploy the original experiments (95 total of games, surveys, and jspsych!) in a reproducible container. E.g.,

```
docker run -p 80:80 vanessa/expfactory-experiments start
```

[full documentation here](https://expfactory.github.io/expfactory/). I want to make sure that I touched bases with you to see if there are any current experiment registries that I could make available for the containers, and further, a way to help make potential users aware of the resource to get proper feedback. I'm thinking of adding simple support for a few more databases, then reaching out to  a larger group of people that  (in the past) expressed interest in the closer of (version 1.0) of Expfactory. I wanted to get your feedback, and also hear about any update for JsPsych? It's still the driver of the huge majority of the experiments! Which is awesome :) Happy Friday and chat soon!

**Comment by jodeleeuw** [comment]
Hi @vsoch !

Sorry I am replying to this thread so late. I was focusing all of my jspsych time on version 6 and neglected this issue. I don't think I have any experiment registries to suggest at the moment. I am interested in thinking about how to integrate expfactory with the [gui](github.com/jspsych/jsPsych-Redux-GUI) that we are building. It would be great if people could deploy those experiments via expfactory. I'm still a docker novice so I don't quite understand what we would have to do to make that happen.

**Comment by vsoch** [comment]
hey @jodeleeuw ! If the gui has some kind of export feature (e.g., take this experiment I'm designing and output an `index.html` and folder of other dependencies) then adding a button to do that (and export a small metadata file for expactory) is all that would be needed. We would just write into the `index.html` to submit data to an endpoint called `/save` and then to `/next` when the response from the server returns. You wouldn't need to think about Docker or things like that.

**Comment by vsoch** [comment]
Maybe a good way to start would be to show me your favorite jspsych example experiment (produced from the GUI) and I'll fork it and tweak it to make it plug into expfactory? Then you could easily look at the diff to see the changes that I made, and we can figure out how to have them export?

**Comment by jodeleeuw** [comment]
Perfect. We already do pretty much exactly that, minus the metadata.

I don't have a good example experiment from the GUI quite yet, but hopefully in the next week or so I could do that.

**Comment by vsoch** [comment]
okay it's a plan! That's actually good for me too, I'm having a surgery on Thursday so I will need at least a week (after that) until I can act human again, lol. Ping me here when you have some time, and I'll be able to jump on it as soon as I'm able.
