### ISSUE TITLE
working example of audio-slider-response

### ISSUE THREAD

**Issue by napulen** [jspsych/jsPsych#481]
Hi, I have been trying to get a simple example of audio-slider-response using similar objects to those of image-slider-response. I can see the slider but no audio is playing. I am running this online, it worked before for single-audio. Could it be something with WebAudio?

**Comment by jodeleeuw** [comment]
The plugin had some bugs in it, but they are fixed now. There's a working example included in the `/examples` folder. Thanks for bringing this up!
