### ISSUE TITLE
Audio not playing in firefox

### ISSUE THREAD

**Issue by RobAWilkinson** [jspsych/jsPsych#496]
Currently experiencing a bug where audio files are not playing in both `audio-keyboard-response` and `audio-button-response`
A simple timeline like below
```js
    const calibration_audio = {
      type: 'audio-keyboard-response',
      stimulus: `audio/noise_calib_stim.wav`,
      choices: ['c'],
      response_ends_trial: true,
      prompt: '<p>Test</p>'
    };
```
Works fine in chrome, but getting the following error in FF 

`The buffer passed to decodeAudioData contains invalid content which cannot be decoded successfully.`

(tested on FF 60.0a1 (2018-01-26) (64-bit) and Chrome  63.0.3239.132)

**Comment by jodeleeuw** [comment]
Looks like it might be related to this:

https://stackoverflow.com/questions/26169678/why-certain-wav-files-cannot-be-decoded-in-firefox
