### ISSUE TITLE
CSS won't center

### ISSUE THREAD

**Issue by acsik** [jspsych/jsPsych#497]
Hey,
I am programming an experiment using jsPsych. I am working on adjusting the CSS for the text and am not able to get the text to center in the middle of the screen vertically. Even if I try to cheat and add paragraphs to get it to appear lower on the screen (instead of at the top), the program automatically scrolls down so the text is at the top. Do you know why that may be happening and how I can fix it? I have a task that uses the html-keyboard-response plugin to present one word on the screen at a time. 

Thanks!

**Comment by jodeleeuw** [comment]
Can you please provide a reproducible example, and include information and browser/OS?

Have you included the jspsych.css file?

**Comment by jodeleeuw** [comment]
I'm closing this. But happy to reopen if a reproducible example is added.
