### ISSUE TITLE
timeline_variables not working for audio

### ISSUE THREAD

**Issue by FalconTY** [jspsych/jsPsych#524]
Hi, anyone came across this before?  I was trying to put all the stimuli in a test_stimuli variable, it worked for the img but it did not work for the audio.  My code is as below:

<script>
var test_stimuli = [ { stimulus: "sound/speech_green.mp3"}, { stimulus: 'sound/speech_red.mp3'}, { stimulus: 'sound/speech_blue.mp3'}    
];
<br><br>
 var trial_1 = {
    type: 'audio-keyboard-response',
   choices: ['y', 'n'],
  }
<br><br>
   var test_procedure = {
      timeline: [trial_1],
     timeline_variables: test_stimuli,
      repetitions: 1,
      randomize_order: true
    } 
<br>	<br>
timeline.push(test_procedure);
  <br><br>
  jsPsych.init({
    timeline: timeline,
    use_webaudio: false,
    on_finish: function() {
      jsPsych.data.displayData();
    },
    default_iti: 250
  });
</script>

**Comment by jodeleeuw** [comment]
You'll need to preload the audio files using preload_audio in the jspsych.init call. This needs to be documented better or we need to make the preload algorithm able to detect audio in timeline variables, so I am going to leave this issue open to help track that.
