### ISSUE TITLE
How to get 'stimulus' from last trial

### ISSUE THREAD

**Issue by miallen** [jspsych/jsPsych#527]
Hi, i can get the response time and key press from the last trial like so:

		lasttrialdata_rt = jsPsych.data.getLastTrialData().select('rt');
		lasttrialdata_kp = jsPsych.data.getLastTrialData().select('key_press');
		resp_time = parseInt(lasttrialdata_rt.values, 10);
		key_press = parseInt(lasttrialdata_kp.values, 10);	

So that i can use them for various experimental logic. However, i'm randomizing trials and also need to know what the last stimulus was. Any ideas how to get the 'stimulus' html string from the last trial? 

I'm using the html-keyboard-response plugin.

**Comment by miallen** [comment]
Hi, the trial does save stimulus but i dont know how to extract information from .select('stimulus'). .select('stimulus') doesn't seem to output anything that is in an accessible and workable format..

Thanks for your reply

**Comment by jodeleeuw** [comment]
Check out the documentation here:
http://www.jspsych.org/core_library/jspsych-data/#datacolumn

I think what you will want is:
```
.select('stimulus').values[0]
```

**Comment by miallen** [comment]
Thank you, that works!
