### ISSUE TITLE
Make jsPsych usable as a module

### ISSUE THREAD

**Issue by RobAWilkinson** [jspsych/jsPsych#529]
In order to integrate better with complicated javascript projects, it would be great to allow jsPsych and it's plugins to be used via browserify or webpack.

As far as I see it there a few steps to this, but totally open to ideas

* [ ] Convert things to work via a umd build script
* [ ] update docs
* [ ] figure out long term plan for plugin usage.

Right now plugins don't actually export anything, they simply attach themseleves to a global jsPsych object, long term it might be handy to make plugins actually export something, so we can test plugin code in isolation, without interacting with the jsPsych global itself.

**Comment by jodeleeuw** [comment]
Figuring out the pattern for plugin use seems essential.

One possible approach would look like this:

```javascript
import htmlKeyboardResponse from "./plugins/jspsych-html-keyboard-response.js";

var trial = htmlKeyboardResponse.createTrial({
  stimulus: 'hello world',
  trial_duration: 1000
});

var timeline = [trial]
```

**Comment by jodeleeuw** [comment]
Another would preserve the current syntax for creating trials, but would presumably require users to attach the plugin to jsPsych, unless someone is aware of a design pattern that avoids this requirement?

```javascript
import htmlKeyboardResponse from "./plugins/jspsych-html-keyboard-response.js"

jsPsych.plugins.attach(htmlKeyboardResponse);

var trial = {
  type: 'html-keyboard-response',
  stimulus: 'hello world',
  trial_duration: 1000
}

var timeline = [trial];
```

**Comment by RobAWilkinson** [comment]
@jodeleeuw  I love the second one, the plugin would just need a top level `name` key.
```
function attach(plugin) {
  this.plugins[plugin.name] = plugin;
}
```

**Comment by jodeleeuw** [comment]
Great point. This also allows for:

```javascript
var trial = {
  type: htmlKeyboardResponse.name,
  /* .. */.
}
```

**Comment by QuentinRoy** [comment]
I do prefer the first approach. It is fortunately quite straightforward.

The plugin pattern is powerful (many lib uses it, e.g. [PouchDB](https://pouchdb.com)), but in my opinion it comes with a cost: it is really just about hiding a global variable. It forces developer to track down what plugins have been added and introduces hidden side-effects across modules.
For example, a good practice would be to add all need plugins a particular module needs, but failing it to do so may have no consequences if the plugin was already added somewhere else in the code.
To solve this, when using pouchdb I usually create a local `pouchdb` modules that patches pouchdb with all plugins I'm using in the project. Then in the entire project I am only importing pouchdb from this local module. But still makes it complicated to maintain, a plugin that isn't used anymore is easily forgotten (and hence uselessly bundled with the app).

**Comment by QuentinRoy** [comment]
What about something like this?

```js
import htmlKeyboardResponse from "./plugins/jspsych-html-keyboard-response.js"

var trial = {
  type: htmlKeyboardResponse
  stimulus: 'hello world',
  trial_duration: 1000
}

var timeline = [trial];
```

**Comment by jodeleeuw** [comment]
I like that approach a lot @QuentinRoy

**Comment by AaronZheng87** [comment]
How can I set the visual angle of images

**Comment by sjburwell** [comment]
Hello, my colleagues and I are just getting started with jsPsych (so far, very pleased!) and curious if there is a suggested repo or approach for integrating jsPsych within a React.js app? E.g., as an experiment page within a larger web app? We are aware of the unofficial / unsupported [openexp/jspsych-react](https://github.com/openexp/jspsych-react), but curious if there is an official, supported approach before we go digging into someone else's unsupported code circa 2019.

**Comment by jodeleeuw** [comment]
Hi @sjburwell,

We're a couple months away from releasing version 7.0 which will transition everything to importable modules. 

In the meantime -- and I realize this feels like a circa 2000 suggestion -- iframes can work pretty well in my experience. The jsPsych page can exist independently of the React code, and React can be used to render the right iframe content.

**Comment by sjburwell** [comment]
Sounds good @jodeleeuw, we'll look into using IFrames as a possible solution, but happy to hear that v7.0 will be importable as modules!

**Comment by jodeleeuw** [comment]
This was completed with #2183
