### ISSUE TITLE
Javascript code on remote page not executed in external-html plugin

### ISSUE THREAD

**Issue by onkeltom** [jspsych/jsPsych#532]
First, thanks for making jspsych. It is a great help for our projects here at Mozilla.

I noticed an issue with the external-html plugin as it does not execute <script> tags that are included in the remote html page. The problem is that scripts injected by innerHTML on [line 85](https://github.com/jspsych/jsPsych/blob/8678eed3049fca0baf6258c06dfc1312e91e1a59/plugins/jspsych-external-html.js#L85) are inactive.

One solution for this could be to relocate each `<script>` tag through DOM manipulation to activate their content. I suggest to control this via an additional executeScript parameter.

Parameter definition:
```javascript
// this code snippet needs to become a new parameter in plugin.info
executeScript: {
   type: jsPsych.plugins.parameterType.BOOL,
   pretty_name: 'Execute scripts',
   default: false,
   description: 'If true, executes scripts on the external html file.'
```

Then, on [line 69](https://github.com/jspsych/jsPsych/blob/8678eed3049fca0baf6258c06dfc1312e91e1a59/plugins/jspsych-external-html.js#L69) add the following code:
```javascript
// Scripts injected by innerHTML are inactive.
// To activate them, relocate them through DOM manipulation.
// Only run this if the executeScript parameter is set to true
if (trial.executeScript) {
   for (const scriptElement of display_element.getElementsByTagName("script")) {
   const relocatedScript = document.createElement("script");
   relocatedScript.text = scriptElement.text;
   scriptElement.parentNode.replaceChild(relocatedScript, scriptElement);
   }
}
```

Happy to turn this into a PR if you wish.

Thanks again,
Dominik

**Comment by jodeleeuw** [comment]
Thanks for diagnosing this! A PR would be great. I bet this also solves #332.

**Comment by onkeltom** [comment]
I agree that this will most likely also solve #332. In the pull request, I made the parameter to run scripts `false` by default.

I think that also documentation update is required.

**Comment by coyiutoc** [comment]
@onkeltom Was also running into this issue and added in your fix to the plugin - the good news is that I believe the script is being executed, but it has having issues detecting D3 methods as functions:

```
Uncaught TypeError: d3.select is not a function
    at <anonymous>:3:24
    at jspsych-external-html.js:84
    at XMLHttpRequest.xmlhttp.onload (jspsych-external-html.js:105)
```

Viewable in the repository [here](https://github.com/coyiutoc/VCLCorrelation_POC), where `index.html` calls the `d3_chart.html` via the external-html plugin. 

Not sure if this is because it is dependent on the external D3 script, and if additional loading would have to take place. Any insight would be appreciated! (And apologies in advance if the solution is otherwise trivial, am still new to front end development.)

**Comment by onkeltom** [comment]
@coyiutoc I have identified the problem.
You need to replace your variable name on [line 36](https://github.com/coyiutoc/VCLCorrelation_POC/blob/8cc4cc18146a3108f8f93d628644cd957f0ac968/index.html#L36) of your index.html file with another name. What is happening there is that you override the d3 properties that are loaded in the header globally with your variable.

Try changing it to something else. I can see the output here.

**Comment by coyiutoc** [comment]
@onkeltom 
Aha, awesome catch! Thank you so much! 
Really does help to have another set of eyes.
Many thanks once again!
