### ISSUE TITLE
In rare cases, extremely fast RTs in RT task

### ISSUE THREAD

**Issue by twiecki** [jspsych/jsPsych#542]
I'm running an effort task on mechanical turk that requires subjects to press a single key many times in quick succession. This works fine on 99% of participants, but some have many presses with very fast RTs (< 10 ms). One report from a worker stated that they just held down the key and it would send many presses. Is this a known problem?

**Comment by jodeleeuw** [comment]
Odd. `jsPsych.pluginAPI.getKeyboardResponse()` has an option `allow_held_keys` that is `false` in the standard set of plugins. It requires a key to be released before it can be registered as down again. This works, as far as I have been able to test. 

What plugin are you using for the task?

**Comment by twiecki** [comment]
Yeah, it is using `getKeyboardResponse()` with `allow_held_keys` to false. It is working, except for a few outliers. I think that some keyboards just send very quick key down and up responses if a key is held down. There is also software (auto keyboard) that subjects can use to cheat.
One idea is to block faster-than-humanly-possible key-presses.

**Comment by jodeleeuw** [comment]
Yeah, I suppose this could be an option in `jsPsych.init()`.

```js
jsPsych.init({
  timeline: [trial_1, trial_2],
  minimum_valid_rt: 50
})
```

Then `getKeyboardResponse()` could treat any response that is less than `minimum_valid_rt` as a "held key" and not register it.

**Comment by twiecki** [comment]
That would be perfect!

**Comment by andytwoods** [comment]
Hey Josh, 

here's a mod that allows this https://github.com/andytwoods/jsPsych/blob/min_RT/jspsych.js
BUT, I need help regarding getting init({minimum_valid_rt: 123}) into parameters here: module.getKeyboardResponse = function(parameters)

Waiting for child #2 to fall asleep, hence a spare mo for OS :)

**Comment by twiecki** [comment]
Thanks @andytwoods, want to submit a PR?

**Comment by andytwoods** [comment]
I need to figure out a non hacky way / jsPsych-ethos way to get default values from init into getKeyboardResponse . Josh will get back to us soon.

**Comment by jodeleeuw** [comment]
I haven't looked at your fork yet, but if you have the new parameter added to this list:

https://github.com/andytwoods/jsPsych/blob/min_RT/jspsych.js#L71-L101

Then you should be able to get its value with `jsPsych.initSettings().minimum_valid_rt`. ([Relevant function](https://github.com/andytwoods/jsPsych/blob/min_RT/jspsych.js#L281)).

**Comment by andytwoods** [comment]
Just pushed :) 
Just saw your comment Josh. Used that way :)
https://github.com/jspsych/jsPsych/pull/546

**Comment by jodeleeuw** [comment]
Closing to merge with #546
