### ISSUE TITLE
Improve webserver for saving data

### ISSUE THREAD

**Issue by 1kastner** [jspsych/jsPsych#549]
First of all thanks for sharing this great project! I love how simple it is made for us to write experiments with it! You describe a PHP webserver at https://www.jspsych.org/overview/data/ and I thought about maybe implementing a similar but a bit more secure webserver in Python. Could we add it in that section as well? Or make it a small separate project? Especially the first implementation without MySQL looks quite dangerous if misused.

Best wishes!

**Comment by jodeleeuw** [comment]
I'm happy to add alternate approaches to the documentation. I don't want to bundle a server with jsPsych, but would support a small separate project to provide an easy-to-use server. There's a half-baked node.js based server sitting in [this project](https://github.com/jspsych/jsPsych-socket-server).

**Comment by 1kastner** [comment]
After some thinking I came up with a very simplistic and general solution: CouchDB. And everything shipped with docker. I hope I will be able to publish my project soon and then I will add a link here, but the sketch goes like this:

#### docker-compose.yml
```
version: "3"
services:
    db:
      image: couchdb
      ports:
       - "5984:5984"
    nginx:
      build: nginx
      ports:
       - "80:80"
```

#### nginx Dockerfile
```
FROM nginx:alpine

COPY html/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
```

#### default.conf

```
server {
    listen 80;
	root /usr/share/nginx/html/;

	location /experiment-results {
		rewrite /experiment-results/(.*) /experiment-results/$1 break;
		proxy_pass http://docker-coachdb;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

So what it does is running two Docker containers, one with the database and one with the nginx server. The static files are hosted in ngninx and one database called experiment-results is also accessible. By now everything is quite open, no security, no users etc. - That could be changed if needed. But everything is only available to the localhost by default. And who of our colleagues or participants would be so mean and start to invoke rest calls on our database API or start to play around with Fouton, the GUI interface?
The results can later be picked up at Fouton at http://localhost:5984/_utils/#database/experiment-results/_all_docs and there is a cool API for that as well. That minimizes a lot of effort!

**Comment by 1kastner** [comment]
Now it runs, sample project available at https://github.com/1kastner/memory-test
