### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mjaquiery** [jspsych/jsPsych#554]
It'd be good to make the styling for plugins more flexible. I've started making my plugins apply a class with their name to each element they create, and adding a parameter for special_class_names which can take a list of additional classes which are likewise applied to all created elements.
This helps a lot when you want a slightly different look for two instances of a plugin. 
In case others want to use a similar approach, the code for the special_class_names is included:
```javascript
plugin.info.parameters.special_class_names = {
                type: jsPsych.plugins.parameterType.STRING,
                pretty_name: 'Special class name',
                default: [],
                array: true,
                description: 'Class names to be added to all elements created by this plugin. ' +
                    'This class can be used to differentiate different trials or uses of the pluging ' +
                    'for CSS styling purposes.'
}

...

let div = document.createElement('div');
        div.classList.add('jspsych-plugin-name');
        display_element.appendChild(div);

...

// Add the custom class to the elements created by this plugin
            if(trial.special_class_names !== []) {
                document.querySelectorAll('.jspsych-plugin-name').forEach(
                    (elm)=>{trial.special_class_names.forEach(
                        (myClass)=>{elm.classList.add(myClass)}
                    )}
                );
            }
```

This then allows me to call a plugin (e.g. written instructions) twice, and apply custom styling to each instance through assigning them different special_class_names parameters:

```css
div.jspsych-plugin-name.customClass1 {background-color: lightblue}
```

**Comment by jodeleeuw** [comment]
I think this use case is now covered by the [`css_classes` parameter](https://www.jspsych.org/7.1/overview/style/#using-the-css_classes-trial-parameter).
