### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by QuentinRoy** [jspsych/jsPsych#556]
npm became the standard package manager for the js community. It would be great to see jsPsych published there. It would greatly ease the development of web experiments making use of the npm ecosystem.

Most likely, it would require the library to make use of a [UMD wrapper](https://github.com/umdjs/umd).

**Comment by jodeleeuw** [comment]
This is in the long-term plan. Closing this since it duplicates #195. See also #529 for some discussion about how to approach this.
