### ISSUE TITLE
RDK plugin does not present next aperture when 'response_ends_trial: false' and a response is made

### ISSUE THREAD

**Issue by mkocsis2016** [jspsych/jsPsych#565]
(also reproducible by setting  'response_ends_trial: false' at line 42 in examples/jspych-RDK.html)
<!DOCTYPE html>
<html>
	<head>
		<script src="jspsych.js"></script>
		<script src="plugins/jspsych-RDK.js"></script>
        <script src="plugins/jspsych-html-keyboard-response.js"></script>
		<link rel="stylesheet" href="css/jspsych.css"></link>
	</head>
	<body></body>
	<script>

	/* 
	We would appreciate it if you cited this paper when you use the RDK: 
	Rajananda, S., Lau, H. & Odegaard, B., (2018). A Random-Dot Kinematogram for Web-Based Vision Research. Journal of Open Research Software. 6(1), p.6. DOI: [http://doi.org/10.5334/jors.194]
	*/
    
    /*
    //disable arrow key scrolling 
    window.addEventListener("keydown", function(e) {
        // space and arrow keys
        if([ 37, 38, 39, 40].indexOf(e.keyCode) > -1) {
            e.preventDefault();
        }
    }, false);
    */   

	//---------Create trials---------
		
		//Create an array of 2 different trials (different conditions)
		var RDK_conditions = [
			{//Condition 1
				correct_choice: 'a',
                //correct_choice: 37, //The correct answer for Condition 1
				coherent_direction: 180 //The coherent direction for Condition 1 (dots move left)
			},
			{//Condition 2
                correct_choice:'d',
				//correct_choice: 39, //The correct answer for Condition 2
                coherent_direction: 0 //The coherent direction for Condition 2 (dots move right)
			},
            {//Condition 3
				correct_choice:'w',
                //correct_choice: 38, //The correct answer for Condition 3
                coherent_direction: 90 //The coherent direction for Condition 3 (dots move up)
			},
			{//Condition 4
				correct_choice:'s',
                //correct_choice: 40, //The correct answer for Condition 4
				coherent_direction: 270 //The coherent direction for Condition 4 (dots move down)
			}
		];
		//console.log(RDK_trials)
        //IPI_task = jsPsych.randomization.shuffle(RDK_conditions)
        //console.log(RDK_trials)
        var short_IPI = jsPsych.randomization.sampleWithReplacement(RDK_conditions, 1);
        console.log(short_IPI)
        var long_IPI = jsPsych.randomization.sampleWithReplacement(RDK_conditions, 6);
        console.log(long_IPI)
        var IPI = 2
        
        if (IPI==1){
            IPI_task = short_IPI
        }
        else if (IPI==2){
            IPI_task = long_IPI
        };
        console.log(IPI_task);
		//The test block where all the trials are nested. The properties here will trickle down to all trials in the timeline unless they have their own properties defined   
		var RDK = {
			type: "RDK",
			timing_post_trial: 0, //The Inter Trial Interval. You can either have no ITI, or have an ITI but change the display element to be the same color as the stimuli background to prevent flashing between trials
			number_of_dots: 200, //Total number of dots in each aperture
			RDK_type: 6, //The type of RDK used
            opposite_coherence: 0.75,
            coherence: 0.25,
			choices:['w','a','s','d'],
            //choices: [37,38,39,40], //Choices available to be keyed in by 
            trial_duration: 5000, //Duration of each trial in ms
			timeline: IPI_task, //The timeline of all the trials
            response_ends_trial: false,
		};
        
        
         var fixation = {
          type: 'html-keyboard-response',
          stimulus: '<div style="font-size:60px;">+</div>',
          choices: jsPsych.NO_KEYS,
          trial_duration: 500,
          //data: {test_part: 'fixation'}
        };
    
        var RDK_trial = {
            timeline:[fixation,RDK]
        };
		//---------Run the experiment---------
		
		//Initiate the experiment
		jsPsych.init({
			timeline: [RDK_trial],
			on_finish: function(){ //Execute this when the experiment finishes
				jsPsych.data.displayData(); //Display the data onto the browser screen
			}
		});

	</script>
</html>

**Comment by mkocsis2016** [comment]
UPDATE - RDK plugin will keep moving along the timeline of apertures when response_end_trial: false and a response is made IF both 'choices : []' and 'correct_choice : []' for all coherence_directions in RDK timeline BUT response is logged as -1 regardless actual response - An issue with how data.correct is created?

**Comment by vrsivananda** [comment]
Thanks for alerting me to the bug. There was a logical error in the `after_response` function, so it should be fixed by placing the `clearTimeout` inside the `if(trial.response_ends_trial)` statement.

Here is the function to be replaced (**line 567**):

`               //Function to record the first response by the subject
		function after_response(info) {

			//If the response has not been recorded, record it
			if (response.key == -1) {
				response = info; //Replace the response object created above
			}

			//If the parameter is set such that the response ends the trial, then kill the timeout and end the trial
			if (trial.response_ends_trial) {
				window.clearTimeout(timeoutID);
				end_trial();
			}

		}; //End of after_response`

PS. I'll get back to you with the other issue you emailed me about.

**Comment by jodeleeuw** [comment]
Closing this as PR will handle it.
