### ISSUE TITLE
suggestion: RDK plugin does not write all parameters for every trial in timeline to trial data

### ISSUE THREAD

**Issue by mkocsis2016** [jspsych/jsPsych#568]
By default the RDK plugin writes a lot of parameters that may remain unchanged over each trial in the "timeline" parameter, thus saving a lot duplicate information + bloating the JSON. It would be convenient that if instead of the plugin rewriting all parameters by default to trial data for every trial in the timeline, that you could collapse static parameter entries across trials while being able to save any parameters of interest of individual trials (e.g., correctness of response on each). Alternatively you could set up the RDK plugin to save aggregate performance (e.g., RT, accuracy) across all trials in the timeline in a single data entry

**Comment by jodeleeuw** [comment]
There are methods available to filter the data (e.g., `jsPsych.data.get().ignore(...)`), and #561 is working on a generic method to filter data at the trial by trial level.

While each plugin can store whatever data it chooses to, the general strategy of the library is to try and store data in a tidy format whenever possible. This does result in some redundancy in the JSON, but also facilitates analysis with tools that expect tidy data.

(CC @vrsivananda)

**Comment by jodeleeuw** [comment]
Closing this, as #561 will handle it.
