### ISSUE TITLE
inconsistencies in RDK plugin documentation

### ISSUE THREAD

**Issue by mkocsis2016** [jspsych/jsPsych#569]
lines 54 and 39 in examples/jspsych-RDK.html refers to RDK plugin parameters not referenced in the RDK parameter list on the RDK page on the the JsPsych site. 

Specifically:

- "timing_post_trial" (for which the assigned value does not seem to matter - does not appear to be initialised as a parameter in the plugin). Note that this parameter is also referenced in the "Displaying a trial with 2 choices and 1 correct choice" example on the RDK page.

- "timeline" (which in the example html accepts an array of RDK trials defined via "correct_choice" + "coherence_direction" and appears to be work as intended).

**Comment by jodeleeuw** [comment]
These two parameters are generic jsPsych parameters and not specific to the RDK plugin. They are documented [here](https://www.jspsych.org/overview/timeline/#nested-timelines) and [here](https://www.jspsych.org/overview/trial/#inter-trial-interval).

The example uses the old jsPsych v5 parameter of `timing_post_trial`. This was replaced by `post_trial_gap` in v6. Renaming the parameter should make it do what is expected.

CC @vrsivananda

**Comment by vrsivananda** [comment]
Thanks @mkocsis2016  @jodeleeuw ! 
Fixed it in both the doc and example, and included in the pull request!

**Comment by jodeleeuw** [comment]
Closing this since the PR will take care of it.
