### ISSUE TITLE
html-slider-response forced slider click

### ISSUE THREAD

**Issue by joelem** [jspsych/jsPsych#573]
Hello, 

I was told to request the following here on Github:

The ability to require participants to at least click on the slider before they can continue. Right now, participants can move on without touching the slider, the data therefore only records the "start" value but we don't know whether that's what the participant wanted or if they're just clicking through.

You can see the original conversation here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jspsych/7msoq50VJH4/dWsYIdW-BQAJ

**Comment by jodeleeuw** [comment]
This is now implemented, and will be available in the 6.1 release. (Or go ahead and download the plugin file from the master branch now.)

```js
var trial = {
  type: 'html-slider-response',
  require_movement: true,
  // ... other params ...
}
```
