### ISSUE TITLE
Play back button for audio stimuli

### ISSUE THREAD

**Issue by SearaChen** [jspsych/jsPsych#595]
How can create a playback button for audio stimuli, there does not seem to be an option in the audio plug-ins ?

Use case: I want the subject to be able to replay the stimuli (an audio) as many times as they want.  

Thank you!

**Comment by jodeleeuw** [comment]
You could set up a looping timeline with the `audio-button-response` plugin so that whenever a repeat button is clicked the trial loops and the audio plays again.

```js
var repeat = {
  timeline: [{
    type: 'audio-button-response',
    stimulus: 'sound.mp3',
    choices: ['Play Again', 'Continue'],
  }],
  loop_function: function(data){
    if(data.values[0].button_pressed == 1){
      return true; // loop again!
    } else {
      return false; // continue
    }
  }
}
```
