### ISSUE TITLE
preloading progress bar grows out of screen

### ISSUE THREAD

**Issue by meowlz** [jspsych/jsPsych#603]
The preloading progress bar grows out of screen when preloading many items..see example here:
http://www.ibbmgroup.de/florian/mmg/

**Comment by meowlz** [comment]
I think the problem is here:
`    var total_n = images.length + audio.length;`

in my cases images is in array of two arrays each having 280 items. but images.length returns 2 because of the two arrays.

**Comment by meowlz** [comment]
so here is my naive fix to make it work for arrays:

`    var images_total_length = 0
    for (var i = 0; i < images.length; i++) {
      images_total_length += images[i].length
      console.log('adding to images total length: ' + images[i].length)
    }

    var audio_total_length = 0
    for (var i = 0; i < audio.length; i++) {
      audio_total_length += audio[i].length
      console.log('adding to audio total length: ' + audio[i].length)
    }


    var total_n = images_total_length + audio_total_length;`

**Comment by jodeleeuw** [comment]
Thanks for reporting this and diagnosing the issue. What's odd is that this used to work just fine, and I've only noticed the problem in recently created experiments. I want to check and make sure that there is not some deeper underlying issue that needs to be patched.

**Comment by jodeleeuw** [comment]
Hi @meowlz! If it's not too much trouble, could you try using the latest version of jspsych.js with your experiment and seeing if it solves the issue? Alternatively, if you can provide an example of the kind of code that caused the issue that would also be helpful.

**Comment by meowlz** [comment]
where can I find the release? latest release I see here is from October18?

I construct my stimuli like this:
``    // our stimulus
    var exams = ["last-acid-sample_crabby-sordid-revolution", "psychedelic-omniscient-data_real-normal-climate"]
    console.log(exams)

    // preloading
    var imagesT1 = []
    var imagesT1c = []
    var imagesT2 = []
    var imagesFla = []
    var images3dLeft = []
    var images3dFront = []
    var images3dBack = []
    var images3dRight = []


    for (var i = 0; i < exams.length; i++) {
        imagesT1.push('stimuli/' + exams[i] + '/png_slices/' + exams[i] + '_t1_slices.png');
        imagesT1c.push('stimuli/' + exams[i] + '/png_slices/' + exams[i] + '_t1c_slices.png');
        imagesT2.push('stimuli/' + exams[i] + '/png_slices/' + exams[i] + '_t2_slices.png');
        imagesFla.push('stimuli/' + exams[i] + '/png_slices/' + exams[i] + '_fla_slices.png');
        images3dLeft.push('stimuli/' + exams[i] + '/png_t1_3D_rendered/' + exams[i] + '_rota000.png');
        images3dFront.push('stimuli/' + exams[i] + '/png_t1_3D_rendered/' + exams[i] + '_rota090.png');
        images3dBack.push('stimuli/' + exams[i] + '/png_t1_3D_rendered/' + exams[i] + '_rota270.png');
        images3dRight.push('stimuli/' + exams[i] + '/png_t1_3D_rendered/' + exams[i] + '_rota180.png');

    }

**Comment by jodeleeuw** [comment]
You can grab the latest file here: https://github.com/jspsych/jsPsych/blob/master/jspsych.js.

This isn't part of a release yet.

**Comment by jodeleeuw** [comment]
I think this is fixed based on my testing, but please feel free to reopen if the latest version doesn't solve the issue.

**Comment by meowlz** [comment]
very cool, thank you! hope I will find time to try it soon!
