### ISSUE TITLE
Error of XMLHttpRequest

### ISSUE THREAD

**Issue by SearaChen** [jspsych/jsPsych#606]
When I launch an old html built with jspsych with chrome I am running into the following error, even though the script has worked fine before 
“jspsych.js:2198 Access to XMLHttpRequest at 'file:///Users/Seara/Desktop/prototype_experiment/mp3s/CelineDion1.mp3' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
load_audio_file_webaudio @ jspsych.js:2198”

I have never encountered this error before, and the bug seem to be coming from jsPsych. Do you have any idea as to why is this happening?

**Comment by jodeleeuw** [comment]
This is a security feature of web browsers. If you run the experiment on a web server the problem will be solved. You can also [disable the security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) for local testing.
