### ISSUE TITLE
allow custom names for survey data key IDs

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#608]
Allow customization of key names in the JSON responses object.

For example, instead of
```js
{
  Q0: 1,
  Q1: 5
}
```

allow
```js
{
  DifficultyRating: 1,
  Confidence: 5
}
```

**Comment by retowyss** [comment]
DId you already start on this one?

**Comment by jodeleeuw** [comment]
No not yet. Feel free!
