### ISSUE TITLE
jspsych-external-html example code has dependency on jQuery

### ISSUE THREAD

**Issue by yinghj** [jspsych/jsPsych#624]
https://www.jspsych.org/plugins/jspsych-external-html/
```
  if ($('#consent_checkbox').is(':checked')) {
    return true;
  }
```
`$` is unrecognizable without jQuery dependency. Will throw `"Uncaught Reference Error: $ is not defined"`.

**Comment by jodeleeuw** [comment]
thanks for reporting this!

**Comment by jodeleeuw** [comment]
This is fixed in the repository and will go live once the docs for 6.1 are published.

**Comment by jodeleeuw** [comment]
For reference, the solution is:

```js
if (document.getElementById('consent_checkbox').checked) {
  return true;
}
```

**Comment by NanChen5353** [comment]
so just wondering if jspsych and jQuery can be used in the same script? when I try to implment jQuery, it seems that it cannot identify $

**Comment by jodeleeuw** [comment]
Yes it should be possible to use both.
