### ISSUE TITLE
standardize the response variable in the data

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#638]
Instead of having different columns like `key_press`, `button_pressed`, and `response`, normalize these names to `response`.

**Comment by becky-gilbert** [comment]
Data variable names need to be checked/changed in the following places:

- [ ] all plugin files (jsPsych/plugins)
- [ ] test.js files (jsPsych/tests)
- [ ] example files  (jsPsych/examples)

And in the following documentation pages:

- [ ] https://www.jspsych.org/tutorials/rt-task/
- [ ] https://www.jspsych.org/overview/timeline/#looping-timelines
- [ ] https://www.jspsych.org/overview/timeline/#conditional-timelines
- [ ] https://www.jspsych.org/overview/trial/#the-on_finish-event
- [ ] https://www.jspsych.org/overview/trial/#dynamic-parameters
- [ ] https://www.jspsych.org/overview/data/#adding-data-to-a-particular-trial-or-set-of-trials
- [ ] https://www.jspsych.org/overview/callbacks/#on_finish-trial
- [ ] https://www.jspsych.org/plugins/overview/#data-collected-by-plugins
- [ ] all plugin docs

@jodeleeuw if a plugin collects multiple responses, should this be called `responses` or `response` in the data?

**Comment by jodeleeuw** [comment]
Let's call everything `response` so there's always one column regardless of which plugins are used.

**Comment by becky-gilbert** [comment]
The following data properties have been renamed to `response` in v6.3:
- `animation`: `responses`
- `audio-button-response`: `button_pressed`
- `audio-keyboard-response`: `key_press`
- `canvas-button-response`: `button_pressed`
- `canvas-keyboard-response`: `key_press`
- `categorize-animation`: `key_press`
- `categorize-html`: `key_press`
- `categorize-image`: `key_press`
- `cloze`: `answers`
- `html-button-response`: `button_pressed`
- `html-keyboard-response`: `key_press`
- `iat-html`: `key_press`
- `iat-image`: `key_press`
- `image-button-response`: `button_pressed`
- `image-keyboard-response`: `key_press`
- `maxdiff`: `left` and `right` now stored in `response` object with `left` and `right` keys
- `rdk`: `key_press`
- `same-different-html`: `key_press`, and `key_press_stim1` renamed `response_stim1`
- `same-different-image`: `key_press`, and `key_press_stim1` renamed `response_stim1`
- `serial-reaction-time`: `key_press`
- `serial-reaction-time-mouse`: `response_row` and `response_column` now stored in `response` array as `[row,col]`
- `survey-html-form`: `responses`
- `survey-likert`: `responses`
- `survey-multi-choice`: `responses`
- `survey-multi-select`: `responses`
- `survey-text`: `responses`
- `video-button-response`: `button_pressed`
- `video-keyboard-response`: `key_press`
- `visual-search-circle`: `key_press`
- `vsl-animate-occlusion`: `responses`
