### ISSUE TITLE
`on_load` doesn't mean that the content is ready for display

### ISSUE THREAD

**Issue by stefanuddenberg** [jspsych/jsPsych#639]
Trying to manipulate DOM elements via a trial's `on_load` function fails since they have not yet been mounted to the DOM; how can one await the actual loading of the trial such that it's visible to the browser? This is especially apparent in the context of the `external-html` plugin, where I've had to put my DOM manipulation code in a `setTimeout` within `on_load`.

**Comment by jodeleeuw** [comment]
I think on_load will be reliable for any synchronous code, but async loads of DOM elements will cause this issue. Thanks for pointing this out. 

I'm not sure there is an easy fix, but the on_load event could be rewritten to be manually triggered by each plugin, or at least provide the option for plugins that rely on async calls. Another option might be some kind of Promise interface.

**Comment by stefanuddenberg** [comment]
Another option would preloading the external HTML pages, a la preloading images or audio; not sure what that would take to implement though...

**Comment by stefanuddenberg** [comment]
For now I've solved this by adding an on `on_complete_callbacks` property to my customized version of the `external-html` plugin; those functions then get called within the plugin's `load` function's callback.
