### ISSUE TITLE
Need a "jspsych-contrib" repo

### ISSUE THREAD

**Issue by jcpeterson** [jspsych/jsPsych#640]
Taking repos like `keras-contrib` ([link](https://github.com/keras-team/keras-contrib)) etc as inspiration. The current plugin list includes plenty of fairly specific experiments that would be a better fit in a plugins repo, and there are likely many community plugins that either need a bit of work or are extremely specific that could go here.

@stefanuddenberg

**Comment by stefanuddenberg** [comment]
E.g., I have a really simple plugin for rendering Mustache templates that I'd like to share with the world, but it may not be useful (or battle-tested) enough for inclusion in the main jsPsych repo.

**Comment by jodeleeuw** [comment]
Great suggestion. I'll work out something along these lines.

**Comment by jcpeterson** [comment]
I noticed the repo here: https://github.com/jspsych/jsPsych-plugin-contrib

Can we start sending pull requests? Do you have any organization / formatting guildlines?

**Comment by jodeleeuw** [comment]
Picking up on thread from https://github.com/jspsych/jsPsych/pull/2078.

My understanding of the purpose of a `jspsych-contrib` repo is that it's a place with a low barrier to sharing potentially useful contributions. With that in mind, I'd love to make it so that `jspsych-contrib` doesn't *require* the full build toolkit to contribute. For example, say someone creates a usable plugin by following the template produced by the `.browser.js` version of a plugin file and that's as far as they are comfortable going. Can we set up a way that this could be added to the repo alongside someone who creates a full package?

**Comment by bjoluc** [comment]
@jodeleeuw That's a good point. We could have a build setup available for both options in `@jspsych/config`, and two templates in `jspsych-contrib`:
* A TS template – something like currently in `packages/plugin-template`
* A plain JS template that adheres to the same format as our `index.browser.js` builds currently do – ES6 IIFE with `jsPsychModule` dependency. That would require a Rollup config for babel and terser only then. The problem that I see here is testing: Configuring Jest for that may be possible, but can easily become a little nightmare :see_no_evil: 

Another option for the second template that just came into my mind: If we discard the IIFE part and offer a plain JS setup, that would be way easier while still very convenient for plugin authors: No TS, just the same ES6 class as in `index.browser.js`, with the only few differences being:
* No IIFE function that wraps everything
* `ParameterType` is imported from `jspsych`
* The plugin class is exported in the end. 
We would gain perfect plain-js Jest testability and only a slight modification of the build chain would be necessary.
Oh, and there I see the con: Users would have to install Node.js, run `npm install` and `npm run build`. And then moving to TS would not even be that much of a difference.

Ok, so I guess we should use said ES6 IIFE solution and not offer Jest support. If someone is ready to use Jest (=has Node.js installed and is ready for a little bit of extra complexity), they may as well just copy their code into the TS template and use our TS tooling. There are examples enough in this Repo after all, including Jest tests for plugins.

**Comment by jodeleeuw** [comment]
> Ok, so I guess we should use said ES6 IIFE solution and not offer Jest support.

Yeah I think I agree here. My primary goal is to allow for a contribution that doesn't rely on Node.js or `npm install`. I don't think contributions in `jspsych-contrib` need a testing file, though it would certainly be nice if someone provides one.

**Comment by bjoluc** [comment]
Alright! You can either setup `jspsych-contrib` yourself and grant me permissions, or temporarily add me to @jspsych and I'll do it. Also, would you like to rename [this repo](https://github.com/jspsych/jsPsych-plugin-contrib) or create a new one?

**Comment by jodeleeuw** [comment]
Should have an invite for admin rights here: https://github.com/jspsych/jspsych-contrib

**Comment by bjoluc** [comment]
@jodeleeuw @becky-gilbert The technical setup is ready at https://github.com/jspsych/jspsych-contrib! There are two template plugin packages now, `plugin-template` for our full tooling and `plugin-template-plain` for the bare-bones JS solution. Feel free to check these out and test the setup locally! For now, `jspsych` and `@jspsych/config` are installed straight from the core repo (using gitpkg), but we should obviously change that once the packages have been published. Oh, and I guess we should rename the templates to `plugin-template-ts` and `plugin-template`, respectively, right?

**Comment by bjoluc** [comment]
[jspsych-contrib](https://github.com/jspsych/jspsych-contrib) is ready now and welcoming contributions (ideally plugins/extensions for jsPsych v7, but v6 is also fine)!
