### ISSUE TITLE
video-keyboard-response doesn't play .MOV files

### ISSUE THREAD

**Issue by mahathu** [jspsych/jsPsych#649]
The video-keyboard-response plugin currently creates html similar to this:
`<div><video id="jspsych-video-keyboard-response-stimulus" autoplay=""><source src="ressources/name.mov" type="video/mov"></video></div>`

This doesn't work in some browsers, and no video is shown. A potential fix for this issue is to update `type="video/mov"` to `type="video/mp4"`.

**Comment by jodeleeuw** [comment]
I'm worried about specifying the type as `mp4` for a .mov file. Any idea why this works?

**Comment by mahathu** [comment]
Alas I'm not too sure either. According to MDN, mov files aren't supported in the HTML5 video tag:
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

I think specifying the type as `mp4` works because both file types are just containers for MPEG-4 compressed data, mp4 being the more commonly used one: https://en.wikipedia.org/wiki/QuickTime_File_Format#Relation_to_MP4
Thank you for looking into this.

**Comment by becky-gilbert** [comment]
It does look like .mov files use the same MPEG-4 format as .mp4, so maybe it's fine to use `type="video/mp4"`. Although this MDN page says that `"video/quicktime"` should be used as the MIME type: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#QuickTime Any idea if that also works? I don't have a Mac to test on right now.

**Comment by becky-gilbert** [comment]
I made a demo on cogniton.run that plays a .mov video using the source type `video/mp4`: https://sed5hj8ulk.cognition.run When I run this in Windows Chrome, it plays the audio but not the video. 

I also made the same demo using the `video/quicktime` source type: https://bqlfjlqjmt.cognition.run In this case, it doesn't work at all on Windows Chrome - I get a video player that doesn't play anything. 

Of course, it may not matter if the method for handling .mov movies doesn't work in Windows Chrome, e.g. if the researcher is only planning to test on Apple devices, or if they're providing a backup video file format in the sources parameter.

However, when I tried running both versions in Safari on an old iPad (iOS 9), the experiment doesn't load in either case. Unfortunately I don't have a way of debugging this, and I don't have any other Apple devices to test on. Could someone else test these links using a newer iOS/MacOS device? If someone can verify that using either `video/mp4` or `video/quicktime` works in at least some versions of Safari, then it might be worth changing this in the video plugins.

**Comment by jodeleeuw** [comment]
I think for 6.2 we could add a `console.warn` about .mov files and update the docs. We can wait for more robust testing before making major changes.

**Comment by jodeleeuw** [comment]
After reading about this a little more, I don't think it makes sense for us to offer partial support for `.mov` files. It looks like cross-platform adoption is too low. It's probably  a better experience for researchers to warn them about using `.mov` than to partially support it.
