### ISSUE TITLE
move back/forward between survey pages

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#652]
It would be great to be able to set up successive survey-type trials/pages so that the participant can move backwards and forwards freely between them (via back/next nav buttons, like the instructions plugin). 

I don't think there's any way to do this without modifying the survey-* plugins. Here are the two options I can think of:

1. Modify the plugins so that they can take multiple pages of questions and handle the navigation between them (like the instructions plugin). Although this would mean that the navigation would only be possible between pages of the same survey trial type.

2.  Create some kind of 'navigation' timeline object that automatically handles the back/next progression in a given timeline (@jodeleeuw I think this is what you suggested in the google group?). This seems like a more general solution and would allow navigation across a set of different trial/question types. This option would still require modification to the survey-* plugins, but I think it would just involve adding the option to show a back button on the page, with parameters like 'show_previous_button' and 'button_label_previous'. I think the core jsPsych code would have to be modified to handle progression through the timeline based on back/next button responses. 

Would you want to include something like this in the library? If so, I'm happy to work on it. If you want to go for option 2 then could use some guidance/suggestions WRT implementation. 

BTW, in case anyone is interested: I'm currently working around this issue by using the survey-html-form plugin in a loop, with an array to hold the HTML string for each page, and dynamic parameters to change the HTML based on whether the 'next' or 'back' button was pressed. I think the main problem with this solution is that the HTML strings quickly become unwieldy and it's especially difficult for beginners to work with.

**Comment by matanmazor** [comment]
This would be a great feature to have!

**Comment by jodeleeuw** [comment]
This is implemented in the survey plugin, so I'm closing this.
