### ISSUE TITLE
Some way to tag trials with info based on randomization in stimulus handler function (data.write() would be ideal, addProperty() isn't good enough)

### ISSUE THREAD

**Issue by bbiney1** [jspsych/jsPsych#656]
If I could get the behavior of data.addProperties() without it overwriting the data on every single trial object before and after it, that would be ideal.

Consider the following variable I have for my experiment's testing phase.

```   var test_procedure = {
    timeline: [
        {
            type: 'html-keyboard-response',
            stimulus: function() {
              //jsPsych.data.write({fixation_cross_trial : true});
              jsPsych.data.addProperties({fixation_cross_trial : true});
              return '<div style="font-size:60px;">+</div>'
            }, 
            choices: jsPsych.NO_KEYS,
            trial_duration: 2000,
        },
        {
            type: 'html-keyboard-response',
            stimulus: function(){
               var myArray = [true, false]; 
              var rand = myArray[Math.floor(Math.random() * myArray.length)];
              // jsPsych.data.write({trial_stimuli_path:jsPsych.timelineVariable('image_path', true)});
              // jsPsych.data.write({fixation_cross_trial : false});
              jsPsych.data.addProperties({trial_stimuli_path:jsPsych.timelineVariable('image_path', true)});
              jsPsych.data.addProperties({fixation_cross_trial : false});
              if (rand == true) {
                // write's to this ccurrent trial object 
                //jsPsych.data.write({treatment_display : "left"});
                jsPsych.data.addProperties({treatment_display : "left"});
                return "<div style='float: left; '><img src=" + "'" +  jsPsych.timelineVariable('image_path', true) + "'" + "></img></div>" + "<div style='float: right; font-size:60px; color: grey'>No Treatment</div>" 
              } else {
                //jsPsych.data.write({treatment_display : "right"});
                jsPsych.data.addProperties({treatment_display : "right"});
                return "<div style='float: left; font-size:60px; color: grey'>No Treatment</div>" + "<div style='float: right; '><img src=" + "'" +  jsPsych.timelineVariable('image_path', true) + "'" + "></img></div>" 
                 }
              },          
            choices: [37, 39], //37 -- keycode for left arrow, 39 -- keycode for right arrow
        }
    ],
    timeline_variables: test_tl_stimuli // an array of image paths
}
```

In this experiment, there is a fixation cross trial that executes first. Then there is the actual test_stimuli trial, where an image is displayed side by side with a string that says "No Effect". These are the two main stimuli I have throughout the experiment for each trial. For each trial, the appearance of either stimuli on the right or left is supposed to be random - this is critical to the "reaction time" dimension of our experiment.

In the code, I tried initially using jsPsych.data.write(), I didn't read that one part of the documentation discouraging you from using it. The intention was to make it so that each trial could hold a new key object pair from every `jsPsych.data.write()` call. As you can see, I'm the things I'm trying to write into the trial are dynamic and based on things that happen in the handler function I've created for my stimulus. 

- I have a write call to give a key/value pair, `trial_stimuli_path`. This holds the timelineVariable() that is loaded for that particular trial, or the image path that I'm trying to access on each specific trial.
- I have a write call to give a key/value pair, `fixation_cross`, which holds a boolean for whether or not the current trial is a fixation cross trial. Ultimately, I don't need the fixation cross trials. 
- I have a write call that's supposed to give a key/value pair, `treatment_display`, which is supposed to indicate whether or not the randomization within my stimulus function chooses to put the timeline variable image on the left or right (or, indicates the opposite side from which the "No Treatment" string appears.

In my jspsych.init() function, I was finding that executing jspsych.data.displaydata('json') looks strange if you use `jsPsych.data.write()`. It appears that a new dictionary object/JSON object is created every time you use `jsPsych.data.write()`, and this object has almost entirely identical fields to other trial json objects (but it does include the field that you tried to write).

So here's the output for what should be two trials, a fixation cross trial and then a test_stimuli trial. But as you can see, it makes 6 json objects.

```
{
		"fixation_cross_trial": true,
		"trial_type": "html-keyboard-response",
		"trial_index": 6,
		"time_elapsed": 3826,
		"internal_node_id": "0.0-6.0-0.0",
		"user_id": "6DLz56Gl",
		"condition": "Mood",
		"total_trials": 2
	},
	{
		"rt": null,
		"stimulus": "<div style=\"font-size:60px;\">+</div>",
		"key_press": null,
		"trial_type": "html-keyboard-response",
		"trial_index": 6,
		"time_elapsed": 5827,
		"internal_node_id": "0.0-6.0-0.0",
		"user_id": "6DLz56Gl",
		"condition": "Mood",
		"total_trials": 2
	},
	{
		"trial_stimuli_path": "/static/images/stimulus_img1.png",
		"trial_type": "html-keyboard-response",
		"trial_index": 7,
		"time_elapsed": 5828,
		"internal_node_id": "0.0-6.0-1.0",
		"user_id": "6DLz56Gl",
		"condition": "Mood",
		"total_trials": 2
	},
	{
		"fixation_cross_trial": false,
		"trial_type": "html-keyboard-response",
		"trial_index": 7,
		"time_elapsed": 5828,
		"internal_node_id": "0.0-6.0-1.0",
		"user_id": "6DLz56Gl",
		"condition": "Mood",
		"total_trials": 2
	},
	{
		"treatment_display": "right",
		"trial_type": "html-keyboard-response",
		"trial_index": 7,
		"time_elapsed": 5828,
		"internal_node_id": "0.0-6.0-1.0",
		"user_id": "6DLz56Gl",
		"condition": "Mood",
		"total_trials": 2
	},
	{
		"rt": 1539.229999994859,
		"stimulus": "<div style='float: left; font-size:60px; color: grey'>No Treatment</div><div style='float: right; '><img src='/static/images/stimulus_img1.png'></img></div>",
		"key_press": 37,
		"trial_type": "html-keyboard-response",
		"trial_index": 7,
		"time_elapsed": 7368,
		"internal_node_id": "0.0-6.0-1.0",
		"user_id": "6DLz56Gl",
		"condition": "Mood",
		"total_trials": 2
	},
```

If I use `data.addproperties()` instead, then while I get one json object to represent each fixation trial and each test trial... Each call to data.addproperties overwrites the previous data.addproperties() calls all the way through the end of the experiment. 

Is there a way to work around the limitations of addProperty() so that I can get something similar to data.write() that doesn't cause this strange behavior in the data? I can imagine myself making a python script to parse the JSON file correctly when I use `data.write()` (this experiment is on a flask application), but that's a lot of trouble just to get what I originally intended to be trial-by-trial tags.

**Comment by jodeleeuw** [comment]
Does the [data property for trial objects](https://www.jspsych.org/overview/trial/#the-data-parameter) do what you need, or is there some feature that is missing from that? You can use functions as values for the data property.

You can also modify the data object after each trial in the [on finish event](https://www.jspsych.org/overview/trial/#the-on_finish-event) for that trial.
