### ISSUE TITLE
[jsPsych5] need to use nlocks generated and saved in previous trial's data to inform later trial

### ISSUE THREAD

**Issue by henrymj** [jspsych/jsPsych#657]
Hello,

In a previous task, I was able to do the following:
var trial = {
...,
  **stimulus**: function() { //use scan_order and stimPop (an iterator) to get correct stimulus from stim_index array
    var scan_order = jsPsych.data.getDataByTrialIndex(0).scanner_order;
    var index = stim_index[scan_order][stimPop()];
    _return ('<div class = dd-stim><div class = amtbox style = "color:white">$'+options.large_amt[index]+'</div><br><br>'+
    '<div class = delbox style = "color:white">'+ options.later_del[index]+' days</div></div>');_
  },
...
}

And that worked fine. 

however, in a different task I am trying the following:

block = {
...,
		**timeline**: function() {
			var test_blocks = jsPsych.data.getDataByTrialIndex(1).blocks;
			_return test_blocks;_
		},
...
}

this gives me the error that  jsPsych.data.getDataByTrialIndex(1) is undefined. However, when I call that same line in the command line, it shows the proper value for test_blocks. What is happening? How can I get this function to evaluate correctly? Thank you for all of your help.

**Comment by jodeleeuw** [comment]
I think the problem here is that you can't use a function as the value for
the timeline parameter. Timelines have to be set at the start of the
experiment, or you can use the addNodeToEndOfTimeline function.

**Comment by henrymj** [comment]
Thank you! This was very helpful.
