### ISSUE TITLE
callback not optional on jsPsych.addNodeToEndOfTimeline function

### ISSUE THREAD

**Issue by oliveralonzo** [jspsych/jsPsych#688]
I'm trying to call the jsPsych.addNodeToEndOfTimeline just passing a node, but I get this errror: TypeError: callback is not a function. (In 'callback()', 'callback' is undefined).

**Comment by vijaygopal1234** [comment]
That looks like a bug oliveralonzo, use an empty function for now. E.g.,

```javascript
jsPsych.addNodeToEndOfTimeline({...}, function(){})
```

**Comment by becky-gilbert** [comment]
@jodeleeuw should I write a test for this?

**Comment by jodeleeuw** [comment]
Yeah, that'd be great

**Comment by becky-gilbert** [comment]
Before closing:
- [ ] write tests for jsPsych.addNodeToEndOfTimeline with and without optional callback function
