### ISSUE TITLE
image-slider-response doesn't log stimulus

### ISSUE THREAD

**Issue by jcpeterson** [jspsych/jsPsych#689]
Looks like it's not included in `trialdata` so it never makes it into the final data dump

**Comment by kupiqu** [comment]
Setting this by hand works (I guess this is obvious for experienced jsPsych people, but wanted to share this for new users).

**Comment by jcpeterson** [comment]
"Setting this by hand works" --> what does this entail exactly? Currently I manually add it to the data of each trial. I've used jspysch a fair amount and developed a number of plugins, but have never seen this behavior. Without this as a default, the plugin simply cannot be used in a real experiment.

**Comment by kupiqu** [comment]
> "Setting this by hand works" --> what does this entail exactly? Currently I manually add it to the data of each trial. I've used jspysch a fair amount and developed a number of plugins, but have never seen this behavior. Without this as a default, the plugin simply cannot be used in a real experiment.

I see what you mean. I think this should be considered a bug.

For me things are a bit better. I use jaysire (R package to build jsPsych experiments; the link to the jaysire issue appears above). jaysire workarounds this issue quite elegantly by simply adding:

```R
data = insert_property(
    stimulus = insert_variable(name = "variable_name")
  )
```

where `variable_name` represents an array in R specifying the proper stimulus in each trial

Unfortunately doing this directly in jsPsych requires changing every condition by hand, which is a pain.

**Comment by jodeleeuw** [comment]
Will fix this in the next release

**Comment by kupiqu** [comment]
I submitted pull request #736 that fixes this issue
