### ISSUE TITLE
How to import audio stimuli from .csv file?

### ISSUE THREAD

**Issue by Cbenaa** [jspsych/jsPsych#693]
Hello!
So I have two experiments, one with 80 main trials (audio identification task) and one with 152 main trials (audio rating task). Now I know that I can put them in using the regular method but that would take a super long time, is there anyway I could import them through a .csv file and if yes, how would one go about that?

Thanks!

**Comment by vijaygopal1234** [comment]
You can use a tool like https://csvjson.com/csv2json to convert your CSV file to a JSON representation. You can then copy the JSON string to your Javascript file.

**Comment by Cbenaa** [comment]
Is there a particular code to use when copy-pasting it or?

**Comment by vijaygopal1234** [comment]
JSON is essentially Javascript code. In the code below, you can paste the JSON where `!!!` is and you can now access your data as a list of objects, one for each row. Each key in those objects is a column name and value is the value for the row.

```javascript
var stimuli = !!!
```
