### ISSUE TITLE
Allow for less intrusive slider "require movement" behavior?

### ISSUE THREAD

**Issue by kupiqu** [jspsych/jsPsych#696]
Require movement in slider is great to avoid accidental/lazy clicks of the `Continue` button, however it is (arguably) more intrusive than it may need to be, especially when using discrete slider positions.

For instance if allowed positions are `[-5 ... 0 ... +5]` and assuming original location is set at `0`, selecting `0` requires:

1. moving the slider cursor elsewhere
2. releasing the cursor
3. grabing it again
4. and selecting back `0` again

It would be great if instead the `Continue` button would just be enabled by clicking on the slider cursor.

If that would not suffice because of some other use case I am not aware of, could we at least remove points 2. and 3. above?

**Comment by jodeleeuw** [comment]
I'm in favor of this change. I'm adding it to the next minor release milestone.
