### ISSUE TITLE
non-zero video start time causes video to jump in Firefox

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#712]
With the video plugins in Firefox, when using a non-zero value for the 'start' parameter (to start the video playback at a specific time), the very first part of the video still plays before jumping to the later start time. This doesn't happen in Chrome.
I'll look to see if I can find a solution for this and update here.

**Comment by becky-gilbert** [comment]
So I tried lots of reasonable approaches to solve this, none of which worked. 
I did come up with a solution that's a little hacky, so I'm not sure it should be incorporated into the official jsPsych plugin, but it does seem to fix the problem. As soon as I get a chance to put it online, I'll add the link here in case anyone is interested in using it. I'm still hoping to find a better fix...

**Comment by vijaymarupudi** [comment]
Here's my attempt!

  ```javascript
plugin.trial = function(display_element, trial) {

  var video = document.createElement('video')
  var source = document.createElement('source')

  source.src = trial.sources[0];
  console.log(performance.now())
  video.appendChild(source)
  console.log(performance.now())
  display_element.innerHTML = ''
  console.log(performance.now())
  video.pause()
  console.log(performance.now())
  video.onseeked = function() {
  console.log(performance.now())
    display_element.appendChild(video)
  console.log(performance.now())
  }
  console.log(performance.now())
  video.currentTime = trial.start;
  console.log(performance.now())
  video.play()
  console.log(performance.now())
};
```

Here's some messy code. This is a tricky problem indeed. Without the performance.now() calls this plays the video at the specific start time, but with a considerable delay (200ms) from page load time.

The interspersed performance.now() calls reveal that seeking is the event that takes the most time. If we preseek the videos (code at the bottom with setTimeout to simulate), then it's works fine (with a 10ms appendChild() duration). That would mean that jsPsych would need to prepare for this *before* the plugin runs, which I think will be tricky.

I wonder what your solution was @becky-gilbert? Would a 200ms delay be acceptable?

```javascript
var video = document.createElement("video");
var source = document.createElement("source");

source.src = trial.sources[0];
console.log(performance.now());
video.appendChild(source);
console.log(performance.now());
display_element.innerHTML = "";
console.log(performance.now());
video.pause();
console.log(performance.now());
video.onseeked = function() {
  console.log(performance.now());
  setTimeout(() => {
    console.log(performance.now());
    display_element.appendChild(video);
    console.log(performance.now());
  }, 1000);
};
console.log(performance.now());
video.currentTime = trial.start;
console.log(performance.now());
video.play();
console.log(performance.now());
```

**Comment by becky-gilbert** [comment]
Thanks very much for looking into this @vijaymarupudi! I haven't had a chance to test your version yet but will ASAP. Once I have a chance to look at this more closesly, I should have a better idea of what you mean about the 200 ms delay vs pre-seeking options. In any case, one of these will definitely work for my purposes. However I'm not sure what changes (if any) would be appropriate for the main jsPsych video plugins. I'd be interested to know what @jodeleeuw thinks.

I didn't know about the performance.now trick for figuring this out - looks very useful!

I also didn't realise that 'seeking' was the critical event. I was working on the assumption that the video playback would be ready to start immediately after all the data was loaded (even with a non-zero start time), so was trying to use the 'canplaythrough' event to trigger playback, but that didn't work. Adding a 200 ms delay after 'canplaythrough' and play() helped, but still didn't work reliably... Anyway, your solution is definitely better than mine!
