### ISSUE TITLE
video-slider-response plugin: start and slider_start parameters not working

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#713]
In the jspsych-video-slider-response plugin, the `start` and `slider_start` parameters do not seem to be working. I'm using the plugin's example HTML file to test this. 
The video always starts at the beginning, regardless of the `start` value. The start parameter works fine in the two other video plugins. 
The slider is always set to the maximum value, regardless of the `slider_start` value. The slider start parameters work fine in the html and image slider plugins.
This happens in Firefox and Chrome, with no errors in the console. 
It would be great to know if someone else can reproduce this problem, since I think the plugin must've been tested and worked fine when it was added in jsPsych v6.1.0, and I don't know what would cause it to stop working now. 
I'll look for a cause/fix and update here.

**Comment by jodeleeuw** [comment]
> I think the plugin must've been tested and worked fine when it was added in jsPsych v6.1.0, and I don't know what would cause it to stop working now.

😐 😐 😐

**Comment by vijaygopal1234** [comment]
https://github.com/jspsych/jsPsych/blob/83980085ef604c815f0d97ab55c816219e969b84/plugins/jspsych-video-slider-response.js#L186

This is because the `start` option is used for the slider (instead of `slider_start`), and the `slider_start` parameter doesn't appear to be used at all. I'll submit a pull request fixing this now.

**Comment by vijaygopal1234** [comment]
Regarding `start` not working, it looks like there are two elements with the same id, so the video element is not being picked by `querySelector()`. 

https://github.com/jspsych/jsPsych/blob/83980085ef604c815f0d97ab55c816219e969b84/plugins/jspsych-video-slider-response.js#L149

https://github.com/jspsych/jsPsych/blob/83980085ef604c815f0d97ab55c816219e969b84/plugins/jspsych-video-slider-response.js#L180

**Comment by becky-gilbert** [comment]
World's fastest fix. Thanks very much @vijaygopal1234 !!

**Comment by becky-gilbert** [comment]
> > I think the plugin must've been tested and worked fine when it was added in jsPsych v6.1.0, and I don't know what would cause it to stop working now.
> 
> 😐 😐 😐

@jodeleeuw sorry, I genuinely thought that I must've accidentally done something weird with my version to cause it to stop working... :grimacing:

**Comment by jodeleeuw** [comment]
> > > I think the plugin must've been tested and worked fine when it was added in jsPsych v6.1.0, and I don't know what would cause it to stop working now.
> > 
> > 😐 😐 😐
> 
> @jodeleeuw sorry, I genuinely thought that I must've accidentally done something weird with my version to cause it to stop working... :grimacing:

Haha well that's my fault for not having better testing in place!
