### ISSUE TITLE
jsPsych-rdk - downloaded files different to code?

### ISSUE THREAD

**Issue by majorminors** [jspsych/jsPsych#749]
Hello,

Downloaded the 6.1.0 release. Pulled the jsPsych-rdk plugin to my project. Turning the fixation cross "white" had no effect. Deleted and redownloaded the 6.1.0 files. Same issue. However, the code on github [here](https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-rdk.js) works just fine.

Whatever files I'm downloading appear to be different to the code. I attach a comparison. On the left is the file I downloaded as the 6.1.0 release. On the right is the (bugfixed) code from [github](https://github.com/jspsych/jsPsych/blob/master/plugins/jspsych-rdk.js).

i hope this is helpful.

Warm regards,

Dorian

![screen](https://user-images.githubusercontent.com/19422558/84036672-6fd9fe00-a995-11ea-91ec-bb0f3582f98f.jpg)

**Comment by jodeleeuw** [comment]
The `master` branch has been patched since the release of 6.1.0. The new code will be part of the next release. In the meantime, using the file from the master branch as you've done should be totally fine to do.

**Comment by majorminors** [comment]
Cheers!
