### ISSUE TITLE
data.last(n) should gracefully fail is n > total data size

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#751]
See #748 for use case!

**Comment by aridyckovsky** [comment]
After looking through #748, it seems the goal is to gracefully fail when `n` is greater than the number of records, whether that's _total trials_ or _filtered trials_. Is this correct?

It might also be worth looking at the Lodash's [`_.takeRight()`](https://lodash.com/docs/4.17.15#takeRight), which slices an array from the righthand index. Generally, it might be worth looking at more comprehensive packages that handle object structure manipulations.

**Comment by jodeleeuw** [comment]
> After looking through #748, it seems the goal is to gracefully fail when n is greater than the number of records, whether that's total trials or filtered trials. Is this correct?

Right. This particular one should be pretty straightforward to handle, but I hear you on taking inspiration from lodash and other toolkit libraries.
