### ISSUE TITLE
animation plugin produces a delay before showing first stimulus

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#791]
See discussion topic about this: #782

**Comment by jodeleeuw** [comment]
We should have with the release of the 1.0.0 version of the plugin, but I think it's too late now. Just gonna close this issue and it'll be a quiet fix.

**Comment by bjoluc** [comment]
For what it's worth, we could still edit the package changelog and GH release message accordingly to get the same result as a changeset would have yielded.
