### ISSUE TITLE
Add list of options for hosting experiments to jspsych docs

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#822]
See answer in #804 for a starting point.

**Comment by jodeleeuw** [comment]
I like the idea of adding to the introduction. 

I think a new page under the overview section also makes sense. I prefer Hosting > Servers, but maybe something a little more descriptive like "Publishing Your Experiment" or even "Collecting Data From Online Participants" is clearer?

My initial thought was that we wouldn't go into too much detail about each option, and that this is merely a way to point people towards other sets of documentation. I think that makes sense, but if you think it would be feasible/better to have more in-depth documentation then making this it's own section on the same level as Overview would make more sense.

**Comment by becky-gilbert** [comment]
Sounds good. Why don't we try to keep it short and simple, and go with a new page called "Collecting Data From Online Participants" under the overview section. With the more page general title, we can also include a few options for recruitment (Prolific etc.), and briefly explain how those platforms differ from hosting methods.

**Comment by jodeleeuw** [comment]
Sounds perfect 👍 👍

**Comment by becky-gilbert** [comment]
My draft of this page is here: https://github.com/jspsych/jsPsych/blob/docs-6.2/docs/overview/collecting-data.md
It didn't turn out to be as short and simple as I'd intended 😬 Please feel free to comment/edit.

**Comment by jodeleeuw** [comment]
This is great! I made some minor changes. I think it is ready to go, and easily update-able in the future.
