### ISSUE TITLE
allow any parameter from the trial object to be added to the data easily

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#823]
To address things like #808

**Comment by jodeleeuw** [comment]
I've implemented a first pass at this in the `feature-params-in-data` branch. I added a parameter called `save_trial_parameters` that works in any plugin. Like other default parameters it is processed in `jspsych.js` instead of in plugin files. You can use it to specify which properties should be included and excluded from the trial, like this:

```js
var trial = {
	type: 'html-keyboard-response',
	stimulus: '<p>Hello world.</p>',
	save_trial_parameters: {
		stimulus: false, // exclude the stimulus parameter from saved data
		choices: true // add the value of choices (works even if using the default value for the plugin
	}
}
```

**Comment by jodeleeuw** [comment]
A few quick thoughts of next steps:

- We should probably add test cases for saving parameters that are objects, arrays, and functions to the data to ensure it behaves as we want. (Not sure what we want when the parameter is a function -- not a dynamic parameter, but an actual function like in the reconstruction plugin).
- Some plugins save trial parameters right now and others don't. This method works for either case because you can exclude things that are saved by default. But I think we should change the way we program plugins to do this. We should probably add a property to `plugin.info` that specifies which parameters are recorded in the data by default. This way including the property via this new method and having the plugin include it by default will always include the same representation of the data. In the current way a plugin writer could save a value in `stimulus` that is a modified version of the actual trial parameter, for example.

**Comment by bjoluc** [comment]
> But I think we should change the way we program plugins to do this. We should probably add a property to plugin.info that specifies which parameters are recorded in the data by default.

@jodeleeuw Sounds insanely useful, let's do this in 8.0!
