### ISSUE TITLE
broken links in documentation to plugin data

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#827]
Via @CarolynBuck-Gengler. Thanks!

> In at least three of the plugin pages I have looked at (and I’m guessing this would be true for most or all), in the section where the data generated are described, there is first a paragraph “In addition to the default data collected by all plugins, this plugin collects the following data for each trial.” that has a link, and the link is broken (404 - Not found).

> For example, when I click it in the html-keyboard-response page, it goes to https://www.jspsych.org/plugins/jspsych-html-keyboard-response/overview#datacollectedbyplugins
Similarly, when clicked from the instructions plugin page, it goes to https://www.jspsych.org/plugins/jspsych-instructions/overview#datacollectedbyplugins

> However, I’m guessing (based on poking around) that all of them should actually be going to the middle of the page https://www.jspsych.org/plugins/overview/

**Comment by becky-gilbert** [comment]
Thanks @CarolynBuck-Gengler! The docs files have been updated with the correct link now and the changes will be updated on the live site when v6.2 is released (if not sooner).
