### ISSUE TITLE
Custom CSS class per trial

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#832]
From #831:

> This is a design issue with the library that we've been thinking about for some time. I think we're likely to add a feature in the future that adds a custom class to the display element so that styles can be specified in a <style> tag or stylesheet.

> The feature might look like this:

```js
var trial = {
	type: 'html-keyboard-response',
	stimulus: 'apple',
	css_classes: ['large-text']
}
```

> And that would add the class .large-text to the root HTML element of jsPsych for that trial. Then one could specify CSS rules that applied to that class.

**Comment by jodeleeuw** [comment]
I added a first pass at this feature in the `feature-css-class-trial` branch. It uses the same syntax described above. The testing suite is kind of minimal at the moment. It would be good to expand it to include things like:

- Making sure that the property is inherited in nested timeline structures
- Making sure it works with functions
- Making sure it works with timeline variables
- Adding a warning message if the given list is not an Array, or deciding to gracefully handle the case where a single class is given instead of an array. Open to either option.

**Comment by jodeleeuw** [comment]
Added testing to cover above. 

Implementation gracefully handles case where a single class is given in non-array format.

Still need to add docs.

**Comment by becky-gilbert** [comment]
Just updated `feature-css-class-trial` with the following:
- added `css_class` to the docs page about parameters available in all plugins (plugins/overview/#parameters-available-in-all-plugins)
- added an example HTML page (examples/css-classes-parameter.html)

I'm still trying to understand the main use cases for this feature so that I can include some useful examples. From what I can tell, this will only ever add the custom CSS class to the `jspsych-content` div, which means that it can't be used to directly style the child elements, and instead will rely on CSS inheritance. And the relevant CSS properties that are inherited seem to be mostly text/font related (here's a [list from stackoverflow](https://stackoverflow.com/questions/5612302/which-css-properties-are-inherited)). I don't think it's possible to do much with size and positioning. I wrote a comment about this limitation of the `css_class` parameter in the example HTML file - it'd be good to know if I'm wrong so that I can correct it!

**Comment by jodeleeuw** [comment]
I think this can be used to control styles in more detail because you can specify CSS selectors that depend on parent elements. So if you set the CSS class `.left-align` on the `jspsych-content` div you can specify a rule like:

```css
.left-align p.stimulus { text-align: left; }
```
And this would affect any `<p>` tag with the class `stimulus` that is within an element with class `left-align`. 

I think this allows one to do some clever things with timeline variables, because you could make a timeline variable that controls style without implementing lots of custom HTML inside the timeline variables.

**Comment by becky-gilbert** [comment]
Aha, thanks! That's what I was missing. I'll update my example HTML file to show how to do this.

**Comment by becky-gilbert** [comment]
Updated docs and examples. Ready to merge?

**Comment by jodeleeuw** [comment]
Looks awesome. Do you think it's worth adding a mention anywhere in the Overview section of the docs? Worried that it's hard to find right now, but maybe the feature isn't so important to highlight. I'm on the fence.

**Comment by becky-gilbert** [comment]
Yes, good idea.
One option is to add a section that _only_ covers the `css_classes` parameter.
Another option is to add a section that's about change style/formatting more generally - maybe just explaining that you can do this in a few different ways, with very basic examples of each: 
- inline style in an HTML string
- style tags (with the limitation that the CSS rules work the same way across all trials)
- style tags along with the `css_classes` trial parameter

Either way, I'm thinking that this section could go in Overview on the "Advanced Options for Trials" page. What do you think?

**Comment by jodeleeuw** [comment]
I like your idea of covering style/format more generally. I think that would be very useful. Maybe even it's own page within Overview. I think that the "advanced options" page is poorly named (I named it!) and maybe we could even bump dynamic parameters to its own page as well?

**Comment by becky-gilbert** [comment]
Sounds good! I'll add a new page within Overview for general style/formatting. Not sure what to name it yet...

And I agree about the "advanced options" page name (sorry!). I think Dynamic Parameters deserves it's own page.

**Comment by becky-gilbert** [comment]
I added a first draft of a new "Style and Formatting" page to go in the Overview section of the docs. I may have gone overboard - sorry 😬 Please feel free to comment/edit mercilessly!

I also made some changes to the "css-classes-parameter.html" example file, such as adding examples that show how to write more specific CSS selectors, as explained in your [earlier comment](https://github.com/jspsych/jsPsych/issues/832#issuecomment-759086128). Again, happy to get feedback on how to improve this example file.

**Comment by jodeleeuw** [comment]
This is amazing. I think it's going to be super helpful for lots of folks! I read through it quickly to get a sense of scope and I think the thoroughness is excellent here. I didn't read closely for minor edits, but I can do that later if you'd like. I'm also not worried about it and think you can go ahead with this if you are happy with it.

**Comment by becky-gilbert** [comment]
Yay, great! No need to look at it more closely right now - I just wanted your thoughts on the general scope and level of detail etc. It'd be great if at some point you could have a closer look for minor edits and to improve the examples.

This feature seems to be working well and I think we're done with the tests and docs, so ready to merge? (I can remind you to look at the Style and Formatting page again before we release 6.3 😃)

**Comment by jodeleeuw** [comment]
🚀 merge away!
