### ISSUE TITLE
Adding prompt to serial-response-time-mouse destroys event listeners

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#840]
see https://github.com/jspsych/jsPsych/discussions/837

**Comment by becky-gilbert** [comment]
@jodeleeuw just fixed this. Does it require a test?

**Comment by jodeleeuw** [comment]
I don't think so. While it can't hurt to have more tests, we have lots of other plugins where even listeners could be destroyed in similar ways but don't have tests set up for them. Probably not a high enough priority to fix that.

**Comment by becky-gilbert** [comment]
Ok thanks!
