### ISSUE TITLE
Allow timelineVariable() to work in functions with no modification

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#883]
See @vijaymarupudi's solution here: https://github.com/jspsych/jsPsych/discussions/788#discussioncomment-30717

**Comment by jodeleeuw** [comment]
I implemented this in the `feature-timeline-variable-simplify` branch based off of @vijaymarupudi's approach. It seems to work well! One thing I had to add was switching the `call_immediate` context before other kinds of callbacks, like `loop_function`, `conditional_function`, `on_finish`, etc. I am worried that I missed some particular context, so adding some additional tests would be really helpful.

I also left in the option to explicitly set the second parameter to `true` and force the function to evaluate immediately. This is mainly a protection against us missing a context where someone wants it to evaluate immediately. Rather than having to rush out a patch we can point to the override option and we can fix that context more leisurely.

**Comment by jodeleeuw** [comment]
I added a bunch of tests for this. I am pretty confident it works in all the major places it might be used. Need to update docs still.

**Comment by becky-gilbert** [comment]
Assigning myself so that I know to update the docs. Just let me know if you're still working on this and/or want me to do anything other than docs.

**Comment by jodeleeuw** [comment]
I think the code is good here. Feel free to add docs and then merge!
