### ISSUE TITLE
Images don't present consecutively in jspsych-animation (for firefox only)

### ISSUE THREAD

**Issue by hellenjingyuan** [jspsych/jsPsych#891]
I was trying to present 60 images as an animation, I found the plugin jspsych-animation doing exactly that (thank you so much). I want all 60 images to present one after another without breaks in between, so I set ```frame_isi``` to be 0. When running the script in Chrome, the animation presents without breaks between images, but when running in Firefox, the animation 'blinks' so much and it seems that there is an isi after each image.

**Comment by vijaymarupudi** [comment]
Did you preload all the images that you're using for the task?

**Comment by hellenjingyuan** [comment]
Yes I preloaded all the images in ```jsPsych.init```. I also tried preloading the images relevant for each trial prior to the trial (because different trials may present different image sets). 

When using Chrome, just preloading all images at the beginning of the experiment is sufficient for smooth animations. When using Firefox, both preloading methods failed to produce smooth animations.

**Comment by vijaymarupudi** [comment]
I see... It is likely that this is a problem that cannot be fixed without changing the plugin, but before that, could you investigate if the images are being redownloaded in Firefox when they are shown using the [Network Monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor)?

**Comment by hellenjingyuan** [comment]
When my code preloads the images only at the beginning of the experiment, the Network Monitor is always empty in Firefox (but in Chrome the Network Monitor shows all images were loaded).

**Comment by jodeleeuw** [comment]
We'll need to investigate this further to figure out if preloading behavior has changed in recent browser updates. I'll add it to one of our milestones. Thanks for flagging this issue.

**Comment by vijaymarupudi** [comment]
Try using this strategy instead of jsPsych's default one

```javascript
function preloadImage(url) {
  return fetch(url)
    .then(x => x.blob())
}

function preloadImages(images) {
  return Promise.all(images.map(preloadImage))
}


preloadImages(listOfImages)
  .then(() => {
    jsPsych.init(...) 
  })

```

**Comment by hellenjingyuan** [comment]
Thank you! I tried your code but got these error messages:
![图片](https://user-images.githubusercontent.com/63465319/88035537-38d13d80-cb3a-11ea-8c39-a239d38da7ce.png)

**Comment by becky-gilbert** [comment]
I think I was able to reproduce this. Here's the cognition.run demo: https://elivpqnmqw.cognition.run

In Firefox, according to the network tab, the images are preloaded/cached successfully when the page loads, and not requested again when the animation starts. But still I do see some flashing between images during the first run through the image sequence, then the animation runs smoothly after that. So the behavior seems consistent with the images not preloading, but the network tab says that they are...

Can someone else check this out in Firefox and let me know if they're seeing the same thing, please?
