### ISSUE TITLE
Accessing trial number for correct response if statement

### ISSUE THREAD

**Issue by sammartin8** [jspsych/jsPsych#893]
I am fairly new to coding, and I am trying to program a basic working memory experiment. I have been able to program an experiment in which one colored circle appears on the screen, followed by another, with a 5 second intermission in between presentations. I have only been able to do this for one repetition; however, because the if statement I used to compare the two stimuli have hard coded indices. I need the numbers to be able to change depending on the repetition number (for example: the first index would need to be 2,8,14,20,26 and the second index would need to be 3,9,15,21,27 for the first 5 trials). I thought that if I could access the trial or repetition number then I could get these numbers with some simple math. I'd appreciate any help. If I am going about programming this experiment the wrong way, please let me know.

**Comment by vijaymarupudi** [comment]
Hello!

Can you post your code as text following the directions here: <https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks>

**Comment by sammartin8** [comment]
I can't seem to get this link to work. I've tried on several devices and I get the same error.

**Comment by sammartin8** [comment]
'''
<!DOCTYPE html>
<html>
    <head>
        <title>Lexical Decision</title>
        <script src="JSPsych/jspsych.js"></script>
        <script src="JSPsych/plugins/jspsych-html-keyboard-response.js"></script>
        <script src="JSPsych/plugins/jspsych-instructions.js"></script>
        <link href="JSPsych/css/jspsych.css" rel="stylesheet">
    </head>
    <body></body>
    <script>
        var timeline = [];
        
        var instructions = {
            type: 'instructions',
            pages: ['Welcome!','<p>Press the f key when you see a nonword and press the j key when you see a word!</p><p>Click the next button to start!</p>'],
            show_clickable_nav: true
        };
        timeline.push(instructions);
        
        var fixation = {
            type: 'html-keyboard-response',
            stimulus: '<span style="font-size: 40px;">+</span>',
            choices: jsPsych.NO_KEYS,
            trial_duration: 1000
        };
        
        var lexical_decision_trial = {
            type: 'html-keyboard-response',
            stimulus: jsPsych.timelineVariable('stimulus'),
            choices: ['f','j'],
            stimulus_duration: 2000,
            data: {condition: jsPsych.timelineVariable('condition'), correct_response: jsPsych.timelineVariable('correct_response')},
            post_trial_gap: 1000,
            on_finish: function(data){
                var accuracy = false;
                if (data.correct_response == jsPsych.pluginAPI.convertKeyCodeToKeyCharacter(data.key_press)) {
                    accuracy = true;
        }
                data.accuracy = accuracy;
        }
        };
        
        var feedback = {
            type: 'html-keyboard-response',
            stimulus: function() {
                var feedback_text = '<span style="30px;color:red">Incorrect</span>';
                var last_trial_accuracy = jsPsych.data.getLastTrialData().values()[0].accuracy;
                if (last_trial_accuracy == true) {
                    feedback_text = "Correct!"
                }
                return feedback_text
            },
            choices: jsPsych.NO_KEYS,
            trial_duration: 3000
        };
        
        var trial_info = [
            {stimulus: '<span style="font-size: 40px;">apple</span>', condition: 'word', correct_response: 'j'},
            {stimulus: '<span style="font-size: 40px;">tree</span>', condition: 'word', correct_response: 'j'},
            {stimulus: '<span style="font-size: 40px;">moxid</span>', condition: 'nonword', correct_response: 'f'},
            {stimulus: '<span style="font-size: 40px;">orap</span>', condition: 'nonword', correct_response: 'f'}
        ];
        
        var lexical_decision_procedure = {
            timeline: [fixation,lexical_decision_trial,feedback],
            timeline_variables: trial_info,
            randomize_order: true
        };
        
        timeline.push(lexical_decision_procedure);   
            
        jsPsych.init({
            timeline: timeline,
            on_finish: function() {
                jsPsych.data.displayData();
        }
        })
    </script>
</html>
'''

**Comment by sammartin8** [comment]
<!DOCTYPE html>
<html>
  <head>
    <title>My experiment</title>
    <script src="jspsych/jspsych.js"></script>
    <script src="jspsych/plugins/jspsych-html-keyboard-response.js"></script>
    <script src="jspsych/plugins/jspsych-image-keyboard-response.js"></script>
    <link href="jspsych/css/jspsych.css" rel="stylesheet" type="text/css">
  </head>
  <body>
  <script>
    
    var timeline = []

    var welcome = {
        type: "html-keyboard-response",
        stimulus: "Welcome to my experiment. Click any key to see the instructions!"
    };
    timeline.push(welcome);
      
    var instructions = {
        type: 'html-keyboard-response',
        stimulus: "<p>In this experiment, you will be presented with a series of orange and blue circles.</p><p>For each trial, you will be presented one circle for 2 seconds, followed by another circle, with a 5 second intermission between presentations.</p><p>After each pair of circles, you will the be asked to indicate if the circles were the same color or different colors.</p><p>Click any key to begin!</p>"
    }
    timeline.push(instructions);
    
    var trial_1 = {
        type: 'image-keyboard-response',
        stimulus: function () {
            var num_1 = Math.floor(Math.random() * 2)
            if (num_1 === 0)
                return 'jsPsych/examples/img/orange.png'
            else
                return 'jsPsych/examples/img/blue.png'
        },
        choices: jsPsych.NO_KEYS,
        trial_duration: 2000,
        post_trial_gap: 5000
    };
      
    var trial_2 = {
        type: 'image-keyboard-response',
        stimulus: function () {
            var num_2 = Math.floor(Math.random() * 2)
            if (num_2 === 0)
                return 'jsPsych/examples/img/orange.png'
            else
                return 'jsPsych/examples/img/blue.png'
        },
        choices: jsPsych.NO_KEYS,
        trial_duration: 2000,
        post_trial_gap: 1500
    };

      
    var question = {
        type:'html-keyboard-response',
        stimulus: "<p>Were the circles the same color?</p><p>Press 'y' for yes and 'n' for no</p>",
        choices: ['y','n'],
        data: {correct_response: function() {
            if (jsPsych.data.get().select('stimulus').values[2] === jsPsych.data.get().select('stimulus').values[3]) 
                return 'y'
            else 
                return 'n'
        }
              },
        on_finish: function(data){
            var accuracy = false;
            if (data.correct_response === jsPsych.pluginAPI.convertKeyCodeToKeyCharacter(data.key_press)) {
                accuracy = true;
            }
            data.accuracy = accuracy;
        },
        post_trial_gap: 1000
    };
      
    var feedback = {
            type: 'html-keyboard-response',
            stimulus: function() {
                var feedback_text = '<span style="30px;color:red">Incorrect</span>';
                var last_trial_accuracy = jsPsych.data.getLastTrialData().values()[0].accuracy;
                if (last_trial_accuracy == true) {
                    feedback_text = "Correct!"
                }
                return feedback_text
            },
            choices: jsPsych.NO_KEYS,
            trial_duration: 3000
    };
      
    var working_memory_procedure = {
        timeline: [trial_1,trial_2, question, feedback],
        repetitions: 5
    };
    timeline.push(working_memory_procedure);
      
    jsPsych.init({
            timeline: timeline,
            on_finish: function() {
                jsPsych.data.displayData();
        }
        });
  
  </script>
  </body>
  </html>

**Comment by jodeleeuw** [comment]
Hi @sammartin8 !

I assume that you are talking about the indices here:
```js
if (jsPsych.data.get().select('stimulus').values[2] === jsPsych.data.get().select('stimulus').values[3]) 
```
One way to solve this would be to use the `.last()` function to get only the last two trials worth of data:
```js
if (jsPsych.data.get().last(2).select('stimulus').values[0] === jsPsych.data.get().last(2).select('stimulus').values[1]) 
```

In terms of general tips, I'd encourage you to take a look at [timeline variables](https://www.jspsych.org/tutorials/rt-task/#part-5-timeline-variables) as a way to organize the scaling-up of the code. You could include variables for the color of the first and second circle, and since you'd know the colors of both circles when you declared the variables you could also just add a variable for what the correct response is in the question part of the task.

**Comment by sammartin8** [comment]
Thank you!
