### ISSUE TITLE
Core library support for randomization

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jsPsych#9]
The core library could include some methods for randomization of order and such, since plugins don't support this. 

A basic version would just be to include something like the underscore.js shuffle method.

More sophisticated options would be sample N from a list with and without replacement, etc..

Also, a common use case is to define a set of variables that go together:

``` javascript
var trials = [
     {param1: value, param2: value, param3: value},
     {param1: value, param2: value, param3: value},
     {param1: value, param2: value, param3: value}
];
```

But, plugins work by taking arrays of like parameters:

``` javascript
var plugin_block = { ..., param1: [value1, value2, value3], param2: [value1, value2, value3], ... }
```

So a useful randomization method would take an object like `trials`, shuffle the order, sample N times, and then return the needed arrays.

**Comment by mizzao** [comment]
> The b/w subject randomization is tricky to do reliably balanced, because you then need to communicate with the database to know the actual distribution of assigned conditions and compare that to the target distribution to choose the condition for the next subject.

Did you folks ever figure out a way to reliably do between-subject randomization?

One low-tech way to do it if you don't have a database, but know the number of participants 2X in advance: 

1. Generate an array of X `a`'s and X `b`s.
2. Randomly shuffle the array.
3. Assign a unique number `i` between 1 and 2X to each participant. (The participant or administrator can manually enter in this number.)
4. Index into the array with `i` to determine what treatment each participant should get.

You can do the same thing with latin squares, etc. Is there an easy way to implement this in JsPsych or an example for something similar? Or is there an other, better way to do it?

**Comment by jodeleeuw** [comment]
Hi @mizzao!

I think your method works when running a study in the lab. (Another option would be to enter the condition id directly, and do the randomization outside jspsych.) I am not sure how you could assign a unique number to each subject without a database when running the study online. You would need to somehow keep track of how many people had started the experiment in order to identify the next participant's number, and that seems to require a database.

You can achieve step 1 and 2 of the algorithm with jsPsych.randomization.repeat().
