### ISSUE TITLE
jsPsych.addNodeToEndOfTimeline() bug

### ISSUE THREAD

**Issue by bjmeagher** [jspsych/jsPsych#918]
Just noticed a bug in the code for this function on line 312 of jspsych.js (version 6.1.0). The word "undefined" is misspelled, leading to the function making a callback function a mandatory second argument.

**Comment by vijaymarupudi** [comment]
Duplicate of https://github.com/jspsych/jsPsych/issues/688

**Comment by jodeleeuw** [comment]
Thanks @bjmeagher ! We will patch this in 6.2
