### ISSUE TITLE
rdk plugin - dots move in opposite direction to specified

### ISSUE THREAD

**Issue by majorminors** [jspsych/jsPsych#922]
Hello,

I'm not sure if this is a bug, or if this is something I'm doing wrong.

## version
6.1.0

## plugin
jsPsych rdk

## expected behaviour
Dots move at direction in degrees as specified in code

## actual behaviour
For some ranges of degrees, dots move in the exact opposite direction to that specified in code

## detail and links to example
Using the rdk plugin, I have users respond to a cue indicating two possible directions of the dot motion. Users must classify the dot motion as going in one direction or the other, each trial. The possible directions rotate every so often (e.g. trials one through forty: dots move at either 45 degrees or 225 degrees, trials 40 through 80: dots move at either 135 degrees or 315 degrees).

In the case where the two possible directions are 45 degrees and 225 degrees the dots work as expected. In the case where the two possible directions are 135 or 315 degrees, the dots appear to move in the exact opposite direction than specified in the code.

I have created a minimal example of the problem, to illustrate what I mean:

[Minimal example](https://github.com/majorminors/evaccum-js/blob/coh_dir_bug/coh_issue_test.html)

You can either clone the repo or insert the file into an existing jsPsych directory. If you do the latter you will need four lines of additional css, as well as four cue images:

[CSS edits](https://github.com/majorminors/evaccum-js/blob/coh_dir_bug/tools/exp.css)
[Cue images](https://github.com/majorminors/evaccum-js/tree/coh_dir_bug/stimuli)

Interested to hear any pointers as to what I'm doing wrong, or how to debug the issue. Anything at all really!

Warm regards,

Dorian

**Comment by becky-gilbert** [comment]
Closing this as the problem was a misunderstanding about how the `coherent_direction` parameter works, as @vrsivananda explained on the discussion forum (#932). Thanks again @vrsivananda!
