### ISSUE TITLE
It's possible to click below the buttons in some of the plugins (+ possible fix)

### ISSUE THREAD

**Issue by Speldosa** [jspsych/jsPsych#954]
When, for example, running the `jspsych-image-button-response.html` example, it is possible to click below the buttons and still register a response. When inspecting the elements, it can be seen that the buttons actually extends below what can be seen of them.

I solved this by commenting out line 63 in the `jspsych.css` file, that says

    margin-bottom: 2em;

This fixed the problem for me, and everything looks normal in the example, but I don't know if this fix breaks something else.

**Comment by jodeleeuw** [comment]
Hi @Speldosa ,

I'm having trouble reproducing this problem. What browser/OS are you seeing this issue on?

**Comment by jodeleeuw** [comment]
Also, what version of jsPsych are you using? I think in the current CSS file the line you are referencing doesn't exist.

https://github.com/jspsych/jsPsych/blob/83980085ef604c815f0d97ab55c816219e969b84/css/jspsych.css#L59-L77

**Comment by Speldosa** [comment]
Oh, I am on v6.1.0, the latest release, but when I download it again I do realize that the line in question isn't there. It would be really embarrassing if this was a change I made myself and then forget about, so it definitely can't be that 🙃 Anyhow, I guess this issue can be closed then.
