### ISSUE TITLE
Present images conseuctively (no white flash)

### ISSUE THREAD

**Issue by chif56** [jspsych/jsPsych#969]
Hi,
I found that images were interrupted in between (flashed white) when I presented them using the way of Timeline variables (https://www.jspsych.org/overview/timeline/) with image-keyboard-response as "type" (although they were preloaded).
The same issue was found when I used the animation plugin instead.

Partially changing the code seemed to solve this (from line 80 to line 106 in the plugin code).
I used the following approach:
    
     
    plugin.trial = function(display_element, trial) {
    
        var canvas = document.createElement("canvas");
        display_element.append(canvas);
		
        //Remove the margins and padding of the canvas
        canvas.style.margin = 0;
        canvas.style.padding = 0;
		
        //Get the context of the canvas
        var ctx = canvas.getContext("2d");
	
        var img = new Image();   
        img.src = trial.stimulus;  
        var width = canvas.width = img.width;
        var height = canvas.height = img.height;
        ctx.drawImage(img,0,0);
		

        // store response
    ...

It seems to work on the several browsers (firefox, edge, google chrome, and safari) and record reaction time properly.
(Maybe this could work for  #891?)

**Comment by jodeleeuw** [comment]
Interesting!

I wonder if this is because the `<canvas>` element renders faster than an `<img>` element or if it is because the cache is utilized for the `<canvas>` but not the `<img>`.

In your testing, did you happen to open the Network tab of the debugger to see if the images were requested/sent again for the unmodified plugin, but not for the modified one?

**Comment by chif56** [comment]
I did not test with the original plugin, but I guess the images were not requested again for mine?
![Screen Shot](https://user-images.githubusercontent.com/69618207/91245863-77859380-e789-11ea-9409-e739bf904d9c.png)

**Comment by becky-gilbert** [comment]
Hi @chif56, I was able to reproduce this problem with blank screen flashes between consecutive images (though it only happens for me in Firefox), and found that your solution of rendering the image on a canvas element solves the problem. I don't see any evidence that the cached images aren't being used with the `<img>` element (i.e. the images are not requested again when the trials start). I'm not sure why this works, but like Josh says, maybe it has do with rendering being faster with `<canvas>` than `<img>`. Anyway, we'll add a new `render_on_canvas` parameter in all image plugins that will implement this. 

Thanks very much for catching this problem and sharing your solution!

**Comment by chif56** [comment]
Thank you @becky-gilbert !
