### ISSUE TITLE
Allow nested parameter values to be functions

### ISSUE THREAD

**Issue by becky-gilbert** [jspsych/jsPsych#988]
As in #986 (dynamic prompt for likert questions).

**Comment by jodeleeuw** [comment]
I think this is now working on the `feature-nested-function-parameters` branch. There is a theoretical use case that I think won't work. If you had a nested parameter where you *wanted* one of the parameters to be a function that was **not** evaluated prior to loading the trial then the approach I've implemented has no way of detecting that. This may be worth adding before we merge it in. I could imagine, for example adding a `validation_function` parameter to survey type plugins where you want to pass a function to be evaluated for each question in the nested `questions` parameter.

**Comment by jodeleeuw** [comment]
@becky-gilbert I've added some additional functionality to protect nested function parameters from early evaluation. Wrote a test for this and everything seems to be OK. Handing it over to you now.
