### ISSUE TITLE
Inappropriate looping technique throws error when attributing default parameters

### ISSUE THREAD

**Issue by egaudrain** [jspsych/jsPsych#989]
In [jspsych.js](https://github.com/jspsych/jsPsych/blob/master/jspsych.js#L919), in the `setDefaultValues` definition, in the case where the variable type is COMPLEX and is an array, the items of the array are looped on using:

```javascript
for(var i in trial[param]){
   ...
}
```

However if the Array prototype has been extended, the `in` method will also include the new methods added to the prototype, which triggers the `console.error` on line 930. For that reason it seems to be recommended to use [another technique](https://stackoverflow.com/questions/3010840/loop-through-an-array-in-javascript) to loop through the elements of the array.

To avoid the problem I was facing, I replaced the lines above with:

```javascript
trial[param].forEach(function(ip, i){
   ...
});
```

I guess one of the advantages of the `in` technique is that it would also loop through the properties of an object if the parameter is not truely an Array. But with a quick scan I couldn't see anything that'd be broken with the proposed change.

**Comment by jodeleeuw** [comment]
Thanks for flagging this issue! If you'd like to submit a PR we will merge with the 6.2 release. Otherwise we'll patch on our own.

**Comment by egaudrain** [comment]
Thanks for your brisk response! I submitted a PR jspsych#990.
